open-telemetry/opentelemetry-specification

specification/library-layout.md

fix typo compoents -> components

---

specification/logs/data-model.md

Fixes #1868
Adds a section to the logs spec referring to the semantic conventions for exception-related attributes.

Refer and link to exception semantic conventions

---

specification/logs/data-model.md

`host.hostname` attributed  was removed from unified model https://github.com/open-telemetry/opentelemetry-specification/pull/838. We want to use `host.name` attribute to represent Splunk HEC  "host" field instead.
`host.name` attribute already being used for HEC <-> unified model translation. This PR is just up update the spec

Update host field in mapping from HEC to the Unified model

---

specification/metrics/sdk.md
specification/sdk-environment-variables.md

Exemplar environment variable configuration doesn't match lower-case convention in other SDK environment variable parameters.
Hat tip to @anuraaga for calling this out.
_Note: This change is still ok because Metrics SDK specification is not stable, and this is not a new feature, just a change to an existing one.  I believe there is no (released) implementation  of this feature yet._

Update env variable values to match other env variables.

---

CHANGELOG.md
semantic_conventions/trace/rpc.yaml
specification/trace/semantic_conventions/rpc.md

The concept of "streaming" is supported by multiple protocols including gRPC, but also others.

Avoid using gRPC when generic RPC systems have same properties

---

CHANGELOG.md
specification/protocol/exporter.md

As discussed in yesterday's Spec SIG call, allow SIGs to define their own default. Specially important as OTel JS will be going GA very soon, and we want to allow it to use gzip as their default (at least for the browser case) - also a motivating reason to include this change in this week's Specification release.
(Also removed the mention of SIGs supporting other compression methods, as they should be vetted first by the Collector, etc)
Alternative to #1895 
cc @dyladan @bogdandrutu

Allow implementations to use their own default for OTLP compression.

---

CHANGELOG.md
specification/protocol/otlp.md

As mentioned in #1923 we need to be explicit on the compression support for the transports on the client AND server side (i.e.g collector receivers at this time).
cc @tigrannajaryan @bogdandrutu

Clarify OTLP server components MUST support none/gzip compression.

---

CHANGELOG.md
specification/library-guidelines.md
specification/metrics/api.md
specification/metrics/sdk.md

* Added concurrency/compatibilty requirements section in the Metrics SDK
* Added `MetricReader.Shutdown`
* Updated the ToC

Multiple improvements to the Metrics SDK

---

specification/metrics/supplementary-guidelines.md

Related to #1873 and #1891.
If you find it hard to look at the raw markdown file, here is a rendered version https://github.com/reyang/opentelemetry-specification/blob/reyang/guideline/specification/metrics/supplementary-guidelines.md.

Add metrics spec supplementary guidelines

---

spec-compliance-matrix.md

cc @jtescher 
Update Rust's support for OTLP/HTTP binary protocol
Related issues #1885

Update Rust's support for OTLP/HTTP binary protocol

---

CHANGELOG.md
specification/protocol/exporter.md

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/1885

Make OTLP/HTTP the recommended default transport

---

CHANGELOG.md
specification/logs/data-model.md
specification/logs/semantic_conventions/README.md
specification/logs/semantic_conventions/media.md

Resolves #1772 
Adds semantic conventions for file log source.

Add semantic conventions for log media attributes

---

specification/common/common.md

- Provide a normative definition of **attribute** (singular), rather than **attributes** (plural).
- Other copyedits
Preview (GH): https://github.com/chalin/opentelemetry-specification/blob/patch-1/specification/common/common.md#attribute
/cc @austinlparker @tedsuo

Provide a normative definition of Attribute (singular) rather than Attributes (plural)

---

specification/metrics/semantic_conventions/README.md
specification/metrics/semantic_conventions/runtime-environment-metrics.md

A 'process.runtime' namespace is currently defined in the resource
semantic conventions. The metric semantic conventions suggest that
runtime metrics use a 'runtime' namespace. Since the runtime metrics
are directly related to the runtime resources, they ought to share a
common namespace.
Related to issue #2061, discussed in [this comment](https://github.com/open-telemetry/opentelemetry-specification/pull/2061#discussion_r740509308).

Align runtime metric and resource namespaces

---

CHANGELOG.md
specification/metrics/sdk_exporters/in-memory.md
specification/metrics/sdk_exporters/otlp.md
specification/metrics/sdk_exporters/stdout.md

Move the metrics exporters spec to feature-freeze (except for Prometheus exporter, which will need more time).

Move Metrics In-memory/OTLP/Stdout exporters to Feature-freeze

---

Makefile
specification/baggage/api.md
specification/common/attribute-naming.md
specification/common/common.md
specification/context/api-propagators.md
specification/context/context.md
specification/glossary.md
specification/metrics/README.md
specification/metrics/api.md
specification/metrics/datamodel.md
specification/metrics/sdk.md
specification/metrics/supplementary-guidelines.md
specification/overview.md
specification/protocol/otlp.md
specification/sdk-configuration.md
specification/trace/api.md
specification/trace/sdk.md
specification/vendors.md
specification/versioning-and-stability.md

Enures that all ToCs are uniformly wrapped in:
- `` and `` so that they get regenerated by `markdown-toc` and checked during CI
- `<details><summary>Table of Contents</summary>` ... `</details>`
/cc @austinlparker

[editorial] Ensure all ToCs are generated using markdown-toc

---

CHANGELOG.md
specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2130

Remove the concept of supported temporality, keep preferred

---

specification/compatibility/opentracing.md

Addresses part of #2147 by stating that ONLY error mapping must happen in the OT Shim layer, as opposed to do any other semantic convention mapping.
cc @jmacd @yurishkuro

State that ONLY error mapping can happen in the OT Shim layer.

---

specification/compatibility/opentracing.md
specification/context/context.md
specification/glossary.md

Fixes #1511 ; since I was looking into adding the term service already, I thought I could also give this one a try. Hope it helps:)
- Update glossary to contain a definition of the term execution unit
- Link back from opentracing.md and context.md where this term is used

Add execution-unit to glossary.md

---

spec-compliance-matrix.md

(Doesn't fix an issue, I just happened to notice it just now)
More up-to-date Zipkin support was recently landed in opentelemetry-php ([link to tracking issue](https://github.com/open-telemetry/opentelemetry-php/issues/295)) so this fills out that column of the spec compliance matrix file based on the current state of the Zipkin exporter

Update Zipkin section for PHP

---

specification/metrics/sdk.md

`would be` seems to be wording that would be intended for an end user, but the spec is for implementation authors so MUST seems like what was intended (though let me know if it's SHOULD)

Change some would be -> MUST in metrics spec.

---

specification/metrics/sdk.md

If the SDK doesn't apply a default aggregation, what can it do? This seemed like a MUST to me but if not, I think this could be changed to also mention a potential alternative.

Clarify SDK must apply a default aggregation if not specified.

---

specification/metrics/sdk.md

Fixes part of #2149.
Changes:
* replace "aggregator" with "aggregation"
* rewrap lines
* add a note to recommend implementers to reserve the "aggregator" term for future use

Metrics SDK - consolidate the aggregation/aggregator term

---

specification/metrics/sdk.md

Fixes a typo in `specification/metrics/sdk.md`.

Fix typo in metrics/sdk

---

CHANGELOG.md
specification/metrics/sdk_exporters/in-memory.md
specification/metrics/sdk_exporters/otlp.md
specification/metrics/sdk_exporters/stdout.md

This has a dependency on the MetricExporter spec, so it should wait for #2150 to be merged.

Mark In-Memory/OTLP/Stdout exporters as Stable

---

CHANGELOG.md
spec-compliance-matrix.md
specification/sdk-environment-variables.md

This PR adds the environment variable to support configuration of log exporters as is supported for metrics and traces today.
This variable was mentioned in the conversation here https://github.com/open-telemetry/opentelemetry-specification/issues/1309#issuecomment-751991068

adding environment variable for OTEL_LOGS_EXPORTER

---

specification/logs/data-model.md

Clarifies that log name field is a low cardinality event classifier. 
Resolves #2074.

Clarify log name field

---

specification/metrics/sdk.md

Fixes #2155
Fixes #2193
- improves description of Exemplars, including use-case.
- Clarify `measurement` as coming from API, and record time.
- Clarify `reset` behavior for `num_measurements` counters.

Clarify confusing aspects of exemplar specification.

---

specification/metrics/semantic_conventions/openmetrics-guidelines.md

Since it was moved to opentelemetry-collector-contrib repo

Update link to Prometheus Receiver Design Document

---

CHANGELOG.md
specification/logs/data-model.md

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/1875
See the issue above for the detailed discussion. A summary here:
Currently, logs data model describes a single (optional) [`Timestamp` field](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-timestamp) which describes when the event occurred
Unlike for e.g. spans, there are at least three ways a log record can have timestamp associated:
1. It can be set by a library supporting OTLP natively
2. It can be parsed out from the log Body or Attributes (e.g. using [timestamp operator](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/types/timestamp.md) for filelogreceiver)
3. It can be set to receipt timestamp (which is a …

Add ObservedTimestamp to the Log Data Model

---

specification/logs/data-model.md

Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/1875
This is part 1 of the change. Part 2 will add the observed timestamp field. See the issue
for the discussion and the description of the source vs observed timestamps.

Clarify the semantics of the Log Timestamp field

---

CHANGELOG.md
specification/logs/data-model.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/1808
The log_name should not map to Name, they are not the same thing.
log_name description: The resource name of the log to which this log entry belongs.
(See https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#logentry)
Name description: Short event identifier that does not contain varying parts.
log_name is now mapped to a Google-specific attribute. If better mapping is known
I can change to that but I don't see anything else in log data model log_name maps
nicely to.

Change mapping for log_name of Google Cloud Logging

---

CHANGELOG.md
specification/compatibility/opentracing.md

Baggage is NOT directly associated with an OpenTelemetry `Span` directly anymore, but with the **OpenTracing Shim layer**, which greatly simplifies its handling (no more global dictionary or extra field in Spans).
This comes with the recommendation of NOT consuming the OpenTelemetry API and the OpenTracing Shim the codebase, as the `Span`'s associated `Baggage` may be lost during in-process or inter-process propagation.
I have a [prototype](https://github.com/open-telemetry/opentelemetry-java/compare/main...carlosalberto:otshim-spanshim-lock?expand=1) for this in Java.
I'd added thread-safety requirements for `Baggage` consumption, even if it doesn't exist in the original OpenTracing Specification, as those calls are thread-safe anyway in most of (all?) OpenTracing compliant tracers. …

Simplify Baggage handling in the OpenTracing Shim layer.

---

CHANGELOG.md
specification/metrics/semantic_conventions/faas-metrics.md
specification/metrics/semantic_conventions/http-metrics.md
specification/metrics/semantic_conventions/rpc.md

As outlined in #2186 and #1794, the [General Metric Semantic Conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#instrument-units) suggest that [UCUM](http://unitsofmeasure.org/ucum.html) units should be used. 
This PR addresses this by changing the Units in
- `specification/metrics/semantic_conventions/faas-metrics.md`
- `specification/metrics/semantic_conventions/http-metrics.md`
- `specification/metrics/semantic_conventions/rpc-metrics.md`
to these UCUM-compliant units while still retaining the original semantics.
Resolves #1794, resolves #2186

Use UCUM units in Metrics Semantic Conventions

---

CHANGELOG.md
specification/common/attribute-naming.md
specification/metrics/semantic_conventions/README.md
specification/trace/semantic_conventions/README.md

This change adds a prohibition clause that requires that no old
metric or attribute name is used for a new attribute.
This is important to ensure reversibility of schema transformation
(converting from a new version to an old version of schema).
Without this restriction the following is possible:
Schema version 1. Attribute A exists.
Schema version 2. Attribute A is renamed to B. Appropriate schema file is created.
Schema version 3. Attribute A is introduced (a completely different new attribute).
Now attempting to go from Version 3 to version 1 is impossible since it requires
renaming B to A (for the change in version 2), but a different attribute A already exists.

Prohibit usage of retired names in semantic conventions

---

CHANGELOG.md
specification/metrics/semantic_conventions/README.md

This PR clarifies the units that should be used for instruments that measure an integer count. 
The spec mentioned that
> Instruments that measure an integer count of something SHOULD use the default unit 1 (the unity) and annotations with curly braces to give additional meaning. For example {packets}, {errors}, {faults}, etc.
Which, due to the use of "and" in the language, could be interpreted that units should be written as `1{packets}`, `1{errors}` and `1{faults}`. According to [UCUM](https://ucum.org/ucum.html), however, `{packets}` semantically is equivalent to `1{packets}`.
To prevent this interpretation, this PR clarifies that the leading `1` should be omitted.

Clarify integer count instrument units

---

specification/metrics/sdk.md

Fixes #2160
- Remove the interaction between `View` configuration + `Baggage` labels.
This is done to allow room for isntrumentation-library specification and a possible unified Trace/Metric baggage interaction semantic that would be orthogonal to what `View`s provide.

Remove usage of baggage in View from initial SDK specification.

---

CHANGELOG.md
semantic_conventions/resource/device.yaml
specification/resource/semantic_conventions/device.md

Add `device.manufacturer` to semantic conventions for resources

---

.vscode/settings.json
Makefile
semantic_conventions/README.md
specification/trace/semantic_conventions/exceptions.md
specification/trace/semantic_conventions/http.md
specification/trace/semantic_conventions/rpc.md

Unblocks #2233 by allowing empty prefix in semconv generator (https://github.com/open-telemetry/build-tools/pull/67)
Generator changelog: [v0.8.0](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/CHANGELOG.md#v080 )

Upgrade semconv generator to v0.8.0

---

specification/metrics/api.md

Follow up of https://github.com/open-telemetry/opentelemetry-specification/pull/1645
1. Rename the remaining usages of "Observer" to "Observable".
Related issues: 
1. https://github.com/open-telemetry/opentelemetry-js/pull/2687#discussion_r774716669

Rename observer result to observable result

---

specification/compatibility/opentracing.md

Addresses #2219 -- and generalizes the case to all languages having automatic/implicit in-process propagation in OpenTelemetry and none in OpenTracing.
Essentially we recommend that:
* Only explicit propagation is performed by the OT Shim.
* Recommend users to not mix the OT Shim with OTel API usage in the same codebase (similarly to what we did for [baggage support](#2194))
* Let the door open for Shims to optionally offer **experimental** integration with the implicit propagation functionality, as long as the user explicitly enables it.
* This came up during a discussion as a potential feature that may work in "advanced" mode. Not sure whether we should mention it now, or simply add it later on (as an extra feature) later on, if/as needed.
Let me know whether I should add more …

Clarify in-process propagation support mismatch in the OT Shim.

---

specification/sdk-environment-variables.md

Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This is related to https://github.com/open-telemetry/opentelemetry-java/pull/4043 which ports Jaeger remote sampler to gRPC lite implementation.
This change has to benefits: 
1. aligns with OTLP endpoint semantics
2. allows using HTTPS for Jaeger remote sampler
@anuraaga could you please review, you have the most context here.

Align Jaeger remote sampler endpoint with OTLP endpoint

---

specification/sdk-environment-variables.md
specification/trace/sdk.md

Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
This PR defines `JaegerRemoteSampler` it is basically a follow-up after https://github.com/open-telemetry/opentelemetry-specification/pull/1791.
Jaeger remote sampler is already available in:
* Collector: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/jaegerreceiver#remote-sampling
* Java: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/jaeger-remote-sampler
* Go: soon https://github.com/open-telemetry/opentelemetry-go-contrib/pull/936
cc) @jmacd @carlosalberto @willarmiros

Add JaegerRemoteSampler spec

---

spec-compliance-matrix.md

Updates the spec compliance matrix for the capabilities of the Erlang 1.0 release.

erlang 1.0: update spec compliance matrix

---

CHANGELOG.md
specification/metrics/semantic_conventions/README.md
specification/metrics/semantic_conventions/process-metrics.md

Adds semantic conventions for process metrics
Resolves #1817 
Prerequisite for [(collector) #4232](https://github.com/open-telemetry/opentelemetry-collector/issues/4232)
I would appreciate perspectives on `process.cpu.time`, in regards to nuances described [here](https://github.com/open-telemetry/opentelemetry-collector/issues/4232#issuecomment-952130568).

Add semantic conventions for process metrics

---

CHANGELOG.md
specification/metrics/semantic_conventions/runtime-environment-metrics.md

Initial draft at JVM runtime memory semantic conventions. 
Different metric names (`p.r.j.m.usage`, `p.r.j.m.init`, `p.r.j.m.comitted`, `p.r.j.m.max` so that the the aggregation across all dimensions of each metric is semantically meaningful. 
/cc @trask

Add jvm memory runtime metrics

---

specification/common/common.md

Attributes keys must be unique. The key/value pair collections in the specification was always intended to model a map.
There was a recent confusion about this. This change clarifies the spec. This is an editorial change. It does not change any semantics.
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/2245

Clarify that attribute keys are unique in collections

---

specification/resource/semantic_conventions/process.md

Resolves [opentelemetry-go-contrib #350](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/350).
This was discussed briefly in the Golang SIG in December. Consensus at the time was that `go` is clearer than `gc` and sufficiently appropriate. The move away from `gc` is helpful in part because the namespace is used to mean "garbage collector" elsewhere in the semantic conventions.
[opentelemetry-go-contrib #1456](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1456)

Change golang namespace to 'go', rather than 'gc'

---

CHANGELOG.md
specification/logs/data-model.md

Fixes #2074.
Drop the Log `name` field.

Drop log Name field

---

specification/compatibility/opentracing.md

A small PR with a pair of small missed pieces in #2228 
* Specify Baggage from all parent references is used
as initial Baggage for the new Span.
* Span Status must be accordingly set on the new Span if the
initial attributes include the OpenTracing `error` tag.
cc @yurishkuro

Improve the OT Shim Start Span operation section. 

---

specification/compatibility/opentracing.md

There's an extra `#` in an anchor:
```console
$ GET="no" npm run check-links # from the opentelemetry.io repo
========================================================================
docs/reference/specification/compatibility/opentracing/index.html
hash does not exist --- docs/reference/specification/compatibility/opentracing/index.html --> /docs/reference/specification/trace/api/##specifying-links
========================================================================
✘✘✘ failed in 536.869273ms
1 errors in 541 documents
```
/cc @tedsuo @austinlparker

[editorial] compatibility/opentracing.md: fix anchor, `##` -> `#`

---

.github/CODEOWNERS

This change adds the https://github.com/orgs/open-telemetry/teams/instr-wg team as a code owner for semantic conventions. This group represents members of the instrumentation SIG who are willing to review changes to semantic conventions, and to ensure that subject matter experts are included as part of the review process.

Add instr-wg as code owers for semantic conventions.

---

spec-compliance-matrix.md

Links were supported from 1.0 itself, just missed to update the matrix.

Update DotNet spec matrix to include SpanLinks

---

specification/metrics/sdk.md

The current spec for View does not allow specifying temporality (cumulative/delta) on aggregation, and it is only allowed along with MetricReader. This PR is modifying the examples to remove the unsupported capabilities, to avoid confusion.

View aggregation examples modified to remove unsupported things

---

Makefile

For computing `ALL_DOCS`, we don't need to use `grep -v`.
This PR adjusts the `find` arguments to get the same result, as tested by diffing the `ALL_DOCS` output with both versions:
```makefile
ALL_DOCS:
@echo $(ALL_DOCS) | tr ' ' "\n"
```

[editorial] Generate ALL_DOCS using find only, no grep -v

---

CHANGELOG.md
specification/metrics/sdk.md

Discussed in the [2/28/2022 Specification SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit?pli=1#).
* Clarified what does wildcard mean.

Clarify what does wildcard mean in the Metrics SDK View

---

CHANGELOG.md
specification/sdk-environment-variables.md

Fixes #2331
The OTEL_EXPORTER_JAEGER_ENDPOINT env var description is updated:
* clarify that it refers to Thrift over HTTP endpoint, provide a link to Jaeger API spec
* change the default value to point to the correct HTTP port, not the gRPC port
* clarify that the path (`/api/traces`) must be included in the value, to support installations running at remapped URLs
The OTEL_TRACES_EXPORTER env var description updated to reflect state of the world where all but Java SDKs implement http/thrift protocol, not gRPC as was stated in the description.

Correct description of OTEL_EXPORTER_JAEGER_ENDPOINT and OTEL_TRACES_EXPORTER

---

CHANGELOG.md
schemas/1.9.0

February release, including the December and January updates.
Added missing entries in the CHANGELOG, although left most of the clarifications outside of it, unless deemed important enough.

Release v1.9.0

---

CHANGELOG.md
spec-compliance-matrix.md
specification/common/attribute-naming.md
specification/glossary.md
specification/metrics/api.md
specification/metrics/sdk.md
specification/trace/api.md
specification/trace/sdk.md
specification/trace/sdk_exporters/non-otlp.md

This is a slightly different take on https://github.com/open-telemetry/opentelemetry-specification/issues/2203
Instead of renaming instrumentation library to instrumentation scope everywhere
this PR suggests targetted editing of wording of the Trace/Meter obtaining API
to allow not just instrumentation library but other instrumentation scopes to be
used as a parameter.
This change does not force renaming of API parameters and is not a breaking change.
We consider it a clarification of usage to match the intent that we had for the "name"
field.
If this PR is accepted there will be a follow up PR that will suggest to rename
InstrumentationLibrary* messages in OTLP proto to InstrumentationScope* message.
Such a change will not be a breaking change for the OTLP wire format and is acceptable. …

Clarify that Trace/Meter are associated with Instrumentation Scope

---

Makefile

Make all performs roughly the same steps as the already existing github actions. The only
exception is yamllint which I was not able to make work on my Mac after quite some time
and had to skip. If anyone knows how to make it work on a Mac please submit a follow-up PR.
Note that the checks can run in parallel to speed up, e.g. `make -j4`.

Add `make all` target to test changes locally

---

specification/schemas/overview.md

For context, see #2320 at https://github.com/open-telemetry/opentelemetry-specification/pull/2320/files#r807334158.
/cc @arminru
Btw, wouldn't be better to use code markdown (like `Resource*`) rather than having to escape `*` when used as plain text?

[editorial] Add space in schemas/overview

---

CHANGELOG.md
specification/sdk-environment-variables.md

Follow-up of #2333
Preview [here](https://github.com/pellared/opentelemetry-specification/blob/patch-2/specification/sdk-environment-variables.md#jaeger-exporter)
- Add the `OTEL_EXPORTER_JAEGER_PROTOCOL` environment variable to select the protocol used
by the Jaeger exporter.
- More explicit description of the rest of the  `OTEL_EXPORTER_JAEGER_*` environment variables (e.g. when they are applicable - it also represents the current state of SDKs)
Here are the following reasons for this change
1. Enable the possibility of selecting the protocol when the Jaeger exporter is set via env var `OTEL_TRACES_EXPORTER=jaeger` (instead of supporting values like `OTEL_TRACES_EXPORTER=jaeger-udp`). 
2. This resembles [the configuration of the OTLP …

Add OTEL_EXPORTER_JAEGER_PROTOCOL and improve description of other OTEL_EXPORTER_JAEGER_* env vars

---

specification/logs/data-model.md

Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/1215
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/2358
The topics has been discussed at length.
This [PR](https://github.com/open-telemetry/opentelemetry-specification/pull/2276) made possible to record instrumentation scope for traces and metrics. The intent is also to
have instrumentation scope as part of the log data model and where available record logger name
as the instrumentation scope name.

Add InstrumentationScope/Logger Name to log data model

---

specification/metrics/sdk.md

Fixes #2337.
Based on the [2/15/2022 Spec SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit?pli=1#heading=h.ixd3fm5gwjy1) discussion and reading through [RFC2119](https://www.rfc-editor.org/rfc/rfc2119.html).

Clarify that instrument name conflict only happens within a Meter

---

specification/protocol/exporter.md

Based on https://github.com/open-telemetry/opentelemetry-specification/pull/2341#discussion_r806960073
By @tigrannajaryan 
> Why does this say `MAY`? This is not a recommendation, it is a strict list. Should it say: `MUST be one of ...` instead?
As far as I checked, only the OTel Erlang SDK would violate this rule. See: https://github.com/open-telemetry/opentelemetry-erlang/search?q=OTEL_EXPORTER_OTLP_PROTOCOL
@tsloughter WDYT? Is it a blocker from your perspective?

OTEL_EXPORTER_OTLP_PROTOCOL value MUST be one of

---

specification/metrics/sdk.md

I'm unsure if this was intentional, but language introduced in #2221 constrained push metric exporters to being paired with a periodic exporting MetricReader. I'm proposing to relax this constraint.

Clarify that push metric exporters can be paired with any MetricReader

---

specification/metrics/semantic_conventions/http-metrics.md

Super minor...
The description of the `http.server.duration` metric is: `measures the duration of the inbound HTTP request`. This just makes `http.client.duration` the same.

nit: Pluralize "measures"

---

.github/workflows/checks.yaml
CONTRIBUTING.md
Makefile
package.json

I'm having issues running certain spec checks from the website because it's working from a spec submodule. This PR:
- Switches to using `npx` to run npm commands rather than hardcoded paths
- Uses `npm install` to install all necessary NPM-based tools
- Adds a `package.json` file for this purpose -- with `markdownlint-cli` pinned to `v0.31.0` as was done in #2320
IMHO, this is a clean and conventional way to deal with NPM packages. WDYT?
/cc @austinlparker

[linters] Install tools based on versions in package.json

---

CHANGELOG.md
specification/metrics/api.md

Part of #2350
As noted in #2350 (and a comment in #2317 by @anuraaga), the requirements for callbacks to behave a certain way apply to the user, not the implementation or the API designer. Therefore, specify these as documentation requirements.

Clarify asynchronous instrument callback documentation and order-of-execution requirements

---

CHANGELOG.md
spec-compliance-matrix.md
specification/trace/api.md

This change is prompted by @MrAlias's request in https://github.com/open-telemetry/opentelemetry-specification/pull/2278#discussion_r807426172.
The information that attributes should preferably be added at span creation rather than later by calling `SetAttribute` is relevant to users of the API and should be conveyed to them.

Add documentation requirement for adding attributes at span creation

---

CHANGELOG.md
semantic_conventions/trace/rpc.yaml
specification/metrics/semantic_conventions/rpc.md
specification/trace/semantic_conventions/rpc.md

Adds a table for well-known `rpc.system` values, similar to what is done already for `db.system`.
This will make it easier to propose new `rpc.system` values, and it will also enable auto-generation of `rpc.system` constants similar to what is done already for `db.system` in some languages.

Add table for well-known rpc.system values

---

CHANGELOG.md
specification/metrics/sdk.md

Fixes #2118, which is considered as a blocking issue for metrics SDK spec stable release.
We've discussed this during the [3/11/2022 metrics issue triage meeting](https://docs.google.com/document/d/1BHK8OgvInms5hDt8yG97kt_l1zgBKdnl94tOA-d4udc/edit?pli=1#).
The priority is to ship the stable version of the Metrics SDK spec, however the Exemplar part still has many open questions and there are not sufficient prototype from language SIGs. Here are some decisions we've made in order to move the needles:
* Instead of being blocked by the Exemplar spec, we will focus on shipping the SDK spec as Mixed, by moving most parts to Stable but leave Exemplar as "Feature-freeze" (PR #2304).
* Weaken the wording in the Exemplar spec, so it won't cause conflict or introduce breaking change to the spec. …

Remove the "MUST" wording which requires exemplar to be on-by-default

---

specification/protocol/otlp.md

Removes duplicated "the" in the `otlp.md` document.

Duplicate word removal

---

specification/compatibility/opentracing.md

- Resolves https://github.com/open-telemetry/opentelemetry.io/issues/1132
- This PR removes the "Language version support" table, which is **non-normative**, and refers to the same table that is published as part of the website's [Migrating from OpenTracing] guide.
[Migrating from OpenTracing]: https://opentelemetry.io/docs/migration/opentracing/
/cc @austinlparker @tedsuo @yurishkuro @carlosalberto

[editorial] OT: remove non-normative table, link to OT migration page

---

spec-compliance-matrix.md

Thrift support for PHP has been landed over several PRs working on https://github.com/open-telemetry/opentelemetry-php/issues/296, so this updates the matrix to reflect that

Update Jaeger support for PHP column

---

CHANGELOG.md
semantic_conventions/trace/rpc.yaml
specification/metrics/semantic_conventions/rpc.md
specification/trace/semantic_conventions/rpc.md

Adds `rpc.system` value for Apache Dubbo.
We have Java instrumentation for Apache Dubbo, and would like to "upstream" an `rpc.system` value for it.
Btw, suggesting a value of `apache_dubbo` over just `dubbo`, because as @tydhot mentioned in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5432:
> At present, many users' old systems in China are using Alibaba Dubbo. RPC types here need to be distinguished, otherwise there will be some confusion in observation.

Add rpc.system value for Apache Dubbo

---

spec-compliance-matrix.md

Remove the spec status since the compliance matrix doc is not a spec.
Related to https://github.com/open-telemetry/opentelemetry-specification/pull/2473#discussion_r844411696

Remove spec status=Experimental from compliance matrix

---

spec-compliance-matrix.md

We will start tracking logging feature implementations.
Once this PR is merged we will need existing Java, Python and .Net
implementations to populate the matrix.

Add Logging SDK features to spec compliance matrix

---

CHANGELOG.md
specification/telemetry-stability.md
specification/versioning-and-stability.md

This PR defines the rules for SDKs in all languages with regards to marking
instrumentations as "Stable" and "Unstable" and how such instrumentations
are allowed to evolve over time.
Summary of changes:
- Explain that schemas define what changes are allowed.
- Clarify that additive changes are an exception and are always allowed.
- Prohibit instrumentation changes until April 1, 2023 to allow recipients
(backends/vendors) to start understanding Schema URLs/Schema Files.
This gives one year advance notice, which I think should be enough for
all parties to prepare.

Define semantic conventions and instrumentation stability

---

.markdown_link_check_config.json
specification/compatibility/opentracing.md
specification/trace/sdk_exporters/jaeger.md

We've also noticed https://docs.github.com returning 403s to the link checker bot lately in the Java repos.
This PR also reduces the scope of the `ignorePatterns`, which caught two broken links.
`retryOn429` helps with github throttling.

Fix sporadic markdown link check failures

---

spec-compliance-matrix.md

Add entries for java log compliance matrix. 
Also fixes the compliance matrix, moving `Shutdown`, and `ForceFlush` methods to `LogEmitterProvider` instead of `LogEmitter`. 
Request in issue [#4349](https://github.com/open-telemetry/opentelemetry-java/issues/4349)

Update java log compliance matrix

---

CHANGELOG.md
specification/metrics/semantic_conventions/README.md
specification/metrics/semantic_conventions/database-metrics.md

Fixes #2263
Adds database connection pool metrics semantic conventions.
This PR is based on the DB connection pool metrics implemented in the Splunk Java instrumentation distro:
*  https://github.com/signalfx/splunk-otel-java/blob/main/docs/metrics.md#connection-pool-metrics
* https://github.com/signalfx/splunk-otel-java/blob/main/bootstrap/src/main/java/com/splunk/opentelemetry/javaagent/bootstrap/metrics/DataSourceSemanticConventions.java

Database connection pool metrics semantic conventions

---

spec-compliance-matrix.md

Add OTLP Log Exporter with HTTP
https://github.com/open-telemetry/opentelemetry-dotnet/pull/3225

Update dotnet compliance to add OTLP Log export over http

---

semantic_conventions/resource/os.yaml
specification/resource/semantic_conventions/os.md

Both Solaris and SunOS are unfamiliar for me, but some runtimes([Node.js](https://nodejs.org/api/os.html#osplatform)) might have a value `sunos` or similar for Solaris platform which might confuse implementors whether this falls under a well-known value or not. I suggest adding "SunOS" next to "Oracle Solaris" to make that clear.
Trivial change - didn't update the changelog.

Map SunOS to `solaris` for `os.type` resource attribute

---

specification/logs/data-model.md

Fixes #2503 
Updates GCP attributes in the logs data model to use an abbreviated `gcp.` rather than the full `com.google.`. This format is allowed in the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#cloud-provider-specific-attributes) and provides consistency with other cloud provider usages throughout the specification.

Update com.google.* to gcp.* in logs data model

---

specification/versioning-and-stability.md

I think a change in support for a language/runtime version should not necessarily force a major version bump.
Examples where I agree that making a version bump would be an overkill:
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/3147
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/2064
However, bumping a minor version in such cases makes sense.
PS. _Maybe I wrongly understand what "a drop in support" means._
FYI @open-telemetry/dotnet-maintainers

Loosen requirement for a major version bump

---

specification/trace/semantic_conventions/span-general.md

Update the span-general.md#source-code-attributes table for obtaining
thread ids and names across languages to explain how to obtain a
thread's id for Ruby.

Specify how to obtain a Ruby thread's id

---

specification/metrics/semantic_conventions/instrumentation/kafka.md

As a hot-followup to #2485, I've just added `messaging.` as prefix, as **existing** trace semantic conventions use such prefix for Kafka.
Inspired by feedback in #2525

Add prefix to Kafka metrics.

---

CONTRIBUTING.md

The contributing guide says all significant changes should go through OTEP
process. It also describes an issue workflow which says that an issue is
created first, the issue is triaged and accepted and then a PR is created,
however the "Proposing a change" section does not explicitly describe this
as a possibility.
I added a paragraph to make it clear that there are 3 possible options:
with an OTEP, with an issue and trivial changes that are just PRs.
Unless we make this change it appears that everything that is not a trivial
change must go through OTEP, which is not our current process and is not
what we want.

Clarify that issues must be created before PRs

---

CHANGELOG.md
semantic_conventions/README.md
specification/common/README.md
specification/common/attribute-requirement-level.md

Extracted general attribute requirement level from  https://github.com/open-telemetry/opentelemetry-specification/pull/2469
Adds terminology to be used by semantic convention to declare attribute presence requirements.
We currently have 4 vaguely defined levels across semantic conventions:
- `always` - all instrumentations MUST provide
- `conditional` which we use to specify when an attribute should be provided (but we use it inconsistently on optional and required attributes)
e.g. [rpc.service](
https://github.com/open-telemetry/opentelemetry-specification/blob/031630c818c60666b27764a5b7a0e4ed435f55c4/semantic_conventions/trace/rpc.yaml#L27-20) is recommended (but not required?)     
```yml
required:
conditional: "No, but recommended"
```
or …

Define attribute requirement levels

---

spec-compliance-matrix.md

Inconsistencies in the spec compliance matrix related to the `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` environment variable
According to [this PR](https://github.com/open-telemetry/opentelemetry-java/pull/4288) that was merged and released as part of the Java SDK Version v1.14.0, `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` is now a supported environment variable and the spec compliance matrix should reflect this.
None
* https://github.com/open-telemetry/opentelemetry-java/pull/4288

Update spec-compliance-matrix 

---

CHANGELOG.md
specification/protocol/otlp.md

The proto is already declared Stable: https://github.com/open-telemetry/opentelemetry-proto/pull/376

Mark OTLP Logs Stable

---

specification/metrics/datamodel.md

Update for the corner cases of delta counters when being converted to cumulative sum in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9919
- Update the expected behaviors of the new data point.
- Add the options to correct/report for the single-write principle violation issue in the  delta-to-cumulative guide.
Related issues:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4153

Update Prometheus Sums for handling delta counter case

---

specification/common/mapping-to-non-otlp.md
specification/trace/sdk.md
specification/trace/sdk_exporters/jaeger.md
specification/trace/sdk_exporters/zipkin.md

Many of the rules specified in non-otlp.md apply to all signals,
not just to traces.
The common directory is a better place for this file. Also renamed
the file to mapping-to-non-otlp.md to better reflect the content.
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2578.

Move non-otlp.md to common directory

---

specification/metrics/sdk.md

This is an attempt to clarify an unparsable or confusing sentence fragment.
The sentence fragment "If none the optional criteria is provided" is either not grammatically correct (it uses the pronoun none to qualify a noun), or it is referring to an unspecified `none` optional criteria. Given the unspecified nature of a `none` criteria, I've assumed the original intent is to instead state that when no optional criteria is provided it should be treated as an error.
Additionally, the "optional" qualifier seems to be an error. The instrument name is non-optional and if it is provided it would seem that the view would be valid, and no error should be returned. Therefore, I think the original intent here was to say that if no criteria (not just optional) is provided that should be an error. …

Clarify grammar for no criteria views being an error

---

CHANGELOG.md
semantic_conventions/trace/general.yaml
specification/trace/semantic_conventions/span-general.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2548
This PR proposed the two additional attributes `net.app.protocol.name` and `net.app.protocol.version`. These allow capturing the name and version of the application layer protocol used (in addition to the name of the transport protocol captured in net.transport). The naming is consistent with ECS, where [network.protocol](https://www.elastic.co/guide/en/ecs/current/ecs-network.html#field-network-protocol) is used.
Those general attributes can be used to capture information about application layer protocols for which no dedicated semantic conventions exist (e. g. AMQT, or MQTT).
@Oberon00 proposed using a new [`net.app` namespace for this](https://github.com/open-telemetry/opentelemetry-specification/issues/2548 …

Add semantic convention attributes for capturing the application layer protocol

---

CHANGELOG.md
semantic_conventions/trace/instrumentation/graphql.yml
specification/trace/semantic_conventions/README.md
specification/trace/semantic_conventions/instrumentation/graphql.md

Add semantic conventions for GraphQL span name and attributes.
Related issues #1670

Add semantic conventions for GraphQL

---

spec-compliance-matrix.md

OTEL-PHP at some point switched to using InstrumentationScope instead of InstrumentationLibrary everywhere, which incidentally satisfied the ["Fetch InstrumentationScope from ReadableSpan"](https://github.com/open-telemetry/opentelemetry-specification/blob/9abbdd39d0b35f635f833f072013431da419894e/specification/common/mapping-to-non-otlp.md#instrumentationscope) part of the spec (otel-php is still alpha so it seemed ok to not deprecate the instrumentation library and just remove it's use entirely)
https://github.com/open-telemetry/opentelemetry-php/issues/705
Don't think it was an OTEP but https://github.com/open-telemetry/opentelemetry-specification/pull/2276 is where the push for the change originally came from …

Check Fetch InstrumentationScope from ReadableSpan Box for PHP

---

specification/logs/README.md
specification/logs/logging-library-sdk.md

- Contributes to #2558
- Renames spec `logs/overview.md` to `logs/README.md` and adjusts links
/cc @tigrannajaryan @reyang @austinlparker

[editorial] Ensure logs section has a README

---

specification/metrics/README.md
specification/metrics/api.md
specification/metrics/data-model.md
specification/metrics/sdk.md
specification/metrics/sdk_exporters/README.md
specification/metrics/sdk_exporters/in-memory.md
specification/metrics/sdk_exporters/otlp.md
specification/metrics/sdk_exporters/prometheus.md
specification/metrics/sdk_exporters/stdout.md
specification/metrics/semantic_conventions/README.md
specification/metrics/semantic_conventions/database-metrics.md
specification/metrics/semantic_conventions/faas-metrics.md
specification/metrics/semantic_conventions/http-metrics.md
specification/metrics/semantic_conventions/instrumentation/README.md
specification/metrics/semantic_conventions/instrumentation/kafka.md
specification/metrics/semantic_conventions/openmetrics-guidelines.md
specification/metrics/semantic_conventions/process-metrics.md
specification/metrics/semantic_conventions/rpc.md
specification/metrics/semantic_conventions/runtime-environment-metrics.md
specification/metrics/semantic_conventions/system-metrics.md

- Contributes to #2558
- Some page titles have been fixed. I'll add inline comments to highlight those changes.
- Adds `linkTitle` front-matter entries (used by Hugo when generated spec pages on the OTel website). A `linkTitle` is a shortened (since the parent-section context is known) version of the full page title
/cc @tigrannajaryan @reyang @austinlparker

[editorial] Ensure metrics subsections have a README

---

CHANGELOG.md
specification/metrics/sdk.md
specification/metrics/sdk_exporters/otlp.md

Resolves #2471.
opentelemetry-java has an exponential histogram implementation, but its currently quite obscure / difficult to use because the exponential histograms aren't yet stable in the spec. As discussed in #2471 and #2429, we removed the "best available histogram" aggregation anticipating later adding an option like this to make it easy for users to opt in to exponential histograms. I'd like to add the configuration option now so that opentelemetry-java users can more easily use exponential histograms, and provide any feedback needed to stabilization of the specification.

Config option enabling exponential histogram as default histogram aggregation

---

specification/metrics/sdk_exporters/otlp.md

Noticed a typo in the #2619. Hoping to quickly fix it before publishing.

Fix typo in default histogram aggregation

---

CONTRIBUTING.md

We discussed this in the spec SIG meeting. We decided that we want
to make the first response to the new issues clearer. To enable that
I added 3 labels to the spec repo to use for the first response.

Clarify that issue triaging requires labeling

---

CHANGELOG.md
semantic_conventions/trace/faas.yaml
specification/trace/semantic_conventions/faas.md

Fixes #2599
`faas.document.time` and `faas.time` levels are changed from `requirement` to `recommended` as  span start time can be used instead when high precision is not so important.

FaaS conventions: make faas.document.time and faas.time attributes recommended

---

specification/context/api-propagators.md

Unify Inject spell
In section https://opentelemetry.io/docs/reference/specification/context/api-propagators/#textmap-inject is `Inject`
In section https://opentelemetry.io/docs/reference/specification/context/api-propagators/#fields is `inject`

Unify Inject spell

---

spec-compliance-matrix.md

- We now specify adding attributes up-front as preferred in our documentation: https://github.com/open-telemetry/opentelemetry-ruby/pull/1291
- We implement all of the attribute limits described in the spec. The
remainder were implemented in: https://github.com/open-telemetry/opentelemetry-ruby/pull/1292
- We have supported the TextMapPropagator for awhile (v0.17, released 2021-04-22)
- We have supported `OTEL_SERVICE_NAME` for awhile (v1.0.0rc2, released 2021-06-23)
- We support all `OTEL_EXPORTER_{JAEGER,ZIPKIN}` defined in the spec since 2021.
- We definitely suppport the Exporter interface (unclear how we could have hit 1.0 without it).

Misc. spec-compliance-matrix updates for Ruby

---

CHANGELOG.md
specification/trace/api.md

Fixes #2624 
Tries to clarify the sentence to make it clear that setting a span should not mutate the current context.

Make clear that context is not mutable when setting a span

---

specification/README.md
specification/common/README.md
specification/context/README.md
specification/logs/README.md
specification/metrics/README.md
specification/metrics/api.md
specification/metrics/data-model.md
specification/metrics/sdk.md
specification/metrics/sdk_exporters/README.md
specification/metrics/sdk_exporters/in-memory.md
specification/metrics/sdk_exporters/otlp.md
specification/metrics/sdk_exporters/prometheus.md
specification/metrics/sdk_exporters/stdout.md
specification/metrics/semantic_conventions/README.md
specification/metrics/semantic_conventions/database-metrics.md
specification/metrics/semantic_conventions/faas-metrics.md
specification/metrics/semantic_conventions/http-metrics.md
specification/metrics/semantic_conventions/instrumentation/kafka.md
specification/metrics/semantic_conventions/openmetrics-guidelines.md
specification/metrics/semantic_conventions/process-metrics.md
specification/metrics/semantic_conventions/rpc.md
specification/metrics/semantic_conventions/runtime-environment-metrics.md
specification/metrics/semantic_conventions/system-metrics.md
specification/overview.md

- Some Markdown files begin with Hugo front matter in HTML comments, which is used to generate the website version of the page. This PR adds a note to inform contributors about the purpose of these HTML comments.
- Followup to https://github.com/open-telemetry/opentelemetry-specification/pull/2635#discussion_r910155744
/cc @arminru

[editorial] Add note to Hugo front matter

---

spec-compliance-matrix.md

Updates the Compliance Matrix to state that `OTEL_SERVICE_NAME` is read by the Node SDK, which it currently does not.
See: https://github.com/open-telemetry/opentelemetry-js/pull/2227
Markdown

Update Node SERVICE_NAME env var

---

specification/metrics/data-model.md

Gauges shouldn't have a `_total` attached to them according to OpenMetrics.

Only monotonic sum are counters (with _total)

---

specification/metrics/sdk.md

Fixing a typo in the metrics SDK headings.

Fix metrics SDK table of contents

---

CHANGELOG.md
specification/metrics/semantic_conventions/runtime-environment-metrics.md

Add JVM buffer pool semantic conventions

---

specification/metrics/data-model.md

OpenMetrics has the `_created` metric which is very similar to `StartTimeUnixNano`, convert one into the other.

[OM/OTLP] Use _created for StartTimeUnixNano and vice-versa

---

spec-compliance-matrix.md

This is related to [an issue in the java sdk](https://github.com/open-telemetry/opentelemetry-java/issues/4577) concerning removal of Java's Thrift+HTTP support for Jaeger.
The current Java Thrift+HTTP Jaeger exporter is [built on top of](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/jaeger-thrift/build.gradle.kts#L18) the [jaeger-client java library](https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-thrift), which has recently been [deprecated](https://github.com/jaegertracing/jaeger-client-java#-this-library-is-deprecated). 
The existing exporter really only depends on the Jaeger client library to get the autogenerated Thrift classes. One could make the case that the java exporter could source the IDL itself directly from `jaegertracing` …

Drop spec matrix support of Java Thrift HTTP

---

CHANGELOG.md
spec-compliance-matrix.md
specification/sdk-environment-variables.md

Mark `OTEL_METRIC_EXPORT_INTERVAL`, `OTEL_METRIC_EXPORT_TIMEOUT` environment variables as stable.
I think this change is representing the current state as all of these env vars are already implemented in OTel PHP, OTel Python, and partially by OTel Java.
See:
- [`OTEL_METRIC_EXPORT_INTERVAL` usage](https://github.com/search?p=1&q=org%3Aopen-telemetry+OTEL_METRIC_EXPORT_INTERVAL&type=Code)
- [`OTEL_METRIC_EXPORT_TIMEOUT` usage](https://github.com/search?p=1&q=org%3Aopen-telemetry+OTEL_METRIC_EXPORT_TIMEOUT&type=Code)
Created because of: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3424

Make periodic exporting MetricReader env vars stable

---

experimental/serialization/json.md
specification/logs/semantic_conventions/media.md
specification/metrics/data-model.md

This fixes a few broken links and ensures that the user stays on the documentation
site when navigating between documents.
The Metrics Data Model document had broken links to old locations of the attributes
specification, which are fixed here. Any other links to specification documents at
their location within the GitHub repository are replaced with relative links.

Make GitHub links relative for links to specification documents

---

CHANGELOG.md
specification/schemas/file_format_v1.1.0.md
specification/schemas/overview.md
specification/versioning-and-stability.md

This is a new transformation type that allows to describe a change
where a metric is converted to several other metrics by eliminating
an attribute.
An example of such change that happened recently is this:
https://github.com/open-telemetry/opentelemetry-specification/pull/2617
This PR contains:
- A new "split" transformation added to the schema file format.
- Schema file format incremented from 1.0.0 to 1.1.0. This is considered
a backward compatible change and thus the minor version number is
incremented.
- Deleted incorrect sentence that claimed that the addition of a new
transformation type is not backward compatible and requires a
major version number change. This is incorrect. Addition of
new transformation types is backward compatible according to our
current definition of backward …

Introduce "split" metric schema transformation

---

specification/metrics/sdk.md

Editorial change.
During the [7/26/2022 Spec SIG](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.d02nbnjvch7y) we noticed that the Exponential Bucket Histogram Aggregation section in the metrics SDK spec is inheriting the Stable status from MeterProvider, which is wrong.
This PR corrected it to "Experimental".

Correct the spec status for Exponential Bucket Histogram

---

semantic_conventions/resource/browser.yaml
semantic_conventions/resource/cloud.yaml
semantic_conventions/resource/cloud_provider/aws/ecs.yaml
semantic_conventions/resource/cloud_provider/aws/eks.yaml
semantic_conventions/resource/cloud_provider/aws/logs.yaml
semantic_conventions/resource/container.yaml
semantic_conventions/resource/deployment_environment.yaml
semantic_conventions/resource/device.yaml
semantic_conventions/resource/faas.yaml
semantic_conventions/resource/host.yaml
semantic_conventions/resource/k8s.yaml
semantic_conventions/resource/os.yaml
semantic_conventions/resource/process.yaml
semantic_conventions/resource/service.yaml
semantic_conventions/resource/telemetry.yaml
semantic_conventions/resource/webengine.yaml
semantic_conventions/trace/aws/lambda.yaml
semantic_conventions/trace/cloudevents.yaml
semantic_conventions/trace/compatibility.yaml
semantic_conventions/trace/database.yaml
semantic_conventions/trace/faas.yaml
semantic_conventions/trace/general.yaml
semantic_conventions/trace/http.yaml
semantic_conventions/trace/instrumentation/aws-sdk.yml
semantic_conventions/trace/instrumentation/graphql.yml
semantic_conventions/trace/messaging.yaml
semantic_conventions/trace/rpc.yaml

Adds a `type` to every group to resolve the build tools' unsilenceable warning mentioned in https://github.com/open-telemetry/build-tools/pull/109
I added a `type` field to every group that was missing one. Since I didn't know what value to put, I guessed `resource` for the ones in the `resource` subdirectory, and left all the rest to `span` since that's what they were defaulting to.
This silences the warnings and results in zero differences in generated code in my testing.
Before this change (without https://github.com/open-telemetry/build-tools/pull/109#issuecomment-1194682078)
```
Using default SPAN type for semantic convention 'browser' @ line 5
Using default SPAN type for semantic convention 'cloud' @ line 5
Using default SPAN type for semantic convention 'aws.ecs' @ line 5
Using …
```

Add 'type' to all groups

---

CHANGELOG.md
semantic_conventions/resource/process.yaml
specification/resource/semantic_conventions/process.md

Fixes #2689
Add process.parent_pid to specification
This issue is related to allowing receiver/hostmetricsreciever reporting parent process ID (PID).
collector contrib issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12290
collector contrib PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12637
https://github.com/open-telemetry/opentelemetry-specification/issues/2689
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12290

add process.parent_pid attribute

---

internal/tools/schema_check.sh
schemas/1.13.0

This is a follow up to https://github.com/open-telemetry/opentelemetry-specification/pull/2617 now that https://github.com/open-telemetry/opentelemetry-specification/pull/2653 has been merged.
Related issues https://github.com/open-telemetry/opentelemetry-specification/issues/2589

add schema definition for direction change

---

specification/metrics/api.md

There is an extra `}` character in the python method call. Probably it is there from copy-paste of the other method.

Fix copy-paste error

---

schemas/1.12.0
schemas/1.13.0

Fixes #2717.
The changes specified for v1.12.0 in both files here were actually only applied on main so far and will be released in v1.13.0 within the upcoming days. They were introduced in https://github.com/open-telemetry/opentelemetry-specification/pull/2614.

Fix 1.12.0 and 1.13.0 schema file

---

CHANGELOG.md
semantic_conventions/trace/database.yaml
specification/trace/semantic_conventions/database.md

This PR adds OpenSearch in the database section of semantic conventions.
This is necessary for example to provide support for java instrumentation of OpenSearch clients.
Signed-off-by: Cédric Pelvet <cedric.pelvet@gmail.com>

Add OpenSearch in the database group

---

specification/protocol/otlp.md

This pull request simply contributes with this documentation file by adding links to
protocol buffers definitions for each telemetry signal type.
While reading Open Telemetry protocol documentation I found it interesting to be able to read
how the protocol is defined using Protocol Buffers. In my humble opinion, it simplifies
the understanding and enriches the document by adding external code references.

Inserts links to each Protocol Buffer definition by Telemetry signal

---

.vscode/settings.json
Makefile
semantic_conventions/README.md

This unblocks #2702 by making the changes introduced in https://github.com/open-telemetry/build-tools/pull/114 available for use.
It also allows for more semantic conventions for scope attributes to be defined in the future (#2682).
See https://github.com/open-telemetry/build-tools/releases/tag/v0.14.0.

Upgrade semantic convention tool to v0.14.0

---

specification/trace/api.md

Small clarification for the specs about what operations can be called after span finishes. There are other improvements that can be made here such as using right capitalized word for may, but that is a different concern/PR.

Clarify that recording status refers to IsRecording and not Set Status

---

specification/protocol/otlp.md

Make Binary and JSON encodings their own sections.
This makes the spec easier to understand and also
makes adding further clarifications to JSON easier.
There are no functional changes. OTLP protocol behavior
remains exactly the same. This is purely editorial change.

Refactor OTLP/HTTP section

---

specification/metrics/sdk.md
specification/trace/sdk.md

Looks like the SDKs were overlooked when adding scope attributes to the [trace](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer) and [metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter) API specifications.
This syncs up the trace and metrics SDK with their respective APIs.

Add scope attributes to tracer and meter creation

---

CHANGELOG.md
specification/logs/api.md
specification/metrics/api.md
specification/trace/api.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2762
The identity part can be changed later if the community agrees to accept this change, but to be safe for the moment revert this change.

Remove scope attributes form the Scope identity

---

specification/metrics/semantic_conventions/system-metrics.md

I assume `mountpoint` was meant here (see also `system.filesystem.utilization`).

Fix a typo in system-metrics

---

CONTRIBUTING.md

https://nodejs.org/en/about/releases/ now yields a 404 causing our markdown link checker to fail :x:

Fix outdated link in CONTRIBUTING.md

---

specification/overview.md

This PR updates the Resources section of the Overview page to remove outdated verbiage. The spec previously referred to specific exporters with a link to the `opentelemetry-proto` repo's `common.proto`, but the linked code was removed in the following PRs:
- https://github.com/open-telemetry/opentelemetry-proto/pull/80 (`Node` and `ProcessIdentifier`)
- https://github.com/open-telemetry/opentelemetry-proto/pull/62 (`LibraryInfo` and `ServiceInfo`)

Remove outdated Resource verbiage from Overview page

---

CHANGELOG.md
specification/protocol/otlp.md

Resolves https://github.com/open-telemetry/opentelemetry-proto/issues/425
The proposed behavior is necessary for interoperability of senders and receivers when OTLP protocol evolves in an allowed way: by adding new fields to existing messages.

Clarify that unknown fields must be ignored when receiving OTLP/JSON

---

CHANGELOG.md
semantic_conventions/exception.yaml
semantic_conventions/logs/log-exception.yaml
semantic_conventions/trace/exception.yaml
semantic_conventions/trace/trace-exception.yaml
specification/logs/data-model.md
specification/logs/semantic_conventions/exceptions.md
specification/trace/semantic_conventions/exceptions.md

Defines how exceptions should be written when using the logs & events API.
/cc @jack-berg @scheler @MSNev

[Logs] Add semantic conventions for writing exceptions

---

CHANGELOG.md
spec-compliance-matrix.md

Follow up from #2684
Adds the recent OTLP exporter user agent spec to the compliance matrix.
Related issues https://github.com/open-telemetry/opentelemetry-specification/issues/2501
cc @codeboten

Update compliance matrix to reflect the OTLP user agent spec

---

CHANGELOG.md
specification/metrics/semantic_conventions/http-metrics.md

Resolves #2335.
- Removes `http.url` from http client metrics. There is no parameterized corollary to `http.url` and its unlikely that http client libraries would be able to provide a parameterized version.
- Replace `http.target` with `http.route` in http server metrics.
These changes align the semantics of attributes in http traces and metrics.

Fix inconsistent metric usage of http.target

---

specification/metrics/semantic_conventions/instrumentation/kafka.md

Changes to `messaging.kafka.max.lag` from UpDownCounter to Gauge, since doesn't make sense to aggregate maxes.
Also, renames `messaging.kafka.max.lag` to `messaging.kafka.lag_max`, to be consistent with `messaging.kafka.consumer.lag_sum`.
Schema translation for the rename is not included since also changing its type, so seems better(?) to treat it as a breaking change with no schema translation support.

Change to messaging.kafka.max.lag from UpDownCounter to Gauge (and rename it)

---

CHANGELOG.md
specification/metrics/data-model.md

Fixes: #2493
Related: https://github.com/open-telemetry/opentelemetry-specification/issues/1906
This is a second attempt at https://github.com/open-telemetry/opentelemetry-specification/pull/2422.
~~No longer depends on https://github.com/open-telemetry/opentelemetry-specification/pull/2702~~
OpenTelemetry encourages the use of semantic conventions to make metric naming similar across instrumentation.  For example, if I have two http client libraries in my application, they would each produce a metric named `http.client.duration`, but with different meters (e.g. [otelmux](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/0dd27453a1ce8e433cb632e175a27f28ee83998d/instrumentation/github.com/gorilla/mux/otelmux) vs [otelhttp](https://github.com/open-telemetry/opentelemetry-go-con …

Add Instrumentation Scope and Version as labels in Prometheus

---

CHANGELOG.md
specification/protocol/otlp.md

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/2795
This is a breaking change for OTLP/JSON and is allowed because OTLP/JSON is not yet Stable.

Clarify that lowerCamelCase field names MUST be used for OTLP/JSON

---

specification/trace/tracestate-handling.md

Fixes typo in tracestate example.

Fix typo in tracestate value ordering example

---

specification/metrics/data-model.md

- Adds an alias, which creates a redirect rule for the spec published on the website.
- Specifically, this addresses https://github.com/open-telemetry/opentelemetry-specification/pull/2586#issuecomment-1154100618
- Best viewed by ignoring whitespace changes :)
/cc @tigrannajaryan @reyang

[editorial] Adds alias for redirect rule due to name change - metrics/data-model

---

CONTRIBUTING.md
internal/tools/schema_check.sh

This downloads the schema files from https://opentelemetry.io/schemas/ and
verifies their content.
Next time we make a release this will force us to make sure 
https://github.com/open-telemetry/opentelemetry.io repo is updated
before we make the release.
This helps prevent issues like https://github.com/open-telemetry/opentelemetry.io/issues/1846

Verify that schema files are correctly published

---

specification/trace/semantic_conventions/http.md

Fix typo in http semantic conventions

---

CHANGELOG.md
specification/metrics/data-model.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2869
Follow-up to https://github.com/open-telemetry/opentelemetry-specification/pull/2703.  That PR prevents collisions between data points, but not collisions between the descriptions of the metrics.
From https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#metricfamily:
> A MetricFamily MUST have a name, HELP, TYPE, and UNIT metadata.
> MetricFamily names are a string and MUST be unique within a MetricSet.
Basically, for a given metric name, we MUST have exactly one HELP, TYPE, and UNIT comment.
This is a bit light on details, but I can add more if people think that would be helpful.
Basically, this is saying that exporters need to deduplicate Prometheus "descriptions" when …

Prevent duplicate Prometheus description comments

---

specification/glossary.md

I have seen several time a confusion around the nature of the scope and whether scope attributes can change at runtime.
The purpose of this PR is to make sure we all agree the scope is a build time concept, or if we disagree then explicitly specify what else the scope can denote and how its attribute can change at runtime.

Clarify that Scope is defined at build time

---

CHANGELOG.md
semantic_conventions/trace/messaging.yaml
specification/trace/semantic_conventions/messaging.md

Add more semantic convention attributes of Apache RocketMQ

---

CHANGELOG.md
semantic_conventions/resource/cloud.yaml
specification/resource/semantic_conventions/cloud.md

[semantic conventions] add ibm cloud as a cloud provider

---

CHANGELOG.md
specification/metrics/sdk.md

Supersedes #2838 and #2722.
Issue: https://github.com/open-telemetry/opentelemetry-specification/issues/1175
This is needed to support an OpenCensus metric bridge, which is [will be proposed separately](https://github.com/open-telemetry/opentelemetry-specification/pull/2732). It could also be used to support other bridges as well, such as a Prometheus bridge.
Define the MetricProducer interface, with one method: Produce().  MetricProducers SHOULD have a single InstrumentationScope, and can be configured with a Resource.
Add a RegisterProducer(metricProducer) function to MetricReader.
MetricProducers SHOULD allow configuration of temporality, but this isn't enforced via the metric reader.  This is because the reader's temporality is configured as a function of OpenTelemetry instrument.
* …

Define MetricProducer as a third-party provider of metric data to MetricReaders

---

specification/compatibility/opencensus.md

Second attempt at https://github.com/open-telemetry/opentelemetry-specification/pull/2732
Part of https://github.com/open-telemetry/opentelemetry-specification/issues/1175
Related to https://github.com/open-telemetry/opentelemetry-specification/pull/2730
Specify that OpenCensus metric bridges implement the MetricProducer interface, and describe non-trivial transformations involved.
This follows the path taken by the [java opencensus-shim](https://github.com/open-telemetry/opentelemetry-java/blob/main/opencensus-shim/src/main/java/io/opentelemetry/opencensusshim/metrics/OpenCensusMetricProducer.java#L27).

Add OpenCensus metric bridge specification

---

experimental/serialization/json.md

I noticed a linter/link check failing on a PR due to jsonlines.org domain not resolving.

Remove markdown link to jsonlines.org

---

CHANGELOG.md
semantic_conventions/trace/messaging.yaml
specification/trace/semantic_conventions/messaging.md

Fixes #2971
Introduces a new `messaging.kafka.message.offset` attribute that is supposed to store the offset of a Kafka message. I used the naming pattern introduced in #2957, assuming it's probably going to land in the same release as this change.

Add `messaging.kafka.message.offset` attribute

---

specification/trace/api.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3006
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.

Update Tracing API: IsRecording wording

---

specification/trace/sdk.md

We use comparison operator. Especially on this paragraph it has confused me. Made me think that the sampling decision is based on what IsRecording returns but in reality we are trying to define what IsRecording returns.
Fixes #
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compl …

Tracing SDK: Do not use comparison operator

---

specification/metrics/semantic_conventions/hardware-metrics.md

- Adds a `linkTitle` (short title) in the same manner that other pages have in that section. This will be the result in the side-nav: 
> <img width="137" alt="image" src="https://user-images.githubusercontent.com/4140793/208150704-bb05eb3b-cde0-46e0-afeb-bf072edd64a9.png">
- Followup to:
- https://github.com/open-telemetry/opentelemetry.io/issues/2079
- https://github.com/open-telemetry/opentelemetry.io/pull/2109
- #2518
/cc @bertysentry

[editorial] Metrics hardware sem. conv. front matter

---

specification/schemas/README.md
specification/schemas/file_format_v1.0.0.md
specification/schemas/file_format_v1.1.0.md
specification/telemetry-stability.md
specification/versioning-and-stability.md

- Contributes to #2558
- Renames spec `schemas/overview.md` to `schemas/README.md`, and:
- Adjusts links correspondingly
- Adds a redirect rule (via `aliases`)
- Wraps the manually added TOC with `` directive so that it gets autogenerated
- Reformats the link to OTel site (otherwise it gets stripped out completely when the page is published to the website)
- Adds version number (and the word "Format") to the titles of the file format pages. This is to ensure that the titles are distinct, otherwise the new `schemas/README.md` subpage list would show two subpages with the same title.
- Preview: https://github.com/chalin/opentelemetry-specification/tree/chalin-gp-spec-schema-index-2022-12-16/specification/schemas
/cc @tigrannajaryan @reyang @carlosalberto @cartermp @svrnm

[editorial] Ensure schemas section has a README, and other changes

---

CHANGELOG.md
semantic_conventions/exception.yaml
semantic_conventions/logs/events.yaml
semantic_conventions/logs/log-exception.yaml
semantic_conventions/trace/general.yaml
specification/trace/semantic_conventions/span-general.md

In some languages such as Javascript or Haskell, it's common to have multiple lambdas/anonymous functions defined on the same line. 
`function myEval(code){return eval(code)}function handleJSONP(a){return a}(function(){function a(b){var c=myEval(b)}})();`
Without a column number, it's impossible to accurately pinpoint which of the anonymous functions in the same file and the same line we are talking about. A column attribute is necessary to fully specify which unit of code we are interested in.

Suggest column # as an extra source code attribute

---

specification/metrics/api.md

Move the related introduction sentence of the Synchronous and Asynchronous instruments section into that section.
The Synchronous and Asynchronous instruments section is composed as an introduction to the Asynchronous and Synchronous Instrument API sections. Make these two other sections sub-sections to communicate this structurally.

Restructure the sync/async API as sub-sections

---

specification/metrics/api.md

A `Measurement` is defined as the encapsulation of a value and attributes. The Histogram record API currently is defined to accept a `Measurement` and attributes. This means, if implemented as currently defined, a user would pass a value/attributes pair and then additional attributes. It is not likely what was the original intent of the specified parameters.

Fix Histogram parameter: use value term instead of `Measurement`

---

specification/context/api-propagators.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/1175
Addresses https://github.com/open-telemetry/opentelemetry-specification/pull/3015#discussion_r1047817750.  We don't currently list OpenCensus propagators anywhere in our specification, even though they have been implemented (e.g. [go's BinaryFormat propagator](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/propagators/opencensus#opencensus-binary-propagation-format)).
This does not require implementing these propagators, but adds them to the list of propagators allowed in core repositories.  My primary motivation is to document them somewhere in the specification for reference.
cc @jsuereth @bogdandrutu @jack-berg @reyang

Add OpenCensus propagators as allowed in OTel repositories

---

schemas/1.17.0

Upon preparing the Schema for opentelemetry.io, realized the incorrect PR is referenced from the 1.17.0 Schema changes.
See #2957

Update the 1.17 Schema to reference the proper changes PR

---

specification/trace/semantic_conventions/instrumentation/aws-lambda.md

Remove an additional square bracket from a link.

Remove rogue bracket

---

CHANGELOG.md
specification/compatibility/opencensus.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/1175
Supersedes https://github.com/open-telemetry/opentelemetry-specification/pull/2730.
Follow-up to https://github.com/open-telemetry/opentelemetry-specification/pull/2979
We have defined what OpenCensus metric and trace bridges, but don't have anywhere with recommendations on how to use them to migrate from OpenCensus to OpenTelemetry.  This adds a description of how users and library authors can migrate to OpenTelemetry.
* **OpenCensus TextFormat Propagator**: Not needed, as it is equivalent to the OpenTelemetry W3c TraceContext propagator.
* **B3 Context propagator for OpenCensus**: Not needed, as b3 compatibility is already specified elsewhere, and is not OC-specific.
* **Semantic convention mapping for …

Add OpenCensus migration plan

---

specification/compatibility/prometheus_and_openmetrics.md

Fix the wrong metric type in the OTel to Prometheus compatibility section.

[chore] Fix wrong metric type in OTel to Prom compatibility section.

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

I realized when opening https://github.com/open-telemetry/opentelemetry-swift/issues/355 that the current prometheus spec for histograms is incorrect (though almost all implementations of prometheus exporters is correct).
From the [prometheus spec](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#histograms-and-summaries):
> Each bucket count of a histogram named x is given as a separate sample line with the name x_bucket and a label {le="y"} (where y is the upper bound of the bucket).
From the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram-1):
> The MetricPoint's Bucket Values Sample MetricNames MUST have the suffix "_bucket".
This corrects our specification to be in-line …

Prometheus histogram bucket metric ends in _bucket

---

CHANGELOG.md
semantic_conventions/trace/database.yaml
specification/trace/semantic_conventions/database.md

Fixes #3106
Added Microsoft Sql Server Compact and Cloud Spanner to db spec. 
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.

Add cloud spanner and mssql compact to db specifications

---

specification/compatibility/prometheus_and_openmetrics.md

Fixes #
This is a minor change to clarify the intent of `otel_scope_name` and `otel_scope_version` labels in prometheus compatibility. On my first read, I thought `all metric points` referred to "all data points in the `otel_scope_info` metric". This clarifies that it is all data points for all metrics within that scope.

Clarify otel_scope_info labels for prometheus compatibility

---

.vscode/settings.json
CHANGELOG.md
Makefile
semantic_conventions/README.md
specification/trace/semantic_conventions/http.md

Fixes #3117.
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/2666.

Enable semantic convention tooling for metrics

---

CHANGELOG.md
specification/trace/semantic_conventions/http.md

Fixes #2998
Changes http server span names from
* `{http.route}` to `{http.method} {http.route}` (when route is available)
* `HTTP {http.method}` to `{http.method}` (when route is not available)
Changes http client span names from
* `HTTP {http.method}` to `{http.method}`

Changes to http span name

---

CHANGELOG.md
specification/logs/sdk.md
specification/trace/sdk.md

Fixes #3147
Clarifies guidance with regards to logging when items (attributes, span links/events) are dropped or truncated on spans or log records.
I'm not certain what was originally intended to be communicated, so my initial proposal is to state that a message must only be printed once per Span/LogRecord regardless of how many items were dropped or truncated on the Span/LogRecord. However, some may argue this too may lead to excessive logging.
So the real question is what do we want to communicate here?
Another option may be to state something like:
> To prevent excessive logging, an SDK SHOULD take measures to limit how often it notifies the user an attribute was discarded or truncated. The exact measures an SDK takes is not specified.

Clarify guidance regarding excessive logging

---

CHANGELOG.md
semantic_conventions/metrics/http.yaml
specification/metrics/semantic_conventions/http-metrics.md

Fixes #2972 by adding text to say whether each instrument is required or optional (ideally should be added to yaml?)
Fixes #2822
Fixes #2974 by including same definition of `net.host.name` from tracing
Fixes #2976 by making `http.server.request.size` and friends optional
Adds http metrics yaml file based on @jamesmoessis build tool changes in https://github.com/open-telemetry/build-tools/pull/79
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to …

Add http metrics yaml

---

CHANGELOG.md
semantic_conventions/metrics/http.yaml
semantic_conventions/trace/http.yaml
specification/metrics/semantic_conventions/http-metrics.md
specification/trace/semantic_conventions/http.md

Fixes #3156
Makes it clear that `http.route` SHOULD contain the "application root" if there is one.

Http route should contain application root

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

Fixes #
https://github.com/open-telemetry/opentelemetry-specification/issues/3078
Define conversion mapping from OTel Exponential Histograms to Prometheus Native Histograms. See, the implementation https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/17370
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16207
https://github.com/open-telemetry/opentelemetry-proto/issues/440
https://github.com/open-telemetry/oteps/blob/main/text/0149-exponential-histogram.md

Define conversion mapping from OTel Exponential Histograms to Prometheus Native Histograms.

---

specification/logs/data-model.md

Cleanup after: #2614, #2469
Discovered when reviewing: https://github.com/open-telemetry/opentelemetry-specification/pull/3087
Update Apache HTTP Server access log example mapping to match current semantic conventions.

Update Apache HTTP Server access log example mapping

---

specification/trace/semantic_conventions/exceptions.md

(This change will allow the OTel website external link checker to avoid having to report redirects.)

[editorial] Use canonical URL to pkg.go.dev/runtime/debug#Stack

---

semantic_conventions/resource/cloud.yaml
specification/resource/semantic_conventions/README.md
specification/resource/semantic_conventions/cloud.md

- Replaces `https://intl.cloud.tencent.com` by `https://www.tencentcloud.com`, the new canonical URL for Tencent Cloud
- Note that other PRs (like #3230) are currently failing because of the invalid Tencent link:
> FILE: ./specification/resource/semantic_conventions/README.md
>  [✖] https://intl.cloud.tencent.com/

[editorial] Fix Tencent Cloud link

---

specification/metrics/data-model.md

- This is part of an effort to normalize external links, for improved external link checking of the OTel website.
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1052

[editorial] Drop Google highlight "hash" from URL in metrics/data-model

---

.vscode/settings.json
Makefile
internal/tools/schema_check.sh
semantic_conventions/README.md

build-tools 1.16.0 was just released and is necessary to unblock https://github.com/open-telemetry/opentelemetry-specification/pull/3190

Update build-tools to 1.16.0

---

.github/auto_assign_issue.yml
.github/auto_assign_pr.yml

After #3255 I noticed we forgot to add @reyang to the auto-assignment back then.

Add reyang to auto assignment for issues and PRs

---

semantic_conventions/trace/http.yaml
specification/trace/semantic_conventions/http.md

Clarify relationship between `http.target` and `http.route` by using the same pattern in the example usage. Having different patterns for the attribute values distorts the relationship between the two attributes.
A similar pattern is seen in the docs for [`aws-lambda.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-lambda.md#api-gateway-request-proxy-lambda-tracing-passive), where `http.target` is `/pets/10` and `http.route` is `/pets/{petId}`. It's a minor adjustment but should help provide clarity for new users.

Show relationship between http target and route in example usage

---

spec-compliance-matrix.md

.NET SDK supports allowing samplers to modify tracestate starting the latest stable version `1.4.0`.
Here is the PR for reference: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3610
- Update .NET entry for "Allow samplers to modify tracestate"

[Spec-compliance-matrix][.NET] Update entry for "Allow samplers to modify tracestate"

---

package.json

Link check is broken due to https://github.com/tcort/markdown-link-check/issues/246, pinning previous version until it's fixed

Make markdown-link-check work again

---

CHANGELOG.md
specification/logs/README.md

Related to #2911.
The log readme contains useful context and history behind the design of the log signal, but is not normative. Well, it won't contain normative language after #3331 is merged.
Removing the document status to reflect this and match the [metrics readme](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/README.md).

Remove log readme document status

---

CHANGELOG.md
specification/metrics/semantic_conventions/hardware-metrics.md

Fixes #3236
* Update attributes requirement levels in `specification\metrics\semantic_conventions\hardware-metrics.md`
* Minor wording corrections

Issue #3236 Update attribute requirement levels in hardware metrics semconv

---

CHANGELOG.md
specification/glossary.md
specification/logs/README.md
specification/logs/bridge-api.md

Related to #2911.
cc @dyladan who brought up naming in the 3/13 maintainers SIG.

Add log appender / bridge to glossary

---

CHANGELOG.md
specification/trace/semantic_conventions/instrumentation/aws-lambda.md

Follow up to https://github.com/open-telemetry/opentelemetry-specification/pull/3214

AWS Lambda - remove references to messaging.destination.kind and messaging.source.kind

---

CHANGELOG.md
semantic_conventions/trace/database.yaml
specification/trace/semantic_conventions/database.md

Add [Trino](https://trino.io/) to the list of well-known identifiers for `db.system`.

Add Trino to db.system semantic conventions

---

CHANGELOG.md
specification/trace/sdk.md

This removes the "decorate" language from span processors. Technically a breaking change but since consensus seemed to be that something new needed to be designed I figured it best to get it out of the spec first.
Open question if the "for advanced scenarios such as tagging or filtering" part should be left in. I'd say it doesn't apply to custom processors but you technically could use them to do that in OnStart.

Remove underspecified and unused Span decorator from Trace SDK.

---

CHANGELOG.md
semantic_conventions/metrics/http.yaml
specification/metrics/semantic_conventions/http-metrics.md

Fixes #3357
Removes `http.status_code` attribute from the `http.server.active_requests` metric.

BREAKING: Remove http.status_code attribute from the http.server.active_requests metric

---

specification/common/attribute-requirement-level.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2429
- This is part of an effort to normalize links, for improved link checking on the OTel website
/cc @carlosalberto @trask

[editorial] Use path, not external URL, for link into glossary

---

CHANGELOG.md
specification/metrics/semantic_conventions/README.md

Resolves @jack-berg's https://github.com/open-telemetry/opentelemetry-specification/pull/3294#issuecomment-1497982334
Adds clarification that UCUM c/s variant applies to all units other than `1` and those using [annotations](https://ucum.org/ucum.html#para-curly).

Clarification about when to use UCUM c/s variant

---

CHANGELOG.md
specification/metrics/semantic_conventions/README.md

Resolves #2977.
Also related to #3294, and discussed in in this [#3312](https://github.com/open-telemetry/opentelemetry-specification/pull/3312#discussion_r1157584440)
As mentioned [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1489150771) this was voted on by the TC.

Specify seconds unit for measuring durations

---

specification/logs/bridge-api.md

Found this small mistake while reading through the document.

Remove duplicated text from Log4J appender section

---

CHANGELOG.md
specification/README.md

The [specification readme](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/README.md) is missing entries for the log signal. This fixes that.

Add log documents to specification README.md

---

CHANGELOG.md
specification/README.md
specification/configuration/file-configuration.md
specification/configuration/sdk-configuration.md
specification/configuration/sdk-environment-variables.md
specification/metrics/sdk.md
specification/metrics/sdk_exporters/in-memory.md
specification/metrics/sdk_exporters/otlp.md
specification/metrics/sdk_exporters/stdout.md
specification/resource/semantic_conventions/README.md
specification/vendors.md
specification/versioning-and-stability.md

Followup to #3360.
Relocates the `sdk-configuration.md` and `sdk-environment-variables.md` files to the `/specification/configuration` directory.

Move configuration documents to configuration folder

---

specification/metrics/semantic_conventions/README.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3457#issuecomment-1527811966
Adds explicit status to all sub-sections in "Mixed" document

Add explicit status to all sub-sections in "Mixed" document

---

CHANGELOG.md
semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
specification/metrics/semantic_conventions/runtime-environment-metrics.md

Resolves #3414.
Indicate that seconds should be unit for `process.runtime.jvm.gc.duration`.
Also indicate that advice should specify bucket boundaries are `[]`. This effectively downgrades gc duration to a summary by default, capturing min, max, sum, and count. Users can opt in to the distribution using views or metric reader configuration.

JVM gc duration unit and bucket boundaries

---

semantic_conventions/resource/cloud_provider/gcp/cloud_run.yaml
semantic_conventions/resource/faas.yaml
specification/resource/semantic_conventions/README.md
specification/resource/semantic_conventions/cloud_provider/gcp/README.md
specification/resource/semantic_conventions/cloud_provider/gcp/cloud_run.md
specification/resource/semantic_conventions/faas.md

Add a note for Cloud Run Jobs on how to identify `faas.version`.
Related issues 
Downstream PR proposing this semconv change: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/465

Add detail for GCP Cloud Run Job execution

---

CHANGELOG.md

This should unblock the spec 1.21.0 release #3474.
FYI @arminru @carlosalberto @jsuereth

Sanitize semantic convention changelog

---

specification/logs/data-model-appendix.md

Fix outdated host.hostname attribute in log data model

---

specification/metrics/sdk.md

Currently the recommendation does not use the key-word defined by [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119.txt)

Make recommendation to reserve aggregator normative

---

specification/metrics/sdk.md

- Using the term "appurtenant" is not necessary and makes the meaning of the sentence unclear.
- Scoping the use of these APIs to the "context of a single `MetricReader` collection" is a meaningless statement. They should be disregarded in all context outside of a callback.
- Remove the qualifier that the use has to be "accidental". This was likely originally included to explain why a user would do this, but it also complicates things as the implementer may think they need to determine if the use was accidental or not.

Simplify language for async API use outside of callback

---

specification/compatibility/prometheus_and_openmetrics.md

See https://github.com/open-telemetry/opentelemetry-specification/blob/976432b74c565e8a84af3570e9b82cb95e1d844c/specification/metrics/semantic_conventions/README.md?plain=1#L199

use singular in metric unit

---

specification/trace/api.md
specification/trace/sdk.md
specification/trace/sdk_exporters/README.md
specification/trace/sdk_exporters/jaeger.md
specification/trace/sdk_exporters/zipkin.md
specification/trace/tracestate-handling.md
specification/trace/tracestate-probability-sampling.md

- Contributes to #2558 by adding `specification/trace/sdk_exporters/README.md`
- Adds `linkTitle` front-matter entries for selected pages
/cc @svrnm @cartermp

[editorial] Ensure trace subsections have a README

---

specification/protocol/README.md
specification/protocol/design-goals.md
specification/protocol/exporter.md
specification/protocol/file-exporter.md
specification/protocol/otlp.md
specification/protocol/requirements.md

- Adds Hugo `linkTitle` to Protocol pages, to match OTLP pages
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2642
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2793
/cc @svrnm @cartermp

[editorial] Add Hugo front-matter for protocol to match OTLP pages

---

spec-compliance-matrix.md

Was reviewing the compliance matrix and realized these two are missing. Took a quick look at existing implementations and put a mark where needed - although I need confirmation for the OC case, as I'm not an expert there. Maybe @dashpole @open-telemetry/go-approvers can confirm?

Add OT/OC Binary propagators to the compliance matrix.

---

CHANGELOG.md
specification/metrics/sdk.md

Towards https://github.com/open-telemetry/opentelemetry-go/issues/3642#issuecomment-1568336829
- Create a `MeterProvider - Configuration` section.
- Change "managed solely" to "owned". E.g. I do not think it is wrong that one would pass the same reader to a different metrics provider. But the provider has the permission to e.g. shutdown the reader during metrics provider shutdown.
- Remove _"The SDK MUST provide a way to configure all options that are implemented by the SDK."_ as I do not see any value in this sentence. For me (maybe wrongly) it means like "the configuration MUST by applied".

Refine SDK MeterProvider configuration section

---

Makefile

Recently IBM changed docs referenced by our semconv, and hence our CI is broken - but there shouldn't be need to check links for it, as they are outdated (and will be removed eventually?).

Do not check for valid links in semantic conventions.

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

Clarifies that _total does not need to be added as a suffix to counters if it already exists.  There was confusion in https://github.com/open-telemetry/opentelemetry-java/issues/5304#issuecomment-1523356583 if that was correct or not.
cc @open-telemetry/wg-prometheus @jack-berg

Prometheus compatibility: don't add duplicate _total suffixes

---

specification/overview.md

Currently the build is broken as location were massaged in the semantic-conventions repository.

Fix semantic-conventions link to the yaml files.

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

Part of https://github.com/open-telemetry/wg-prometheus/issues/72
We currently require Prometheus -> OpenTelemetry translation to remove type and unit suffixes in metric names.  For example, the Prometheus metric `http_request_duration_seconds_total` would become `http_request_duration` in the resulting OTel metric.  When this change was made, it received a large amount of user pushback, as it broke many existing metric names.
This PR makes trimming suffixes from names disabled by default, and encourages implementations to provide a config knob to enable the suffix trimming.
The original motivation for trimming suffixes by default was so that metrics could be round-tripped between an OTel SDK and the collector through the prometheus endpoint.  For example, the OTel metric …

[Prometheus compatibility] Do not require trimming suffixes by default

---

specification/common/README.md
specification/compatibility/opencensus.md
specification/compatibility/opentracing.md
specification/compatibility/prometheus_and_openmetrics.md
specification/configuration/sdk-environment-variables.md
specification/context/README.md
specification/logs/noop.md
specification/metrics/noop.md

- Followup changes for https://github.com/open-telemetry/opentelemetry.io/issues/2793
- There are only changes to Hugo front matter
- Adds `likeTitle`s for "Compatibility" pages
- Adds aliases for pages that have moved or were renamed
- Related: https://github.com/open-telemetry/opentelemetry.io/issues/3013 -- the `compatibility/openmetrics` spec page is in the list because it was renamed
/cc @svrnm @cartermp

[editorial] Hugo front-matter fixes for aliases and linkTitle

---

.markdown_link_check_config.json
CHANGELOG.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2429
- This is part of an effort to normalize links, for improved link checking on the OTel website.
- This is meant to catch and prevent fixes like with a local check in this repo rather than the OTel-website build:
- #3375
- #3310
/cc @svrnm @cartermp @jsuereth

[CI/editorial] Report link-check error when external URL used for local spec page

---

CHANGELOG.md
specification/metrics/api.md
specification/metrics/sdk.md

Currently, the SDK states that identical instruments need to have their data aggregated together. It is implied that the definition of "identical" is defined by the metric data-model. However, the linked data-model defines identical in a way that does not include the Instrument number type. Therefore, if two instruments are "identical" in all their fields, but one if defined for double-precision floating point values and the other integer values they will need to be aggregated together. This is challenging if not impossible for strongly typed implementations.
Instead, have the SDK explicitly use the definition added to the metric API defining the number type (and all other language-level features) as identifying and therefore included in the definition of identical.
This does mean that …

Clarify identical instrument definition for SDK.

---

CHANGELOG.md

July Release.
PS - removed the "Protocol" and "Telemetry Schemas" sections of the CHANGELOG, as they now reside in their respective repos.

Release 1.23.0

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

Part of https://github.com/open-telemetry/opentelemetry-go/issues/4305
When migrating from OpenCensus to OpenTelemetry, and using Prometheus exporters, it causes a breaking change in the metric name for counters that were not complying with Prometheus naming recommendations. This is because OpenCensus does not add `_total` suffixes for counters. For example, the metric `my.metric.foo` became `my_metric_foo` in OpenCensus. But in OpenTelemetry, it now becomes `my_metric_foo_total`.
Prometheus exporters should allow disabling the addition of `_total` suffixes through configuration.
cc @open-telemetry/wg-prometheus @jmacd @jsuereth

Prom compatibility: allow disabling the addition of _total suffixes on prometheus counters

---

spec-compliance-matrix.md

Document the current state of OpenCensus bridges in the spec compliance matrix.
Go
* metric: https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/metric.go#L40
* trace: https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/bridge.go#L29
Java:
* metric: https://github.com/open-telemetry/opentelemetry-java/tree/main/opencensus-shim#metrics
* trace: https://github.com/open-telemetry/opentelemetry-java/tree/main/opencensus-shim#traces
Python
* trace: https://github.com/open-telemetry/opentelemetry-python/tree/main/shim/opentelemetry-opencensus-shim/src/opentelemetry/shim/opencensus
JS: 
* trace: https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/shim-opencensus

Add opencensus compatibility spec compliance matrix

---

specification/metrics/sdk.md

1. Currently the term "view" is overused within the section. It is used to mean the SDK, views, and aggregators. This replaces the term with an appropriate replacement
2. Clarify the priority order for how a cardinality limit is configured within its own new section
3. Create a section for the overflow attributes

Clarify the cardinality limit section

---

specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3618
Mark the default aggregation cardinality limit experimental, since the rest of the aggregation cardinality limit feature is experimental.

Mark the default aggregation cardinality Experimental in MetricReader

---

specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3601.
This is a small clarification for the MetricProducer specification.
cc @damemi

Clarify that produce may have required or optional parameters

---

specification/metrics/sdk.md

Not all implementations have the concept of classes in their languages. Instead, consistently use the term implementation which is used in the periodic exporting reader section.

Remove Object Oriented language from metric SDK

---

CHANGELOG.md
specification/metrics/sdk.md

- Make it normative that an SDK is recommended to include both types of default reservoirs.
- Make the description of both default reservoirs their own sub-sections.
- Correct the "SimpleExemplarReservoir" section to be titled "SimpleFixedSizeExemplarReservoir".
- Loosen the SimpleFixedSizeExemplarReservoir to allow any uniformly-weighted sampling algorithm instead of just the naive one that is not optimal.
- The current algorithm has an asymptotic running time of `O(n)`. There are other sampling algorithms that produce equivalent results and have more optimal asymptotic running times. Therefore, do not restrict implementations to only implementing the inefficient algorithm.

Revise the exemplar default reservoirs

---

spec-compliance-matrix.md

I noticed that the handling of the partial success message introduced more than a year ago in https://github.com/open-telemetry/opentelemetry-specification/pull/2696 is only implemented in a few SDKs. This adds it to the spec compliance matrix to keep track of adoption.
Related issues:
- https://github.com/open-telemetry/opentelemetry-go/issues/3102
- https://github.com/open-telemetry/opentelemetry-python/issues/2882
- https://github.com/open-telemetry/opentelemetry-js/issues/3183
- https://github.com/open-telemetry/opentelemetry-dotnet/issues/3592
- https://github.com/open-telemetry/opentelemetry-cpp/issues/1577
- https://github.com/open-telemetry/opentelemetry-java/issues/4706
- https://github.com/open-telemetry/opentelemetry-erlang/issues/436
- …

Add OTLP partial success message handling to compliance matrix

---

specification/overview.md

I just would like to report that all links to W3C tracestate specifications are either:
* https://www.w3.org/TR/trace-context/#tracestate-header or,
* https://www.w3.org/TR/trace-context/#tracestate-header-field-values 
But `specification/overview.md` is using:
*  https://w3c.github.io/trace-context/#tracestate-field (not the same document/version).
Do you need me to open an issue first?

Fix inconsistent tracestate reference

---

spec-compliance-matrix.md

This updates reflects the Logs state in the latest update in the [opentelemetry-cpp](https://github.com/open-telemetry/opentelemetry-cpp#project-status) repo.
@open-telemetry/cpp-maintainers @open-telemetry/cpp-approvers

Update spec-compliance-matrix for C++ Logs

---

CHANGELOG.md
specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3611
This change moves the registration of MetricProducers from a RegisterProducer function to a configuration option on the MetricReader.
The only potentially breaking impact of this change is that a user can no longer register new MetricProducers after the MetricReader is created.  For example, it wouldn't be possible to dynamically register new MetricProducers.  I don't know of any use-cases for this.
Since it isn't feasible for JS to implement the spec as currently written, so we need to at least allow passing MetricProducers as config instead of via RegisterProducer.
However, it would be best if we had a consistent implantation across languages, and when I [prototyped using configuration in …

MetricProducers are passed via config to MetricReaders instead of RegisterProducer

---

CHANGELOG.md
specification/metrics/sdk.md
specification/metrics/supplementary-guidelines.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/2711
This is limited to asynchronous instruments in order to minimize the changes required for SDKs.  It could be extended to synchronous instruments in the future with a Delete() function, as requested in https://github.com/open-telemetry/opentelemetry-specification/issues/3062.  Implementing this specification would allow temporarily working around the limitation for synchronous instruments in some cases as described in https://github.com/open-telemetry/opentelemetry-specification/issues/3062#issuecomment-1412306635, and would validate the approach recommended here before making the addition to the API.
This does not impose additional requirements on the SDK's handling of start time.
This updates the metric SDK …

Attribute sets not observed during async callbacks are not exported

---

CHANGELOG.md
specification/logs/data-model-appendix.md

GCP logging exporters should support the IsSampled flag, for example https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/690 adds this support.
Currently, this is supported by the `gcp.trace_sampled` attribute (by way of our [mapping for "All other fields"](https://github.com/open-telemetry/opentelemetry-specification/blob/dc78006c12d9767fd2e35b691706c7572a76fd43/specification/logs/data-model-appendix.md#google-cloud-logging) to a matching `gcp.*` attribute).
Therefore, in the spec this is a breaking change (from `gcp.trace_sampled` to `Flags`), but implementations can continue to support the attribute for backward-compatibility.

logs: Document Flags mapping in Google Cloud logs appendix

---

CHANGELOG.md
specification/metrics/sdk.md

Supersedes https://github.com/open-telemetry/opentelemetry-specification/pull/3600
Part of https://github.com/open-telemetry/opentelemetry-specification/issues/3599.
All outstanding issues with MetricProducer have been resolved:
* https://github.com/open-telemetry/opentelemetry-specification/issues/3615
* https://github.com/open-telemetry/opentelemetry-specification/issues/3611
* https://github.com/open-telemetry/opentelemetry-specification/issues/3601
There are compliant implementations in Go and JS:
* https://github.com/open-telemetry/opentelemetry-go/blob/10d9038059c237fe1805c1439fde04aa39113d45/sdk/metric/reader.go#L121
* https://github.com/open-telemetry/opentelemetry-js/pull/4007
There is a prototype in Java:
* https://github.com/open-telemetry/opentelemetry-java/pull/5678
cc …

Promote MetricProducer specification to feature-freeze

---

CHANGELOG.md
specification/metrics/api.md
specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3622
The language for resolving conflicts matches the language used for naming conflicts.
cc @MrAlias @jack-berg @jmacd

Clarify that metric advice is non-identifying

---

specification/metrics/supplementary-guidelines.md

I think in #3242 when updating the supplementary guidelines, we lost the initial export for one of the delta examples. I didn't see it when the original PR was open.
CC @dashpole, could you check if this is correct or whether I am missing something?
The second change just removes a redundant `a`, since I just stumbled across it I thought I'd remove it while I am at it.

Fix missing delta export and a typo in supplementary guidelines

---

specification/metrics/api.md

The example for creating a synchronous UpDownCounter and an Asynchronous UpDownCounter showed different idiomatic variations: `up_down_counter` vs `observable_updowncounter`. This change makes those consistent.
As this change seems trivial, I didn't add a changelog. Happy to add one if deemed necessary.

update code example for consistency

---

package.json

Version was pinned in https://github.com/open-telemetry/opentelemetry-specification/pull/3327 because of a bug in the tool, which is fixed, so we can use latest version again

nit: Unpin markdown-link-check version

---

CHANGELOG.md
specification/protocol/exporter.md

Fixes #3652
This PR attempts to clearly define `transient error` in the OTLP exporter specification.
It also fixes a bug in that the set of retryable status codes in the OTLP exporter spec vs. the protocol spec are not aligned.

Define transient error in OTLP exporter specification

---

specification/metrics/sdk.md

As per title they are called everywhere °advisory" a part for these two instances

Consistently use "advisory parameters" instead of "advice parameters"

---

CHANGELOG.md
specification/metrics/api.md

Fixes #3391
This is a prerequisite for HTTP semconv stability.
Stabilizes `ExplicitBucketBoundaries` instrument advisory parameter.
Prototypes in Java, JS, Go, and Erlang:
* https://github.com/open-telemetry/opentelemetry-java/pull/5217
* https://github.com/open-telemetry/opentelemetry-js/pull/3876
* https://github.com/open-telemetry/opentelemetry-go/pull/4341
* https://github.com/open-telemetry/opentelemetry-erlang/pull/628

Stabilize `ExplicitBucketBoundaries` instrument advisory parameter

---

CHANGELOG.md
specification/trace/sdk.md

ParentBased sampler is decorator (and not a composite).
> The intent of a composite is to "compose" objects into tree structures to represent part-whole hierarchies.
> What problems can the Composite design pattern solve? 
> [...]
> A part-whole hierarchy should be represented as tree structure
`ParentBased` does not produce a tree.  Composite aims to solve a different (but kind of similar) problem.
> decorator pattern [...] that allows behavior to be added to an individual [object](https://en.wikipedia.org/wiki/Object_(computer_science)), dynamically, without affecting the behavior of other objects from the same [class](https://en.wikipedia.org/wiki/Class_(computer_science)).
> What problems can it solve?
> Responsibilities should be added to (and removed from) an object dynamically at …

ParentBased is a decorator

---

specification/configuration/sdk-environment-variables.md

The OTEL_ATTRIBUTE_COUNT_LIMIT variable was described in the SDK environment variables document as the "maximum allowed _span_ attribute count" (emphasis added). The "span" in that sentence was likely a mistake, since this variable applies to attributes in general, and not only to span attributes. These are more appropriately controlled with the OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT, which is probably where this description was accidentally copied from.
This is a trivial change, so it follows the expedited process.

Fix description of OTEL_ATTRIBUTE_COUNT_LIMIT

---

specification/protocol/exporter.md

Bad references spotted during reading.

Fix note references in protocol/exporter.md

---

CHANGELOG.md
specification/common/attribute-requirement-level.md
specification/logs/data-model-appendix.md
specification/trace/sdk_exporters/zipkin.md

~Queuing this PR so I don't forget once https://github.com/open-telemetry/semantic-conventions/pull/342 is (hopefully) merged.~ https://github.com/open-telemetry/semantic-conventions/pull/342 is merged now
Rename/replace `(client|server).socket.(address|port)` attributes with `network.(peer|local).(address|port)`.

Rename/replace `(client|server).socket.(address|port)` attributes with `network.(peer|local).(address|port)`.

---

CHANGELOG.md
specification/protocol/exporter.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3721
The Go SIG is working towards stabilizing the OTLP metrics exporter.
The Go SIG would prefer to manage the exporter environment variables through a distinct package: https://pkg.go.dev/go.opentelemetry.io/contrib/exporters/autoexport. This approach is akin to [Java Autoconfigure](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure). The rationale behind this decision is as follows:
1. If users aim to utilize the `OTEL_EXPORTER_OTLP_PROTOCOL` and `OTEL_TRACES_EXPORTER`, we aim to support all the values documented in the specification. We want to ensure that users are not prone to encountering runtime errors if a protocol driver hasn't been registered in the code.
2. …

protocol/exporter: Configuration options MAY be implemented by exporter, SDK, or separate component

---

spec-compliance-matrix.md

Update spec-compliance-matrix.md for C++:
* `Get a Tracer with scope attributes` implemented by:
* https://github.com/open-telemetry/opentelemetry-cpp/pull/2371
* `Links can be recorded after span creation` implemented by:
* https://github.com/open-telemetry/opentelemetry-cpp/pull/2380
* `get_meter accepts attributes` implemented by:
* https://github.com/open-telemetry/opentelemetry-cpp/pull/2224

Update spec-compliance-matrix.md for C++

---

CHANGELOG.md
specification/configuration/sdk-environment-variables.md
specification/protocol/exporter.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3735
Addresses https://github.com/open-telemetry/opentelemetry-specification/pull/3730#discussion_r1369363907
Supersedes https://github.com/open-telemetry/opentelemetry-specification/pull/3730
I think it is a clarification, not a breaking change. Similarly to https://github.com/open-telemetry/opentelemetry-specification/pull/3730#pullrequestreview-1690193896

Add environment variable implementation guidelines

---

specification/protocol/exporter.md

Noticed some log omissions in the OTLP exporter doc where traces and metrics are mentioned. This change is editorial.

[editorial] Fix log omissions in OTLP exporter env vars document

---

specification/baggage/api.md
specification/context/api-propagators.md
specification/logs/README.md
specification/protocol/exporter.md
specification/resource/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3757
Changes:
- Refer to a W3C "working draft" version instead of "editor's draft" or "master branch" version
I also want to notice that most other hyperlinks is already referring to working draft. On this branch `https://www.w3.org/TR/` is found in 23 places.
I find this change editorial and I do not think it is worth putting an entry in the changelog.

Refer to W3C working draft versions

---

CHANGELOG.md
specification/trace/sdk_exporters/stdout.md

I couldn't find the definition for a standard output exporter for the trace signal, so I'm submitting one. This is mostly a copy of the definition already present for the metrics exporter. It doesn't specify a format for the output itself.

add definition for standard output span exporter

---

CHANGELOG.md
specification/logs/sdk_exporters/stdout.md

I couldn't find the definition for a standard output exporter for the logging signal, so I'm submitting one. This is mostly a copy of the definition already present for the metrics exporter. It doesn't specify a format for the output itself.
Similar to https://github.com/open-telemetry/opentelemetry-specification/pull/3740

add definition for standard output logging exporter

---

specification/logs/event-api.md

"merge conflict" between #3749 and #3772.

Remove outdated `event.domain` mention

---

CHANGELOG.md

Release 1.28.0

---

CHANGELOG.md
specification/metrics/sdk_exporters/prometheus.md

Adding some more options that are exposed in the OTel Go SDK, but not specified in the prometheus exporter details.

add optional otel_scope_info configuration for prometheus exporter

---

CHANGELOG.md
specification/baggage/api.md

* Align Baggage definition with W3C Baggage Specification, namely that it is a container of application-defined properties and that its use is not restricted to "annotating telemetry" as currently stated in the spec. In practice, since Baggage API provides read/write access to baggage, the usage cannot be restricted to observability function anyway, so this is not a breaking change.
* Also note the distinction from W3C about key uniqueness requirement (OTel being more restrictive).

Align definition of Baggage with W3C Baggage Specification

---

README.md

Fix build, which is currently failing because the permissions of the spec meetings notes file changed: https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit

Temporarily remove broken link to fix build

---

README.md

Revert #3806 
Document permissions are fixed and https://github.com/open-telemetry/community/pull/1850 adds a note on how to avoid this in the future.

Revert "Temporarily remove broken link to fix build (#3806)"

---

.markdown_link_check_config.json
CHANGELOG.md
specification/trace/sdk_exporters/zipkin.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3793
Update OpenTelemetry to Zipkin Transformation to handle attributes from older semantic conventions in a backwards compatible way so that following attributes are (again) handled:
- `net.peer.name`
- `net.host.name`
- `net.sock.peer.addr` & `net.sock.peer.port`
- `server.socket.domain`
- `server.socket.address` & `server.socket.port`
The backwards compatibility of a stable OpenTelemetry to Zipkin Transformation was broken by:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3402
- https://github.com/open-telemetry/opentelemetry-specification/pull/3713

zipkin: Handle older semconv

---

CHANGELOG.md
specification/protocol/file-exporter.md

Fixes #2390
The `*Request` proto messages are design for RPC/REST communication (request, response style) and may contain in the future information specific to this type of communication.
The `*Data` proto messages are design for cases where only the telemetry data must be encoded without ony OTLP specific metadata.

Use *Data proto messages for file exporter

---

CHANGELOG.md
spec-compliance-matrix.md

Part of incorporating [OTEP #225](https://github.com/open-telemetry/oteps/pull/225) into the specification.

Add spec compliance matrix entries for file configuration

---

CHANGELOG.md
specification/logs/data-model.md

Change the type of `Resource` to reference the definition in the SDK so that the resource's scheme URL is included in logs data model.
The Logs Data Model misses scheme URL of resource. All of the languages reuse a common type representing resource.
- Java (stable logs): [reuses a common resource type](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/logs/src/main/java/io/opentelemetry/sdk/logs/data/LogRecordData.java)
- .NET (stable logs): [reuses a common resource type](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/Implementation/OtlpLogRecordTransformer.cs) 
- C++ (stable logs): [reuses a common resource type](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/sdk/src/logs/read_write_log_rec …

Fix Resource field type in Logs Data Model

---

specification/protocol/otlp.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3799
- On the OTel website, when a reader visits the `specification/protocol/otlp` page, they'll be automatically redirected to the website's OTLP spec page.
cc @theletterf @svrnm

[editorial] Add redirect rule to published OTLP page

---

specification/protocol/README.md
specification/protocol/design-goals.md
specification/protocol/requirements.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3799. This PR adds front matter config to the **OTLP** **design-goals** and **requirements** pages so that:
- Each page automatically redirects to its new GitHub home, and 
- An "external link" icon is show next to the page links in the left sidenav (see the screenshot below)
-  Clarifies the text of the "OpenTelemetry Protocol" page to indicate that three pages have moved: design-goals, requirements, and the specification; not only the specification.
cc @theletterf @svrnm 
---
... of the OTel website showing the left side nav section of the OTel sepc:
> <img width=300 src="https://github.com/open-telemetry/opentelemetry-specification/assets/4140793/d2861192-4215-43a7-aed4-4b58bec07b22">

[editorial] OTLP design & req: redirect to GH & mark as external

---

specification/metrics/api.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3804
- Switches to use of canonical links (yielding HTTP 200) of the form `https://en.wikipedia.org` instead of the apex domain`https://wikipedia.org`, otherwise the OTel website link checker sometimes fails due to delays in page redirects (HTTP 301s)
- Similar to #3230
cc @theletterf @svrnm

[editorial] Use canonical URL to wiki page in metrics/api

---

spec-compliance-matrix.md

Support for OTEL_BLRP_* environment variables has been introduced in the rust client.
PR: https://github.com/open-telemetry/opentelemetry-rust/pull/1471
Updates the spec-compliance-matrix.md to reflect the updated capabilities of the rust client.

Update spec-compliance-matrix.md for rust client

---

specification/metrics/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3829
- Adds clarification on measurement processing for metric views and their relation the resulting metric streams, particularly when multiple views match the same instrument
- Fixes example that should generate a warning of conflicting metric identities
- Adds example for drop aggregation as a non-conflicting metric view

Clarify metric view measurement processing

---

specification/README.md
specification/baggage/README.md
specification/common/README.md
specification/compatibility/README.md
specification/configuration/README.md
specification/context/README.md
specification/logs/README.md
specification/metrics/README.md
specification/metrics/sdk_exporters/README.md
specification/protocol/README.md
specification/resource/README.md
specification/schemas/README.md
specification/trace/README.md
specification/trace/sdk_exporters/README.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/3922
- Either updates or adds `path_base_for_github_subdir` to selected page front matter
/cc @theletterf @svrnm

[editorial] Add Hugo front-matter path base

---

specification/metrics/sdk.md

Fix the typo in MetricFilter. Except for this line, it says `Accept_Partial` in the metric filter definition. I forgot this line when I renamed it.

Fix typo in MetricFilter

---

CHANGELOG.md
specification/logs/bridge-api.md
specification/logs/noop.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/1569

[editorial] Remove use of Object-Oriented term `class` in log signal

---

CHANGELOG.md
specification/trace/api.md

[editorial] Remove use of Object-Oriented term `class` in trace API

---

CHANGELOG.md
specification/metrics/api.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/1569

[editorial] Remove use of Object-Oriented term `class` in metric API

---

CHANGELOG.md
specification/metrics/api.md

The api.md document specifies the Metric API, it does not defined the OpenTelemetry defined implementations of this API. Remove or correct the details within this API and leave it for the implementation specification to define.
Importantly, the API is decoupled from implementation for a reason. Third-party implementation may exists that OTel does not have domain over. This document needs to written with that in mind.
Related to https://github.com/open-telemetry/opentelemetry-specification/pull/3171 and https://github.com/open-telemetry/opentelemetry-specification/issues/3071.

[editorial] Remove implementation specific specification from metric API

---

specification/metrics/data-model.md
specification/metrics/sdk.md

Related to #3866.
I think this is an editorial change, so I didn't update changelog.
1. Added a brief explanation to the existing Metric Points section (mainly for folks who followed the links in the SDK spec and came to this section).
2. Changed "points" to "Points".
3. Updated the links in the SDK spec.

Clarify metric point

---

CHANGELOG.md
specification/metrics/sdk.md

Follow up based on the TC discussion and spec issue triage discussion: https://github.com/open-telemetry/opentelemetry-specification/issues/3904#issuecomment-1969453098.
Related to #3904 and #3905.

Formalize the overflow and cardinality limit interaction

---

specification/overview.md

Continuing https://github.com/open-telemetry/opentelemetry-specification/pull/3900
The Metric signal overview was outdated, referencing classes that no longer exist.
- Added overview of Meter instruments
- Added section about views
- Updated wording / descriptions

Rework metric signal overview

---

package.json

https://github.com/tcort/markdown-link-check/issues/304 is breaking our build (a regression in that library).
It's the second time (at least?) this library break. Can we please pin it instead? See https://github.com/open-telemetry/opentelemetry-specification/pull/3682

Use a specific markdown-link-check version to fix the build.

---

specification/logs/sdk_exporters/stdout.md

I wonder if y'all at the specs SIG would be open to dropping the leading "OpenTelemetry" for this and other exporter pages, in those situations were it is unnecessary?
None of the Log's other subpages start with "OpenTelemetry"; here's the list:
- Data Model Appendix
- Events API Interface
- Logs Bridge API
- Logs Data Model
- Logs SDK
- Logs Bridge API No-Op Implementation
- Supplementary Guidelines
This makes "OpenTelemetry LogRecord Exporter - Standard output" stand out. So, for consistency, the Stdout exporter page probably shouldn't have OTel as the start of the title either. Also, for sake of consistency with the other exporters for Metrics and Traces, I think the title should use "Logs" rather than "LogRecord". WDYT?
/cc @theletterf @svrnm

[editorial] Logs > Exporters > Stdout - drop leading "OpenTelemetry" from the page title

---

specification/trace/tracestate-probability-sampling.md

Polish content in tracestate-probability-sampling.md

Polish document content

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md
specification/metrics/sdk_exporters/prometheus.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3702
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2468
Addresses https://github.com/open-telemetry/opentelemetry-specification/issues/3737#issuecomment-1787439083
* Add option to disable `target` info metric.
* Move SDK-specific language from the compatibility spec to the prometheus exporter spec.
* Disallow using OpenMetrics proto format, or Prometheus remote write formats in SDK exporters
* Recommend using Prometheus client libraries
* Clarify that only features supported by the text format are required to be implemented by Prometheus exporters
* Require prometheus SDK exporters to follow the compatibility specification.
@open-telemetry/wg-prometheus

Prometheus SDK exporter specification cleanups

---

spec-compliance-matrix.md

Go recently merged recording links after span creation.
See https://github.com/open-telemetry/opentelemetry-go/pull/5032
Note that this change is not released yet.
cc @open-telemetry/go-approvers

Update spec matrix to indicate go's links can be recorded after span creation

---

CHANGELOG.md
specification/metrics/sdk_exporters/prometheus.md

Similarly to the other options listed in the Prometheus exporter specification, adding a suggested name for the option to apply resource attributes as metric attributes.

add name suggestion to prometheus exporter option

---

specification/common/README.md

There is no section of this document which is called out as "Feature-freeze", so we must assume the whole document is stable.

Editorial: Remove erroneous feature freeze designation

---

specification/metrics/sdk.md

I'm making my best guess of what was intended. If the language should use `SHOULD` or `MAY` please comment.

Make exemplar default language normative

---

specification/configuration/file-configuration.md

Resolves #3466.
Supporting a JSON file format would be problematic:
- Env var substitution syntax is hard
- JSON doesn't allow comments
- We couldn't mandate JSON support across languages so supporting would be bad from an interoperability standpoint
Also, nobody has expressed interested in a JSON file format. Removing the TODO as it makes it seem imminent / likely which is not the case. This doesn't close the door on a JSON file format - just removes clutter.

Editorial: Remove TODO for JSON file format

---

CHANGELOG.md
specification/metrics/api.md

Stabilize synchronous gauge

---

CHANGELOG.md
specification/configuration/file-configuration.md

Add file configuration examples

---

specification/configuration/file-configuration.md

No other changes, just uppercasing the L

fix casing in BOOl_VALUE

---

.github/workflows/checks.yaml
docfx.json

DocFx v3 is no longer available and not intended to be used externally.
The feature it provided that we don't have from other tooling is cross-file anchor reference check, see https://github.com/open-telemetry/semantic-conventions/issues/1009 for the details. It seems there is no popular (or even not popular) replacement for it.
DocFx v2 only check anchors within the same file which markdownlint does as well.
Related: https://github.com/open-telemetry/semantic-conventions/pull/1008
Closes #4026.
This PR removes docfx since v2 does not provide additional value. We'll need to find a different solution for relative anchor checks.

Remove docfx

---

CHANGELOG.md

May 2024 release.
Important changes:
* Mark exemplars as stable (#3870)
* Mark synchronous gauge as stable (#4019)
* Record Links with empty/invalid SpanContext (#3928)

Release 1.33.0

---

specification/logs/event-api.md
specification/metrics/sdk.md

Small pedantic change -- "API interface" is technically redundant, so let's just stick with API.

Remove redundant usage of "interface" after API

---

specification/logs/README.md

Fix a typo in logging specification

---

specification/metrics/api.md

Adds the missing creation of a sync gauge to the meter operations list of links.

add 'create a new gauge' to meter operations

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

I found this confusion while reviewing https://github.com/open-telemetry/opentelemetry-dotnet/pull/5646#discussion_r1611719896.  The intention is for unit to be added in the same fashion for both OpenMetrics and non-OpenMetrics names.
Before this change, the name `seconds_before_my_birthday` would not have a unit suffix appended.  While this is a conceivable name, it isn't compliant with OpenMetrics, which is the intention of the spec.  Instead, it needs to be changed to `seconds_before_my_birthday_seconds` to be compliant with the OpenMetrics spec.
This change will prevent Exporters from needing to special-case unit handling for OpenMetrics vs non-OpenMetrics.
@open-telemetry/wg-prometheus @reyang @robertcoltheart

Clarify that unit must be a suffix for metric names for Prometheus

---

CHANGELOG.md
spec-compliance-matrix.md
specification/logs/bridge-api.md

Fixes #3917 
Knowing if a `LogRecord` will be dropped prior to performing computationally expensive operations helps developers using the Logs Bridge API avoid wasted and expensive work. This adds and `Enabled` API to the `Logger` to provide this functionality.
This is related to https://github.com/open-telemetry/opentelemetry-specification/pull/3877. In that PR `Loggers` may become entirely disabled. The `Enabled` method included here will help users determine this state.
- [Go](https://pkg.go.dev/go.opentelemetry.io/otel/log#Logger)
- [Rust](https://github.com/open-telemetry/opentelemetry-rust/pull/1147)
- [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/07f6cb54ece56691dbd2a94b0cbeec722ff6a631/api/include/opentelemetry/logs/logger.h#L259)

Add Enabled method to Logger

---

CHANGELOG.md
specification/trace/sdk.md

The current language implies only discarded attributes should be logged. However, the following sentence indicates that discarded events and links should also be logged. This updates the first sentence to included the omitted types.

Clarify the trace SDK should log discarded events and links

---

specification/logs/event-api.md

Resolves #3254 and #4045 
The PR adds clarity to the features provided by Events, as well as guidance on when it is appropriate to use the Event API.
* Reorganized the Data Model section for clarity
* Include MUST for the requirement that Event `Body` and `Attributes` fields conform to a schema.
* Include use cases for when Events are appropriate.
* Include a warning that advanced logging features are not currently accessible when using Events.

Describe the use cases for events in greater detail

---

specification/metrics/supplementary-guidelines.md

Permutations would be a way higher number, as the ordering matters in a permutation vs. a combination.

Correct "permutation" -> "combination" wording for attributes

---

specification/trace/api.md

- Fix link that is broken when the spec is published to the website. There shouldn't be a hash to the page title.
/cc @open-telemetry/docs-maintainers

[editorial] Fix link: drop anchor ID to page title

---

spec-compliance-matrix.md

In the spec compliance matrix, optional entries are to be noted with `X`, not `+`.

[editorial] Spec compliance matrix: optional noted with 'X', not '+'

---

spec-compliance-matrix.md

In the spec compliance matrix, add header lines for readability.
This fixes two issues:
* first, having an entry as blank forces the reader to consider whether this is a missing feature in a SIG implementation, which is an issue, or weather this is a header line, in which case a blank is not an issue.
* second, when many rows are present, reading the spec matrix in a web browser (or in an editor) is difficult because the column names are no longer rendered on the screen when scrolling down to see more content.
Repeating the header column names for intermediate sections fixes both issues.
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md …

[editorial] Spec compliance matrix: add sub headers for readability

---

spec-compliance-matrix.md

Python implementation supports the `Span.add_link()` after span creation since v1.23.0. See https://github.com/open-telemetry/opentelemetry-python/pull/3618

Update the specification matrix to indicate that Python supports recording links after span creation

---

CHANGELOG.md

July 2024 release.
FYI, the only non-editorial changes for this month are:
- (Experimental) Isolating Log Record Processor (#4062)
- Define casing for hex-encoded IDs and mark the "Trace Context in non-OTLP Log Formats" specification stable (#3909 )

Release 1.35.0

---

specification/baggage/api.md

Fixes #4082
Restrict baggage names to non-empty strings.

Clarify no empty string allowed in baggage names

---

specification/overview.md

Fixes #4149, fixing an incorrect statement about being able to apply a `View` to a `Meter`.

Fix incorrect assertion about views and meter in overview

---

specification/logs/event-api.md

Looks like some old leftover.
It is only a cosmetic change that does not need a changelog entry.

Use event.name in Event Data model

---

CONTRIBUTING.md

Fix after https://github.com/open-telemetry/community/pull/2051
CC @austinlparker @svrnm 
_May be good checking if this does not affect other repos._

Fix community contributing hyperlink

---

CHANGELOG.md

August 2024 Release.
Major changes:
- Remove restriction that sampler description is immutable.
([#4137](https://github.com/open-telemetry/opentelemetry-specification/pull/4137))
- Require separation of API and SDK artifacts.
([#4125](https://github.com/open-telemetry/opentelemetry-specification/pull/4125))
- Clarify no empty string allowed in baggage names.
([#4144](https://github.com/open-telemetry/opentelemetry-specification/pull/4144))

Release 1.36.0

---

specification/metrics/data-model.md

Fix syntax error in code example in data-model.md 

Fix code example in data-model.md

---

CHANGELOG.md
specification/overview.md

Some package managers (PyPi) don't provide means to reserve namespaces for projects. We also have a number of **external** instrumentation libraries in python that follow current guidance and use `opentelemetry-instrumentation-{component}` naming pattern.
These libraries are hard to distinguish from otel-authored ones. Also, when someone (legitimately following existing guidance) creates an external instrumentation package like this, it blocks our ability to have OTel-authored instrumentation with this 'good' name. 
See https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2759#discussion_r1698096166 for real-life example.
This PR changes the recommendation to:
- otel authored instrumentation should use `opentelemetry-instrumentation-*` pattern
- external instrumentation …

Update instrumentation library naming guidance to avoid conflicts between external and otel instrumentations

---

CHANGELOG.md
specification/trace/api.md

Fixes #3172
(Built on top of #4088)
- Explains kinds without assuming presence of parent/children 
- Adds links as another correlation mechanism
- Normalizes nested client spans even further - database, messaging, RPC, and LLM semantic conventions require CLIENT kind for logical client operation.
- Does not touch INTERNAL kind yet - https://github.com/open-telemetry/opentelemetry-specification/issues/4179
* ~~[ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #~~
* ~~[ ] Links to the prototypes (when adding or changing features)~~
* ~~[ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary~~

Refactor description of span kind

---

specification/configuration/sdk-environment-variables.md

I believe this was accidentally left out in https://github.com/open-telemetry/opentelemetry-specification/pull/3870/files

Mark exemplar filter env variable config as stable

---

specification/metrics/data-model.md

The doc for 2.52 is no longer available on the prometheus website, switching to use latest.
Saw the check failure [here](https://github.com/open-telemetry/opentelemetry-specification/actions/runs/10799406554/job/29955075935?pr=4188)

chore: fix broken link

---

CHANGELOG.md
specification/metrics/sdk.md

Same as https://github.com/open-telemetry/opentelemetry-specification/pull/4173 for metrics SDK.
Towards https://github.com/open-telemetry/opentelemetry-specification/issues/4134

Clarify metrics export concurrency

---

CHANGELOG.md

Release 1.37.0

---

specification/configuration/README.md

for https://github.com/open-telemetry/opentelemetry.io/pull/5195
If rendered on the opentelemetry.io
website the link title for the configuration index page is "Overview", this sets the title to "Configuration to address that"

[editorial] Set 'configuration' as title for configuration/README.md

---

.github/workflows/triage-followup.yml

Removes the `--dry-run` flag. We tested it and verified that it's creating the appropriate followup actions.

Enable Triage Followup Script Action

---

specification/trace/api.md
specification/trace/sdk.md

Fixes a few typos in the specifications.

Minor fixes of typos in trace/{sdk,api}.md

---

.github/scripts/triage-helper/app.py

Fixes a small logic bug in the script that was causing the followup label to be re-added after it was removed.

Fix triage script to ignore followup label removal when calculating changes.

---

CONTRIBUTING.md

There was a discussion among TC members about whether we should require 4 approvals for OTEPs.
Given we want to merge OTEPs into the specification repo, I think it'll be good to improve the spec PR merge criteria. Here is the thinking behind this change:
1. Having 2 approvals seem good to me, I haven't seen cases where people try to abuse it.
2. Increasing the number from 2 to 4 will slow down PRs for trivial/editorial changes. Many of the editorial PRs were contributed by first-time contributor to the OpenTelemetry project. I actually think we might want to speed this up rather than slowing it down.
3. Since the project started, I think the spec maintainers (TC members) have been careful about significant changes, so we make sure people have enough time to review, discuss and share their …

Update the PR merge criteria to allow situational judgement

---

CHANGELOG.md
specification/metrics/sdk.md

Clarify cardinality capping should be after filtering

---

specification/metrics/api.md

Editorial - Nit edits to make it easy to navigate the API spec by linking to relevant sections.

Editorial - add links to Metric instrument parameters

---

specification/metrics/api.md

Editorial only - adding a link from API to SDK doc for Metric name validation.

Editorial - Link to sdk section for Metric name validation

---

spec-compliance-matrix.md

This has been implemented in https://github.com/open-telemetry/opentelemetry-go/pull/4287.
See also https://github.com/open-telemetry/opentelemetry-go/blob/v1.30.0/exporters/otlp/otlpmetric/otlpmetrichttp/doc.go#L61-L67 for docs on it.
cc @open-telemetry/go-maintainers

Update spec-compliance-matrix.md for Go temporality preference

---

specification/metrics/sdk.md

I think this got left out by mistake in https://github.com/open-telemetry/opentelemetry-specification/pull/4222

Mark MetricReader cardinality limit as stable

---

specification/trace/sdk.md

`OnEnding` specifies that the ending timestamp should be set when the callback runs, and the span should be mutable.
These are requirements, so it seems like they should be marked as so.

Make the end timestamp and mutable span as requirements in onending

---

CHANGELOG.md
specification/glossary.md

Small follow up to https://github.com/open-telemetry/opentelemetry-specification/pull/4161
Updates the glossary to indicate that instrumentation scope's schema url and attributes are also identifying. I simplified the language a bit.

Update Instrumentation Scope glossary entry with correct identifying fields

---

spec-compliance-matrix.md

Update the spec compliance matrix for C++.
* Logs section
* Document that `LoggerProvider.Shutdown` and `LoggerProvider.ForceFlush` are implemented.
* see https://github.com/open-telemetry/opentelemetry-cpp/blob/6445819fceeb3bfea1444a88418f00a0df69cd2f/sdk/include/opentelemetry/sdk/logs/logger_provider.h#L93-L101
* Document that the `OTLP File exporter` is supported.
* see https://github.com/open-telemetry/opentelemetry-cpp/blob/6445819fceeb3bfea1444a88418f00a0df69cd2f/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_file_exporter.h#L26
* Context Propagation section
* Document that `TextMapPropagator` is supported.
* see https://github.com/open-telemetry/opentelemetry-cpp/blob/6445819fceeb3bfea1444a88418f00a0df69cd2f/api/inclu …

Update the spec compliance matrix for C++.

---

CHANGELOG.md

October 2024 Release.
Changes of special interest:
* [Mark cardinality limits as Stable](https://github.com/open-telemetry/opentelemetry-specification/pull/4222)

Release 1.38.0

---

CHANGELOG.md
specification/logs/bridge-api.md
specification/logs/event-api.md
specification/logs/event-sdk.md
specification/logs/sdk.md

This matches "Traces API" and "Metrics API" and can still be differentiated from "Logs Bridge API".
Follow-up from https://github.com/open-telemetry/opentelemetry-specification/pull/4236#pullrequestreview-2352473178

Simplify the name "Logs Instrumentation API" to just "Logs API"

---

CHANGELOG.md
specification/configuration/data-model.md
specification/configuration/sdk.md

Fixes #4181
cc @open-telemetry/configuration-approvers

Declarative config: clarify null vs empty

---

CHANGELOG.md
specification/versioning-and-stability.md

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/4257
This issue has been discussed in spec SIG meeting on 22 Oct 2024 and decision was made that we want this to be a requirement for language implementations.
This is a new requirement for implementations, which we believe becomes more and more important now that we have Stable signals that we would like to continue evolving.

Add requirement to allow extending Stable APIs

---

CONTRIBUTING.md

In the 10/22/24 spec SIG, we discussed that the prototyping requirement for newly proposed features with development maturity level has a "chicken and the egg" problem.
This resolves by clarifying what counts as a prototype for these cases.

Define prototype for proposed features in development

---

issue-management.md

Updates label name: it's `triage:deciding:community-feedback`, not `triage:deciding:needs-community-feedback`

[chore] Correct label name

---

specification/logs/api.md
specification/logs/event-api.md
specification/logs/event-sdk.md
specification/logs/sdk.md

- Followup to #4259. cc @tedsuo 
- Adds an alias due to the file rename
> <img width="645" alt="image" src="https://github.com/user-attachments/assets/9f99d8d9-8881-4d5c-966c-8ac609a39747">
- Adds a `linkTitle` (to be the same as for the API pages of other signals)
- The rename is the root cause of the initial build failure of https://github.com/open-telemetry/opentelemetry.io/pull/5552.
/cc @open-telemetry/docs-maintainers

[editorial] logs/api: add Hugo alias and linkTitle due to file rename

---

issue-management.md

This label is present on the issue tracker but a description was missing.

Add description of 'triage:followup'

---

specification/metrics/sdk.md

docs(metrics): fix typos in exemplars section

---

spec-compliance-matrix.md

Adding compliance matrix entry as .NET now supports adding links after Span creation.
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5972

Update Dotnet Matrix - Add Links after span creation

---

oteps/README.md

Now that we have moved the OTEPs to the Spec repo, we need to re-establish how to get the OTEP id. This PR simply keeps the former behavior, i.e. use the PR number as the OTEP id.
Yes, we may get a relatively long number, but it overall worked well and was simple enough to avoid confusion/conflicts.

Use PR number as OTEP id.

---

oteps/README.md

It was discussed, during the move of OTEPs to the Specification repo, that we want to let users know OTEPs are _not_ part of the Specification _until_ their contents have been actually integrated.
We had mentioned we may want to add this one to every OTEP. Any opinion?

Clarify OTEPs are documents of intent.

---

CHANGELOG.md
specification/context/api-propagators.md

Fixes #433
Discussed in 11/5/24 Spec SIG, and prototyped in Java and Go.
Adds `GetAll` method to Getter, allowing for the retrieval of multiple keys for the same value. For example, an HTTP request may have multiple `baggage` headers.
As written in the changes, the implementation of `GetAll` is strictly optional. This is for two reasons: 
1. Backwards compatibility with existing types/interfaces
2. Carriers do not necessarily support returning multiple values for a single key
This includes implementations of `GetAll()` in Java and Go, as well as using the method in the W3C Baggage Propagators (multiple baggage headers are allowed, [spec reference](https://www.w3.org/TR/baggage/#baggage-http-header-format)).
- Java: https://github.com/open-telemetry/opentelemetry-java/pull/6852
- Go: …

Propagation - Extract handles multiple values on carrier using same key

---

specification/configuration/sdk-environment-variables.md
specification/context/api-propagators.md

Build is currently failing due to this broken link, which appears to have been removed in the 2.0 version of jaeger docs: https://github.com/open-telemetry/opentelemetry-specification/actions/runs/12041693502/job/33627729557?pr=4295
Maybe @yurishkuro can confirm if there is an equivalent page in the latest version of the docs.

Fix jaeger propagation link

---

CHANGELOG.md
specification/logs/sdk.md
specification/metrics/sdk.md
specification/trace/sdk.md

> It is not necessary for implementations to ensure that changes to `disabled` are immediately visible to callers of `Enabled`.
I am OK with this statement. The implementation can use things like [`Volatile.Read`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.volatile.read?view=net-9.0) or `volatile` in .NET so that at some point a modified `disabled` value will be returned.
> I.e. atomic, volatile, synchronized, or equivalent memory semantics to avoid stale reads are **discouraged** to prioritize performance over immediate consistency.
I completely disagree with this statement as it encourages that we should never synchronize the memory which leads to data races. If we do not have any mean to synchronize then the user may NEVER get the updated value.
E.g. the program may …

Remove the recommendation to not synchronize access to Config.disabled

---

specification/compatibility/prometheus_and_openmetrics.md
specification/metrics/sdk_exporters/prometheus.md

Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main.  This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.

Update links to openmetrics to reference the v1.0.0 release

---

oteps/logs/0097-log-data-model.md
specification/common/README.md

Recently the semconv docs for attribute naming changed, so this PR updates this.

Update the link to the semconv attributes naming guideline.

---

.lychee.toml

Just discovered a bug I introduced when switching from command-line config to toml config

Fix lychee (markdown link check) toml config

---

specification/schemas/README.md

We probably forgot to update it when moved semconv out.

[editorial] Schema URL version matches SemConv version, not spec version

---

specification/metrics/sdk.md

Shutdown() for Exporter was pointing to Shutdown() for MeterProvider. Fixed to point to the right one. Same for Flush

Nit fix link to correct shutdown & flush

---

specification/protocol/file-exporter.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/5935
- Normalized intra-spec link in `file-exporter.md`: there is no need to have the path step out of the spec only to step back into it
/cc @arminru @svrnm

[editorial] Normalized intra-spec link in protocol/file-exporter.md

---

specification/trace/api.md

- Similar fix to #4366, in support of https://github.com/open-telemetry/opentelemetry.io/issues/5935. The `trace/api.md` page also has a stray `)` when published to the OTel website
- Normalizes path to intra-spec overview page.
/cc @arminru @svrnm
Apologies for the separate PRs, but I don't have my usual dev env setup so it was easier to fix these separately via the GH web interface.

[editorial] Normalized intra-spec link in trace/api.md

---

.lychee.toml
specification/common/attribute-naming.md

Leaving as draft for now because probably need to wait until after the next semconv release to merge it (when this link will exist https://opentelemetry.io/docs/specs/semconv/general/naming/).
cc @open-telemetry/docs-approvers

Update link to semconv attribute naming guidance

---

specification/logs/api.md

Leftover after:|
- https://github.com/open-telemetry/opentelemetry-specification/pull/4352
Thanks @cijothomas for spotting it.

[editorial] Update Logs API preface

---

CHANGELOG.md
specification/logs/noop.md
specification/logs/sdk.md

Towards:
- https://github.com/open-telemetry/opentelemetry-specification/issues/4207
Next step:
- ~~https://github.com/open-telemetry/opentelemetry-specification/issues/4364~~
- https://github.com/open-telemetry/opentelemetry-specification/issues/4363
Related OTEP PR:
- https://github.com/open-telemetry/opentelemetry-specification/pull/4290
Needed for:
- https://github.com/open-telemetry/opentelemetry-specification/issues/4208

Define how SDK implements Logger.Enabled

---

CHANGELOG.md
spec-compliance-matrix.md
specification/logs/api.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/4201
Reference implementations:
- https://github.com/open-telemetry/opentelemetry-go/pull/6180
- https://github.com/open-telemetry/opentelemetry-java/pull/6983
Related Slack thread: https://cloud-native.slack.com/archives/C062HUREGUV/p1736545245331779

Logs API to have functionality for reusing Standard Attributes

---

specification/compatibility/prometheus_and_openmetrics.md

- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/6196
- Switches to using the canonical link into the OpenMetrics repo
- Drops invalid link fragment
/cc @trask

[editorial] Use canonical URL to OpenMetrics repo, and more

---

CHANGELOG.md
specification/semantic-conventions.md
specification/trace/exceptions.md

This is follow up on https://github.com/open-telemetry/semantic-conventions/pull/1716 - cross signal guidance on how to record errors (and exceptions) in instrumentations. 
Follow up for https://github.com/open-telemetry/semantic-conventions/pull/1716
`exception.escaped` attribute is not used in practice within OTel instrumentations (checked Java, .NET, JS. Python, Go, C++ and Rust including contrib repos).
OTel instrumentations, in general, don't record handled exceptions, i.e. virtually all exceptions we're recording in non-native instrumentations are expected to escape span scope.
The litmus test whether to record exception on spans is whether the instrumentation is going to set span status to `ERROR` due to this exception.
A way to record all sorts of exceptions is being introduced in …

Deprecate `exception.escaped` attribute, update exception example

---

spec-compliance-matrix.md

Cardinality Limit is a stable feature in Metric SDK spec, but has no entry in the spec compliance matrix, making it hard to know which languages have implemented this.
This PR adds an entry with empty values for each languages; filling with actual status can be follow up work for each languages.

Add Cardinality Limit to Compliance Matrix

---

spec-compliance-matrix.md

Otel .NET supports capping by default, and supports changing at Metric level using Views, but not at MeterReader level.

Update cardinality cap spec matrix for OTel .NET

---

spec-compliance-matrix.md

Otel Rust - does not implement
OTel C++ - implement cardinality capping, but does not allow configuring.

Update spec matrix for cardinality cap - cpp and rust

---

specification/protocol/file-exporter.md

Update file-exporter with a clickable link to jsonlines.org.

fix: Improve link to jsonlines.org

---

CHANGELOG.md
specification/metrics/README.md

Fixes #4405
Updated the metrics design goals to scope out the StatsD client support.

Clarify metrics design goal, scope out StatsD clients

---

CHANGELOG.md
specification/configuration/data-model.md

Fixes #4027.
@open-telemetry/configuration-maintainers please take a look!

Convert declarative config env var subtitution syntax to ABNF

---

CHANGELOG.md
specification/configuration/sdk.md

Explicitly state that declarative configuration should support configuration of all SDK extension plugin interfaces, and list the current status of all of them.
This idea came up in a recent [CNCF slack discussion](https://cloud-native.slack.com/archives/C0476L7UJT1/p1742330526645349) with @aabmass.

List declarative config supported SDK extension plugin interfaces

---

specification/configuration/data-model.md

The example was showing the comment that applied to the line above it.

Fix incorrect comment in example

---

spec-compliance-matrix.md

Rust looks to already implement `LogRecordProcessor.Enabled`: https://github.com/open-telemetry/opentelemetry-rust/blob/b2de6cc5a3dc271fffee45f050e894fba57508ba/opentelemetry-sdk/src/logs/log_processor.rs#L61-L65
Also https://github.com/open-telemetry/opentelemetry-specification/issues/4363#issuecomment-2660164716:
> OTel Rust also has this capability. Here's an example where it is leveraged to improve performance by dropping unwanted log early.
>
> https://github.com/open-telemetry/opentelemetry-rust/blob/88cae2cf7d0ff54a042d281a0df20f096d18bf82/opentelemetry-appender-tracing/benches/logs.rs#L78-L85
CC @cijothomas @open-telemetry/rust-maintainers

compliance-matrix: Rust implements LogRecordProcessor.Enabled

---

CHANGELOG.md
specification/logs/api.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/4208
[Current state of implementations](https://github.com/open-telemetry/opentelemetry-specification/issues/4208#issuecomment-2754919458):
- [Go](https://github.com/open-telemetry/opentelemetry-go/blob/main/log/logger.go#L57) 
- [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/logs/logger.rs#L24C8-L24C21)
- [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/logs/logger.h#L269-L290)
- [PHP](https://github.com/open-telemetry/opentelemetry-php/blob/015da800aa005d69f1b54a54c28af9173e236c7f/src/API/Logs/LoggerInterface.php#L15-L20) 
- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/incubator/src/main/java/io/opent …

Stabilize Logger.Enabled

---

CHANGELOG.md
spec-compliance-matrix.md
specification/logs/api.md
specification/logs/data-model.md
specification/logs/sdk.md

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/4459
From the issue comments:
> `EventName` looks to be already supported by:
> - [Collector](https://github.com/open-telemetry/opentelemetry-collector/blob/ced2880d495cb48503d337fb8971d1cee5d2fe13/pdata/plog/generated_logrecord.go#L105-L108)
> - [Go](https://pkg.go.dev/go.opentelemetry.io/otel/log#Record.EventName)
> - [Java](https://github.com/open-telemetry/opentelemetry-java/blob/e6f90f58ce82c861f91fdf7474914ac66939b28f/sdk/logs/src/main/java/io/opentelemetry/sdk/logs/ExtendedSdkLogRecordBuilder.java#L26-L30)
> - [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/a6779d8e21c008204ea4b62affbec177f931ede9/sdk/include/opentelemetry/sdk/logs/read_write_log_record.h#L100-L104)
> - …

Stabilize EventName

---

CHANGELOG.md
specification/context/api-propagators.md

Handles closed #437
[API.Context] Drop reference to binary propagator.
It was closed ~year ago. No progress in couple last years. It can be added when needed. Now, it is misleading.
* ~~[ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #~~
* ~~[ ] Links to the prototypes (when adding or changing features)~~
* ~~[ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary~~

[API.Context] Drop reference to binary propagator

---

CONTRIBUTING.md

Some prototypes may be done in implementations that are not language libraries, such as the Collector (see discussion on #4223). This rewords the CONTRIBUTING.md doc to reflect this

[CONTRIBUTING.md] Specify that prototypes are not necessarily done in language implementations

---

oteps/0000-template.md

We already ask for prototypes in the CONTRIBUTING.md. Having the section in the template reiterates the need.

Add "Prototypes" section to OTEP template

---

CHANGELOG.md
specification/logs/api.md
specification/logs/sdk.md

Fixes #4220
Already used by Rust; https://github.com/open-telemetry/opentelemetry-specification/issues/4220#issuecomment-2828399052: 
> Yes. Otel Rust already has [more parameters for the Enabled()](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/logs/logger.rs#L57) check.
> 
> We expect to use that in Etw/user_events exporters scenarios, where we ask the OSKernel about whether a given event is interesting or not. Its [currently leveraging severity ](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/main/opentelemetry-user-events-logs/src/logs/exporter.rs#L391-L392) only, but we expect to leverage EventName(and scope too) in the future.
OTel Go prototype: https://github.com/open-telemetry/opentelemetry-go/pull/6702

[Logs] Add optional Event Name parameter to Logger.Enabled and LogRecordProcessor.Enabled

---

specification/entities/data-model.md
specification/resource/data-model.md
specification/trace/tracestate-probability-sampling.md

- Converts two new HTML tables into the equivalent Markdown syntax, otherwise the link references inside the tables don't get correctly processed by Hugo
- Fixes links that break when the spec is published to the website.
**Reminder**: don't link to spec page titles since those link targets don't exist in the published website HTML pages.
/cc @carlosalberto @jsuereth - once this get's merged, I'd like to test the OTel.io build again before you issue a release. So please let me know.

[editorial] Fix links and switch to table markdown syntax

---

CHANGELOG.md

May 2025 Release.
- Drop reference to binary `Propagator`.
([#4490](https://github.com/open-telemetry/opentelemetry-specification/pull/4490))
- Add optional `Event Name` parameter to `Logger.Enabled` and `LogRecordProcessor.Enabled`.
([#4489](https://github.com/open-telemetry/opentelemetry-specification/pull/4489))
- Add experimental resource detector name.
([#4461](https://github.com/open-telemetry/opentelemetry-specification/pull/4461))
- OTEP: Span Event API deprecation plan.
([#4430](https://github.com/open-telemetry/opentelemetry-specification/pull/4430))

Release 1.45.0

---

specification/entities/data-model.md

Add a requirement that each entity type must have a canonical set of identifying attributes. Observers unable to provide the full set must either defer to another source or use a different entity type.
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/4253

[entities] Define rules for setting identifying attributes

---

specification/logs/README.md

The k8sprocessor was renamed the k8sattributes processor some time ago. This is updating the spec to point to the correct place.

fix: update k8sprocessor link

---

specification/profiles/mappings.md

- Addresses OTel.io link-check failure reported in https://github.com/open-telemetry/opentelemetry.io/pull/6952#issuecomment-2967779704
- I'm not sure how to avoid this in the future. /cc @trask

[editorial] Use canonical link into semconv

---

oteps/metrics/0146-metrics-prototype-scenarios.md
specification/baggage/api.md
specification/context/README.md
specification/document-status.md

Follow up to #4529 
Discussed this recently during the Specification call and there was initial agreement regarding removing Feature Freeze (and potentially restoring it if needed).
PS - embarrassed to realize we had forgotten to remove Feature freeze from the Baggage API and Context documents.

Remove Feature Freeze from document statuses.

---

supplementary-guidelines/compatibility/aws.md

This doc is also available in semantic conventions (no changes here since semconv were moved to a different repo).
Removing spec copy in favor of semconv one to keep all AWS-specific instrumentation guidance in one place.

Replace AWS context propagation doc with link to semantic conventions

---

CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md
specification/metrics/sdk_exporters/prometheus.md

Related to https://github.com/open-telemetry/opentelemetry-specification/issues/4494
This change focuses on three things:
- Flexibilization of underscore scaping
- Flexibilization of unit and type suffix additions
The goal is to mimic Prometheus' existing configuration that controls the translation of metric names when receiving OTLP metrics via its /otlp endpoint. Configuration alignment will help users migrate in both directions (Prometheus/Collector) when switching their metrics collection systems.
Some further reading might be helpful for reviewers:
* Our guide for receiving metrics via OTLP, specifically the [UTF-8 section]
---

Prometheus translation modes

---

.markdownlint.yaml
CHANGELOG.md
specification/compatibility/prometheus_and_openmetrics.md

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/4494
This conversion is the inverse of the exp -> native conversion defined here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#exponential-histograms.
@open-telemetry/prometheus-interoperability @ywwg @krajorama

Define conversion of prometheus native histograms to OpenTelemetry exponential histograms

---

specification/compatibility/prometheus_and_openmetrics.md

Small adjustment after https://github.com/open-telemetry/opentelemetry-specification/pull/4505
cc @pellared @dashpole @aknuds1 @ywwg

prometheus: Clarify what to do when scope attribute conflicts with name, version and schema URL

---

specification/versioning-and-stability.md

Since an entity’s type is part of its identity, we should define stability guarantees for it, considering that the identifying attributes are already covered by resource attribute guarantees.
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/4451

[spec] [entities] Mention entity references in the stability guarantees

---

spec-compliance-matrix.md

The Java SDK has implemented the functionality required for parsing yaml files and generating SDK components
cc: @jack-berg  @zeitlinger

Update declarative file config spec compliance matrix for java

---

specification/versioning-and-stability.md

This should fix the failing link check in the https://github.com/open-telemetry/opentelemetry.io repo:
```
docs/specs/otel/versioning-and-stability/index.html
hash does not exist --- docs/specs/otel/versioning-and-stability/index.html --> /docs/specs/otel/entities/data-model/#entity-data-model
```
https://github.com/open-telemetry/opentelemetry.io/actions/runs/16885034448/job/47830450540

[chore] Remove implicit title anchor from versioning-and-stability.md

---

CHANGELOG.md

August 2025 release.
- Improve concurrency safety description of `LogRecordProcessor.OnEmit`.
([#4578](https://github.com/open-telemetry/opentelemetry-specification/pull/4578))
- Clarify that `SeverityNumber` values are used when comparing severities.
([#4552](https://github.com/open-telemetry/opentelemetry-specification/pull/4552))
- Mention entity references in the stability guarantees.
([#4593](https://github.com/open-telemetry/opentelemetry-specification/pull/4593))
- Clarify protocol defaults on specification.
([#4585](https://github.com/open-telemetry/opentelemetry-specification/pull/4585))
- Flexibilie escaping of characters that are discouraged by Prometheus Conventions
in Prometheus exporters.
([#4533](https://github.com/open-telemetry/opentelemetry-specification/pull/4533))
- …

Release 1.48.0

---

oteps/0202-events-and-logs-api.md

there's still one more link failure being reported, but I really don't understand it (cc @open-telemetry/docs-maintainers):
> Error:  https://opentelemetry.io/docs/specs/status/ | Network error: error sending request for url (https://opentelemetry.io/docs/specs/status/) Maybe a certificate error?

Fix broken link

---

.github/PULL_REQUEST_TEMPLATE.md
.github/scripts/compliance_matrix.py
.github/workflows/checks.yaml
CONTRIBUTING.md
Makefile
spec-compliance-matrix.md
spec-compliance-matrix/cpp.yaml
spec-compliance-matrix/dotnet.yaml
spec-compliance-matrix/erlang.yaml
spec-compliance-matrix/go.yaml
spec-compliance-matrix/java.yaml
spec-compliance-matrix/js.yaml
spec-compliance-matrix/php.yaml
spec-compliance-matrix/python.yaml
spec-compliance-matrix/ruby.yaml
spec-compliance-matrix/rust.yaml
spec-compliance-matrix/swift.yaml
spec-compliance-matrix/template.yaml

Part of https://github.com/open-telemetry/opentelemetry-specification/issues/3976#issuecomment-2375297172
The goal of this PR is to yamlify the spec compliance matrix without affecting the resulting markdown file (other than whitespace differences), so that folks can be sure the yaml files are correct extraction of the current state of the markdown file.

Yamlify the spec compliance matrix

---

spec-compliance-matrix.md
spec-compliance-matrix/js.yaml

Update the JavaScript spec compliance to the latest values for Declarative Config
Implementation: https://github.com/open-telemetry/opentelemetry-js/pulls?q=is%3Apr+%22feat%28opentelemetry-configuration%29%22+is%3Aclosed

update JS declarative config spec compliance

---

spec-compliance-matrix.md
spec-compliance-matrix/go.yaml

Updates the spec compliance matrix for declarative config implementation in Go.

update spec compliance matrix for declarative config in go
