open-telemetry/opentelemetry-specification

README.md, semantic-conventions.md, specification.md, terminology.md
This adds some basic structure as well as an explanation of the structure, versioning, etc.
=> Add basic spec structure

README.md
The description text in every section already contains the link, which makes section titles look confusing.
=> Remove links from section titles

specification/tracing-api.md
=> added a comment that End doesn't End children Spans

specification/resources-api.md, specification/tracing-api.md
Based on https://github.com/open-telemetry/opentelemetry-java/pull/352 discussion.
This also raise the question - if SpanData is immutable, Tracer will need to create a new `SpanData` with the `Tracer`'s `Resource` set before passing it to the exporter. Which requires a new allocation. Creating issue: https://github.com/open-telemetry/opentelemetry-specification/issues/68
=> Resource On SpanData + Specify SpanData format

terminology.md
=> adapter terminology

specification/package-layout.md
Fixes #52 
The best way to view this is: https://github.com/open-telemetry/opentelemetry-specification/blob/84c835b1746d14fa18d087d789728bb5e071afad/specification/package-layout.md
=> Add OpenTelemetry API package layout

README.md
Language can mean both a literal language (like English, or Chinese or C++, or Python) or some way of expressing things (terminology). But in the plural I think it primarily means the former (and in any case, we hopefully do not have multiple terminologies but only one).
=> Typo languages -> language

specification/distributedcontext-api.md, terminology.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/41.
Most are a copy-and-paste from https://github.com/census-instrumentation/opencensus-specs/blob/master/tags/TagMap.md#tagmap by renaming `Tag` -> `Entry` and `TagMap` -> `DistributedContext`.
/cc @c24t @dinooliva @mayurkale22 @rghetia
=> Add specs on DistributedContext and propagation.

specification/concurrency.md, specification/library-guidelines.md
Concurrency and Thread-Safety is specified in a separate document and
is linked from Language Library Design principles document.
Implements issue: https://github.com/open-telemetry/opentelemetry-specification/issues/91
=> Add Concurrency and Thread-Safety specification

specification/tracing-api.md
Fixes #38.
Documents are based on Java API: https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/Tracer.java.
=> Add Tracer operations specs.

specification/tracing-api.md
resubmitting #116 after changing email on CLA.
=> reformatted tracing-api.md and added TOC.

specification/tracing-api.md
=> Add specs on Span creation.

specification/tracing-api.md
Fixed the comment in https://github.com/open-telemetry/opentelemetry-specification/pull/124#discussion_r294392248.
=> Clarify mutually exclusive options in span creation.

specification/tracing-api.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/133.
The current order is local parent span -> remote parent span context -> no parent, if more than one out of the three parameters are set. Feel free to propose an alternative.
=> Clarify the order of mutually exclusive params when creating spans.

README.md, milestones.md
This document https://github.com/open-telemetry/community/blob/master/initial-milestones.md is more relevant in this repository. 
I will also send a proposal for refreshed milestones shortly after this one is merged
=> moved milestones document from the community repo

specification/tracing-api.md
Fixes #59 
This is based on the **current** effort. Observe I tried to keep the canonical codes brief ;)
=> Add Status to the Tracing section.

specification/propagators-api.md, terminology.md
Fixes #72.
Specs are based on Java APIs: https://github.com/open-telemetry/opentelemetry-java/tree/master/api/src/main/java/io/opentelemetry/context/propagation.
=> Add specs on Propagator API.

milestones.md
This proposal clarifies milestones of API revisions and SDK implementation. We are still shooting for a stable version of all project components in September and Sunset in November.
Milestones are quite aggressive to fit the desired goal.
=> Milestones proposal (clarification)

terminology.md
Just a minor edit.. I guess it meant to be a link in markdown syntax.
=> Correct a markdown syntax error

specification/tracing-api.md
This PR changes a subset of the Span API to the agreed model in #165. The rest of the changes will be added in a different PR, trying to keep this PR small so feedback can be addressed faster.
Updates #165
=> Change Span specification to focus more on capabilities.

specification/api-tracing.md, specification/sdk-exporter.md, work_in_progress/specification/resource/Resource.md
Changes are generated with
$ misspell -w .
See https://github.com/client9/misspell
=> Fix all typos

specification/api-resources.md
A focus of the specification on the capabilities that should be
afforded rather than strict requirements around implementation
enable better flexibility to ensure libraries are compatible with
the idioms of their corresponding languages.
This incorporates feedback discussed in #191.
Updates #165.
=> Modifying resources specification to describe capabilities

README.md, specification/proto-design-goals.md, specification/proto-requirements.md, specification/protocol.md
Moving the design goals and requirements docs from opentelemetry-proto
to this repository.
The design goals and requirements will help us design the right wire protocol.
The design goals part has been already approved and merged in
opentelemetry-proto, the requirements part were under review here:
https://github.com/open-telemetry/opentelemetry-proto/pull/22
=> Add OpenTelemetry protocol design goals and requirements

specification/api-metrics.md, specification/api-propagators.md, specification/api-tracing.md
Like #190, this PR removes references to the java implementation and specific method names in favor of a general description of tracing API.
Updates #165.
=> Generalize span operations

specification/api-tracing.md
No other changes rather than some formatting.
=> Use bullet list for status instead of headers.

specification/api-tracing.md, specification/overview.md
See more details here https://www.w3.org/TR/trace-context/#traceparent-header-field-values
=> Rename TraceOptions to TraceFlags to be w3c compatible

specification/library-guidelines.md
We want to encourage language library authors to give feedback to
specification writers and help improve the specification.
This notice is one of the ways to express this encouragement.
=> Add a note for language library authors

specification/sdk-span-processors.md
Resolves #155 
Resolves #54 
`Block when the queue is full processor` will be added in a separate PR.
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
=> Add SDK span processors spec

specification/overview.md
One typo ("Telemery") and one correction to the language in the Gauge description.
=> Fix a typo and a contradictory statement

specification/api-tracing.md
Remove addLink support from the Span API and allow only during Span creation. 
For more details about why see https://github.com/open-telemetry/oteps/blob/master/text/0006-sampling.md#links
=> Allow recording links only at Span creation time

specification/api-metrics.md
Builder pattern is not common in C# and should be avoided to minimize memory allocations
=> Builder pattern should not be used in C#

specification/library-guidelines.md
There was unnecessarily suggestive wording that implied that vendor
exporters should be part of language libraries.
Added a clarification regarding vendor-specific exporters, 
OpenTelemetry protocol exporter and standard output exporter.
=> Clarify placement of exporter implementation

specification/library-guidelines.md
Based on previous discussion [1] this PR adds a recommendation to include
exporters for several open-source protocols in language libraries.
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/6
[1] - https://github.com/open-telemetry/opentelemetry-specification/pull/277#discussion_r330372034
=> Add list of exporters that are recommended for SDK

specification/library-guidelines.md
We assume that API specification will have a version number.
We also assume that SDK's will implement a particular API version.
Library authors may want to make multiple SDK releases that are
implementing a particular API version. For example, we may start
with API version 1.0.0 and make an SDK release 1.0.0 that
implements that particular API.
Later library authors may want to make a bug fix in the SDK and
release 1.0.1. Note that this release implements the same API
version, there are no changes from API perspective. Now we are in
a situation when API and SDK versions diverged.
This diverging seems inevitable because most likely API versions
will change much less frequently than library authors will want
to make SDK releases that implement those particular API versions.
Both API and SDK …
=> Proposal: API and SDK version labeling

specification/overview.md, specification/sdk-tracing.md
=> clarifies parent and links

specification/overview.md
Addressed feedback from https://github.com/open-telemetry/opentelemetry-specification/pull/283. Sentences structure, no semantics change.
=> Minor grammar changes, addressed feedback from @haf

specification/sdk-tracing.md
=> Update Sampler interface base on OTEP 0006-sampling

specification/api-metrics-meter.md, specification/api-metrics-user.md, specification/api-metrics.md
This is rewritten content that was removed from PR#250.  There is only only substantial change here, but it is substantial. This specification now says that instruments are allocated by the `Meter`, meaning they are automatically registered and qualified by the named Meter's component namespace.  This resolves questions about what kind of registry support is needed and how to export metrics that have not been updated.
See the new caveats about instrument storage.  These changes will encourage users not to store instruments in static scope, otherwise they will be forced to use the global Meter to allocate metric instruments.
=> Specify the user-facing API for metric instruments

specification/api-metrics.md
This is a response to late-arriving feedback on #250. @AloisReitbauer 
This change from `Signed` and `NonNegative` to `Absolute = false/true` is coordinated with PR #299. I think this is a sensible improvement in naming.
=> Use Absolute(true/false) vs NonNegative/Signed

README.md, specification/overview.md
Update SDK spec regarding span processors and Tracers / TracerFactories.
=> Spanprocessors / TracerFactory

specification/api-tracing.md
This is minor refactoring of a Span Creation API. Mostly to add an option to pass SpanContext as a parent Span to the span creation API.
=> Clarification on Span Creation API

specification/sdk-tracing.md
This adds an option for how long an exporter can run before it is cancelled for taking too long, default of 30 seconds.
=> add timeout for how long the exporter can run

CHANGELOG.md
I believe I captured all of the major changes. Did I miss anything?
=> Update ChangeLog to include v0.2.0

specification/api-tracing.md
In my understanding, these are minimum requirements to be able to implement the W3C TraceContext spec correctly.
=> Clarify inproc propagation of TraceId & TraceState

specification/api-tracing.md
This adds clarification to the `SpanKind` field values.
=> Clarify the interpretation of `SpanKind`

specification/sdk-resource.md
Previously Resource label values could be only strings. This change allows
label values to be also bool, int64 or double if needed.
While it is expected that most label values will be strings (see for example
labels defined by semantic conventions [1]) there may be rare cases when
non-string values make more sense, for example a process ID is typically a
numeric value and belongs to the Resource.
This change also makes Resource label value types uniform with Span attribute
value types [2].
[1] - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-resource-semantic-conventions.md
[2] - https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-tracing.md#set-attributes
=> Allow non-string Resource label values

specification/data-resource-semantic-conventions.md, specification/data-semantic-conventions.md, specification/sdk-resource.md
We use the term "attribute" to describe arbitrary key/value pairs that can be added
to Span, while for a similar concept of key/values pairs on Resource we previously
used the term "label".
This commit makes the terminology uniform and uses the term "attribute" universally.
A separate question is whether we want to also support Resource "attributes" to
support all data types that Span "attributes" allow (currently only string "labels"
are allowed for Resource).
This fixes issue https://github.com/open-telemetry/opentelemetry-specification/issues/342
=> Use uniform terminology for Span and Resource attributes

specification/api-metrics.md
Remove spec part about singleton Tracers which leads to confusion.
regarding named tracers.
=> Tracer spec globals review

specification/data-resource-semantic-conventions.md
Some exporting protocols have built-in fields for this information
(e.g. OpenCensus), some other protocols don't (e.g. Jaeger).
Our approach so far has been that this sort of information is best to be
standardized via semantic conventions and conveyed as generic attributes.
This change adds the appropriate semantic conventions.
A companion change in https://github.com/open-telemetry/opentelemetry-proto/
will be made to remove no longer needed messages that describe the Library.
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/235
=> Add Resource semantic conventions for telemetry library attributes

specification/sdk-tracing.md
Fixes #316
Clarifies that multiple processors registered on TracerFactory allow multiple exporters (i.e. not chainable) but chaining could be done on additionally.
Now spec recommends chaining on exporters, check out #316 for reasons why processors are better suited for it.
=> SDK tracing: clarify multi-processors scenarios

specification/api-propagators.md
Raising https://github.com/open-telemetry/opentelemetry-python/issues/214 to the spec: The [specification for extract](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-propagators.md#extract) should mention how to deal with case sensitivity.
=> Clarify case sensitivity in propagator spec.

specification/api-tracing.md, specification/data-semantic-conventions.md
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/341
Array values are useful for representing attributes that can have
multiple values (e.g. representing a Memcached `get` that can be
over multiple keys and making the keys a span attribute).
This change allows homogeneous array values for span attributes
and specifies that array values should be JSON encoded string when
exporting using protocols that do not natively support array values.
=> Allow array values for attributes

specification/data-database.md, specification/data-http.md, specification/data-rpc.md, specification/data-semantic-conventions.md, specification/data-span-general.md
This splits the "peer" attributes from the database conventions where they don't really belong and reworks it, adding a common `net.` prefix and more.
Related changes (I felt leaving them out of this PR would make the conventions inconsistent):
- `peer.address` was renamed to `db.url` for DB
- `peer.service` was renamed to `rpc.service` for (g)RPC
- `peer.service` was dropped for DB
- Requirement for `peer.hostname`/`net.peer.name` in db was modified so that only one of name or IP is required (since you might connect by IP only to a DB).
Closes #295.
=> Add general semantic conventions for networking.

specification/api-tracing.md
It's popular in asynchronous scenarios to send messages in batches.
In this case, each message should carry a unique context to be individually traceable. Arguably it means creating span per message. Such spans do not represent remote calls.
Sending a batch (which is remote outgoing call) is represented by a different span that is linked to all of the messages span contexts.
So async messaging scenarios with batching involve
* *message* spans with PRODUCER kind (each of them is a parent of asynchronous request)
* *send* span that is CLIENT kind (which is remote outgoing call). But it is not a parent of any asynchronous request
In some cases (not involving batching) it is possible that dedicated *message* span is not needed and *send* may represent both: context in the message and remote …
=> Producer SpanKind does not always imply a remote call

specification/api-tracing.md, specification/data-http.md
=> Fix discrepancy between status names

specification/library-layout.md
I think /sdk/trace directory for /api/trace
=> Fixed typo for sdk/trace description

specification/api-metrics.md, specification/data-http.md
Having user agent data is often useful in troubleshooting. There are also extreme use cases like my current project where only certain browsers are contractually supported. Storing with traces eliminates the need to jump back and forth between tracing backend and log aggregation backend.
=> Define HTTP User-Agent attribute

specification/data-rpc.md
The previously defined requirement of always providing `net.peer.name` only works for a client connecting to a server.
A server on the other hand is usually not able to provide the host name of a client connecting to it, since it only has access to the IP address of the incoming request.
=> Fix RPC semantic conventions

specification/sdk-tracing.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/351
Some cases like AWS lambda can suspend a process before span processors export the completed spans. In these cases, it is desirable to flush the span processor to the exporter before the process suspends so that no spans are lost.
- Shutdown is not required by the specification to flush spans
- In many FaaS services, the same process will be used for multiple requests. In these cases it is desirable to only initialize span processors and exporters a single time per process, not per request.
The simple span processor does not batch, so will export spans as soon as they are completed. While this solves the flushing problem, it can be inefficient in many cases. It is a common use case for a lambda function to make …
=> Add flush interface to span processor

specification/sdk-tracing.md
This also cleans up the language slightly in this section..
=> Remove internal language-specific requirements from the batch span processor description.

specification/api-tracing.md, specification/data-http.md
=> Provide guidelines for low-cardinality span names

specification/data-http.md
Minor fixes/updates to HTTP semantic conventions.
=> HTTP: Allow user_agent also on client, remove peer.ip4.

specification/api-tracing.md
[OTEP 66](https://github.com/open-telemetry/oteps/blob/master/text/0066-separate-context-propagation.md#default-span-parentage) has a section where it offers guidance on how to parent a `Span` given a `Context`. This PR integrates those details into the api-tracing spec.
The bulk of this PR is the following text:
When a new `Span` is created from a `Context` there are several scenarios to
consider when selecting a parent. A `Context` can contain:
- A current `Span`
- An extracted `SpanContext`
- A current `Span` and an extracted `SpanContext`
- Neither a current `Span` or an extracted `Span` context
In order handle these scenarios, a convention has been established for assigning
a parent from a `Context`. The precedence for parent selection is as follows:
- Use the current `Span`.
- Use …
=> Add details for determining the parent Span from a Context

specification/sdk-resource.md
The Resource spec was moved from the API to the SDK but it still referred to the API in the text. This also updates to reference the Providers and all the tracers that may be retrieved from the provider (named tracers and meters).
=> update Resource spec based on the move to the SDK and named tracers

specification/data-http.md
Found by accident when editor started highlighting the text in quotes in weird ways.
=> Add missing quotes

specification/api-propagators.md, specification/api-tracing.md, specification/data-http.md, specification/overview.md
The Propagators API includes both binary and text propagators, however the binary format is not well defined and is without an agreed protocol. This has lead many languages to simply have a Noop implementation.
The W3C has binary protocols for different transports in progress but they have not been formally accept yet. It make senses to remove the binary propagator from the Open Telemetry spec for now and re-add once a protocol has been accepted.
In-progress W3C binary protocol proposals:
Trace Context Binary Spec: https://github.com/w3c/trace-context-binary
Trace Context AMQP: https://github.com/w3c/trace-context-amqp
Trace Context MQTT: https://github.com/w3c/trace-context-mqtt
=> Remove binary format propagator

specification/api-propagators.md, specification/overview.md
This is an initial PR focusing on updating the `Propagator`s API, and is meant to be get **initial feedback**, rather than getting merged right away. This is because related PRs are still not merged, which hopefully will change soon ;)
Overall:
1. Composite Propagator concept: Even though in OTEP 66 this part is rather defined as a function taking a **list** of propagators, I think it makes sense to **try** to go with a composite `Propagator` concept.
2. (Optional) Global Propagators. This has TraceContext/CorrelationContext as default global propagators, as some language implementations already do this.
=> Initial composite/global Propagators update for OTEP 66.

specification/data-database.md, specification/data-http.md, specification/data-rpc.md
In #271 it was decided to drop the span attribute `component` from the semantic conventions.
=> Remove `component` attribute from semantic conventions

specification/api-propagators.md, specification/api-tracing.md, specification/context.md, specification/overview.md
This PR intends to include some of the changes of OTEP 66, by making the Specification `Context` aware.
Summary of changes:
1. Add a `Context` mechanism section to describe what is expected in all languages overall. This is mostly described as a SDK API, in order to signal that users instrumenting their application shouldn't use it directly.
2. Update `Propagators` to make them directly consume `Context`.
3. Relax the `Tracer`'s current `Span` handling as this now belongs to `Context` (changes this part from MUST to SHOULD).
3. Removed `Binary` support for now. `Binary` needs to be updated to play along well, and it's still a work in progress anyway. The plan is to add it again in the near future, once it has been prototyped/tested.
I'm specially interested in feedback regarding 1), so …
=> Add the Context notion.

specification/api-metrics-meter.md, specification/api-metrics-user.md
Two documents have not been updated.
(1) api-metrics-user.md with detail on the user-facing API, needs to add Observer and remove Gauge as per OTEP 72 and 80
(2) api-metrics-meter.md was never finished following v0.3 as promised, push back to v0.4
This also adds TOCs in these documents.
=> Add out-of-date notices in api-metrics-user.md and api-metrics-meter.md

specification/api-metrics-user.md, specification/api-tracing.md
Now that https://github.com/open-telemetry/oteps/pull/76 has been merged, this is a follow up PR to address itss two major changes:
- rename factory to provider
- clarify the use of meter name as metric `namespace`
=> rename factory to provider and clarify namespace

specification/api-metrics.md
This specifies the changes described in these OTEPs:
https://github.com/open-telemetry/oteps/pull/80
https://github.com/open-telemetry/oteps/pull/72
=> Combined Metrics API updates for v0.3 (Add Observer instrument, remove Gauge instrument, etc.)

specification/exporter-zipkin.md
Replacing https://github.com/open-telemetry/opentelemetry-specification/pull/221 s it has no traction
I hope to get this merged before addressing other items that needs to be merged. Discussions for those may be easier to handle in small PRs
Related issue: #220
=> Transformation to Zipkin

specification/api-metrics-user.md
Just a minor detail but it hurts my eyes :).
=> Fix indentation in Golang example code

specification/api-tracing.md
Seems like SpanKind was forgotten to be mentioned in the list of span properties.
=> List SpanKind as a span property in api-tracing.md

specification/data-http.md
=> Remove references to obsolete `peer.*` attributes.

specification/data-resource-semantic-conventions.md
Resolves #484.
I renamed the attributes since calling them just `library` is highly ambiguous as we realized in the last SIG spec meeting.
By introducing a nested set of keys in `telemetry.sdk.*`, we could neatly introduce something like `telemetry.api.*` in future if we also want to keep track of the OpenTelemetry API version being used. This is, however, out of scope of this PR since this is only to clarify the current intention of the status quo.
I defined a hard-coded string for the OpenTelemetry default SDK in order to have a single uniform value across all language implementations. This makes it easier in case someone wants to build handling around that in a backend.
=> Clarify telemetry library resource attributes

specification/sdk-resource.md
The spec did never explicitly say that resources are immutable. It IMHO did so implicitly, as there are create+merge operations but no set operation. This PR makes immutability explicit.
All implementations that I know of already have immutable resources, so this should hopefully really just be a clarification.
=> Clarify that resources are immutable

specification/api-tracing.md
The IsRemote flag should be false on children of remote spans,
as the span itself was created locally.
Fixes #523
=> SpanContext.IsRemote is false on remote children

.circleci/config.yml
With the release of [go 1.14 in 2020-02-25](https://golang.org/doc/devel/release.html#go1.14), go 1.12 is no longer supported. This PR updates circleci jobs to use the go 1.14 docker container.
=> update circleci to use go 1.14

specification/trace/sdk.md
The sdk-tracing spec grouped everything but sampling under "Tracer creation".
This changes the top level section hierarchy to match the table of contents.
=> sdk-tracing: Fix section hierarchy

specification/trace/sdk.md
=> Remove the handling of retries by the SDK.

specification/metrics/api-user.md, specification/metrics/api.md
Following https://github.com/open-telemetry/oteps/pull/90.
@jmacd please check my work here, I may have mangled some of your go examples.
=> Remove LabelSet

specification/trace/semantic_conventions/http.md
It was not clear if "status message" refers to the general span status description or the HTTP reason phrase (see [Gitter request](https://gitter.im/open-telemetry/opentelemetry-specification?at=5e831abbac3c3909b2dce63c)).
=> Clarify span status guidance for HTTP spans

specification/metrics/api.md
Resolves #463 
We are still planning to support the capability to reduce the set of labels that are recorded during instrumentation but will do that using the Views. By default we will use all provided labels when we build the aggregation.
=> Remove default keys from metrics spec

specification/trace/semantic_conventions/messaging.md
I'm not sure what this should have to do with vendors, according to the examples, this would be the actual system names themselves. Otherwise the vendor for kafka would probably be "Apache", for example.
CC @arminru
=> Clarify messaging.system  (remove confusing "vendor" terminology).

specification/metrics/api-user.md
Should hopefully let us close #434 .
=> Add some clarifying language to the semantics of metric instrument naming

specification/trace/sdk_exporters/zipkin.md
This proposal is mostly related to OTEL collector as I assume it is the only one collecting Zipkin data in thrift format. I am not sure if this could also happen in JSON or proto (probably not). 
In Jaeger we have a set of span sanitizers https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/sanitizer/zipkin/span_sanitizer.go that properly set some span fields if the values are missing. I think it might be worth documenting these as we saw that old Zipkin instrumentations/clients might send spans with missing fields (start time, duration).
The only missing sanitizer is for span errors. Errors in Zipkin spans might have the following format `error=some error`. This will have to also be transformed to OTEL format. It is blocked by …
=> Document special Zipkin conversion cases

specification/trace/semantic_conventions/http.md
`host.port` was renamed to `net.host.port` in #349
Also resolves #369.
=> Fix HTTP span example

specification/context/context.md
=> Add a small explanation on why Restore is needed.

specification/context/api-propagators.md
[OTEP-66](https://github.com/open-telemetry/oteps/pull/66) originally had the propagator interface divided into separate `Injector`s and `Extractor`s. In OpenTelemetry Ruby we found some advantages to this division. For example, you can have asymmetry in the formats that are injected / extracted, and there are situations where order matters. By dividing `Propagator`s into `Injector`s and `Extractor`s you can still implement the `Propagator` and `CompositePropagator` interfaces by composing individual `Injector`s and `Extractor`s. This PR updates the [api-propagators spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md) to allow for that possibility.
Addresses #479.
=> Allow injectors and extractors to be separate interfaces

.circleci/config.yml, Makefile, specification/trace/semantic_conventions/http.md
The current build output is not really helpful, one would have to setup the build and execute it locally to figure out what failed.
before:
```
markdown-link-check FAILED => errors:
Run 'make markdown-link-check' to see the errors
Makefile:30: recipe for target 'enforce-markdown-link-check' failed
make: *** [enforce-markdown-link-check] Error 1
Exited with code exit status 2
```
after:
```
FILE: ./specification/trace/semantic_conventions/http.md
[✖] https://tools.ietf.orgg/html/rfc7230#section-3.1.1
[✖] span-generall.md#general-network-connection-attributes
[✖] https://github.com/open-telemetry/opentelemetry-python/pull/14800
31 links checked.
ERROR: 3 dead links found!
[✖] https://tools.ietf.orgg/html/rfc7230#section-3.1.1 → Status: 0
[✖] …
```
=> [build] Improve markdown-link-check output

specification/metrics/semantic_conventions/README.md, specification/trace/semantic_conventions/README.md
Currently the resource semantic conventions are easy to miss as brought up on #593.
=> Link from trace (and metric) semantic conventions to resources

specification/context/api-propagators.md, specification/correlationcontext/api.md, specification/overview.md
After discussions with the W3C Distributed Tracing Working Group, it has been determined that the Correlation-Context header is not ready for implementation and is being actively changed. As recommended by the working group, we should implement our own header until the specification is an official recommendation.
/cc @tedsuo @mwear
=> Change w3c correlation context to custom header

specification/trace/sdk.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/492
=> Replace ALWAYS_PARENT with a composite ParentOrElse sampler

specification/glossary.md, specification/trace/api.md
Address issue not resolved in #539:
https://github.com/open-telemetry/opentelemetry-specification/pull/539/files#r426546780
=> Fix instrumentation library synonym

Makefile, specification/context/api-propagators.md, specification/metrics/api.md
The Makefile isn't running the spelling and link-check tools correctly. This fixes it.
=> Makefile fixes

specification/trace/sdk.md
Fixes #614.
The tracer creation portion of the trace SDK spec specifies that the name and version used to obtain a tracer should be stored on  a `Resource` object and made available through a `getLibraryResource` method. With the introduction of [OTEP-83](https://github.com/open-telemetry/oteps/blob/master/text/0083-component.md), this is no longer accurate. The name and version should be represented as an `InstrumentationLibrary` instance instead.
See #614 for more discussion.
=> Tracers should reference an InstrumentationLibrary rather than a Resource

specification/vendors.md
Threw this together this morning and think it is a good starting point.
=> add vendors.md doc about what it means to support opentelemetry

CHANGELOG.md, specification/trace/sdk.md
Discussed during the 05/26/2020 specification SIG meeting.
Do we want SpanId as an input to a sampler?
* As of now ID of to be created span is required: https://github.com/open-telemetry/opentelemetry-specification/blob/5b78ee1adf437bb6c151d8992129f22970a96677/specification/trace/sdk.md#sampler
* Asked around and nobody recalled why we had SpanID in the first place, and there is no outstanding use case.
* Agreed to remove it from the spec.
* Resolution: @reyang will propose removing SpanID from sampling, to reduce overhead.
* History https://github.com/open-telemetry/opentelemetry-specification/pull/81
* Discussion https://github.com/open-telemetry/opentelemetry-dotnet/pull/683#discussion_r429062646
* Related & new: https://github.com/open-telemetry/opentelemetry-specification/issues/620 …
=> Remove SpanId from Sampler input

specification/trace/sdk_exporters/zipkin.md
Next step for #220 
Trying to keep PRs small and uncontroversial
=> Zipkin Exporter: Set the ServiceName from the resource attributes

specification/library-guidelines.md
=> Remove OpenCensus exporter requirement from the library guideline

experimental/README.md
discussed with @open-telemetry/technical-committee that experimental folder may expedite development of OpenTelemetry features. The first feature discussed is a zPages
=> propose experimental folder

specification/trace/api.md
I think saying that the root span "describes the end-to-end latency" is inaccurate. The "describes the entire operation" appears to be more accurate.
=> Improve root span description

CHANGELOG.md, specification/glossary.md, specification/library-guidelines.md, specification/trace/sdk_exporters/zipkin.md
There is an implicit convention around exporter packages in several
language instrumentations. Adding the convention to the spec standardizes
the convention.
=> Setting naming convention for exporter packages

CHANGELOG.md, specification/trace/api.md, specification/trace/sdk.md
This cleans up the tracing API spec, and clarifies what TracerProviders/Tracers are (not) allowed to do for different Tracers.
It also removes some wording regarding propagators that seems obsolete by now (OTEP66).
=> Clean up Tracing API spec, clarify Tracer vs TracerProvider.

CHANGELOG.md, specification/trace/semantic_conventions/faas.md
=> Add span attribute to indicate cold starts of Function as a Service executions

CHANGELOG.md, specification/trace/semantic_conventions/rpc.md
I generalized the semantic conventions to allow RPC systems other than gRPC.
Therefore, I added an attribute `rpc.system` (like we have for messaging systems as `messaging.system` [here](https://github.com/open-telemetry/opentelemetry-specification/blob/27e5c89075d3eeb5981e79bf8ab94d78aea5481d/specification/trace/semantic_conventions/messaging.md#messaging-attributes)) to identify the RPC system being used and added a section for gRPC, defining `rpc.system="grpc"` in this case.
Once we use proper YAML definitions, we can add a list of well-known descriptors to be used in addition to the ones I mentioned as examples.
Additionally, I added the method name as an attribute so that it doesn't have to be parsed out of the span name. This also makes it available for sampling decisions since the …
=> Extend semantic conventions for RPC and allow non-gRPC calls

CODEOWNERS
This proposal was reviewed by the @open-telemetry/technical-committee. We will update the teams accordingly to the following schema:
*  @bogdandrutu @carlosalberto @SergeyKanzhelev @yurishkuro @reyang @tigrannajaryan @jmacd 
@arminru @Oberon00 @tedsuo
@MrAlias @jkwatson @lzchen @cijothomas
TBD (@tigrannajaryan to propose the initial list)
**NOTE:** This PR will be copied in otep and proto repositories
=> Update codeowners to support area owners

CHANGELOG.md, specification/trace/semantic_conventions/http.md
This adds attributes for the payload size of HTTP requests / responses. I looked at [messaging](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md) too for inspiration but have ended up being inconsistent to better match HTTP conventions Whereas messaging has payload and compressed_payload, here I use content_length and raw_content_length. This is because the concept of content length for HTTP is defined by spec so matching it (i.e., using compressed size as content length for compressed payloads) seems to be clearer for users. But I'm happy to tweak as needed.
Fixes #640
=> Add semantic conventions for http content size

CHANGELOG.md, specification/resource/semantic_conventions/README.md
Adds semantic conventions for `process` as a resource which represents a regular operating system process.
=> Add semantic conventions for process resource

CHANGELOG.md, specification/resource/semantic_conventions/README.md
Currently Container Attributes in Resource have only `container.name` to represent the container instance. I am proposing adding `container.id` as a Container attribute.
Refer to docker documentation [Container identification](https://docs.docker.com/engine/reference/run/#container-identification), Container's `full-id`, `short-id` and `name` are equivalent in docker CLI like 'docker info <id>'. `name` is usually human readable and can be changed by command ['docker rename'](https://docs.docker.com/engine/reference/commandline/rename/#examples) during runtime. 
And [AWS X-ray](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-plugins) uses `container.id` represent the container instance in ECS, adding `container.id` in …
=> Add semantic conventions for container id

specification/trace/api.md, specification/trace/semantic_conventions/http.md
Fixes #591.
Adding semantic conventions for http start and end times. This has previously caused some ambiguity in the start / end times that instrumentations should target.
=> Clarify semantic conventions around span start and end time

.markdown_link_check_config.json, Makefile
Temporary workaround to get our spec builds green again until #668 is resolved properly.
=> [meta] Exclude github.com from markdown-link-check

specification/context/api-propagators.md
This is partially related to #496 as how to proceed when an extraction failed - currently we set a `null`/`empty` value, but it can be very useful to retain any previously existing value, as it would help with:
1. Reducing `Context` allocations for failed extractions.
2. Make things simpler for a `StackPropagator` (which handles multiple signal formats, such as B3 + W3C), as the prototype in #496 shows.
On the other hand, putting a `null`/`empty` value in `Context` upon extraction clears any previously leaked value, but that's an error in itself anyway.
cc @dyladan @Oberon00
=> Do not write a value in Context upon failed extraction.

CHANGELOG.md, specification/trace/semantic_conventions/database.md
We revised and extended the semantic conventions for database client calls that were initially copied over from OpenTracing by making definitions more precise and adding technology-specific attributes.
This should lead to improved data quality and allow better identification of databases and analysis of calls made to them.
Resolves #245.
=> Revise and extend semantic conventions for databases

specification/trace/sdk.md
The diagram was taken over from the OpenCensus spec and never updated, thus the OpenCensus ZPagesProcessor is still depicted there but not mentioned anywhere else in the spec.
There is currently an effort to get zPages into OTel as an experimental feature (see https://github.com/open-telemetry/oteps/blob/master/text/0110-z-pages.md), so this might be re-added in future once zPages makes it into the OTel spec as a standard feature.
=> Remove ZPagesProcessor mentioned in SDK spec

specification/trace/semantic_conventions/database.md
I forgot to update the example after introducing `db.redis.database_index`.
=> Fix Redis example in database semconv

specification/resource/semantic_conventions/README.md
Not all Unix based OSs have `procfs` (Darwin) or have it enabled by default (FreeBSD). Update the description to be specific to Linux systems.
=> Update resource `process.*` descriptions

README.md
Fixes #664 
Not sure whether we need to put this *also* in the Specification itself.
=> Use OTel as the official acronym in the README.

.github/ISSUE_TEMPLATE/context.md, .github/ISSUE_TEMPLATE/correlationcontext.md, .github/ISSUE_TEMPLATE/logs.md, .github/ISSUE_TEMPLATE/metrics.md, .github/ISSUE_TEMPLATE/miscellaneous.md, .github/ISSUE_TEMPLATE/protocol.md, .github/ISSUE_TEMPLATE/resource.md, .github/ISSUE_TEMPLATE/trace.md, .github/PULL_REQUEST_TEMPLATE.md
Follow up on the 7/14/20 SIG meeting, adding the issue/PR templates to make triage easier.
=> Add issue/PR templates

CHANGELOG.md, specification/resource/semantic_conventions/README.md
Please suggest additional well-known values for the list if you feel any fundamental platform is missing.
=> Add resource semantic conventions for operating systems

CHANGELOG.md, specification/trace/semantic_conventions/messaging.md
=> Adapt semantic conventions for the span name of messaging systems

specification/trace/sdk.md
The parameter `maxExportBatchSize` refers to "export", but `exporterTimeoutMillis` refers to the "exporter".  This unifies on "export" since they are both in reference to the same process.
=> Unify the batch span processor parameters

CHANGELOG.md, specification/trace/sdk.md
I noticed that the `Probability` sampler specification still specifies parent handling, but that it is superseded by the existence of the `ParentOrElse` sampler. This change makes it clear that parent handling should be done by `ParentOrElse` sampler and that `Probability` sampler does only probability.
=> Specify how probability sampler is used with ParentOrElse

specification/glossary.md
* Resolves #711 
* Fixes #715
The Markdown automatically add section anchors in the form `#section-caption-words`. Since this document contained old (redundant) anchors that used underscore between words I kept them for backwards compatibility.
=> Describe in-band and out-of-band terms

specification/common/common.md, specification/overview.md, specification/resource/sdk.md, specification/trace/api.md
Fixes #425
Fixes #446
Found Attributes defined in at least 3 different places, with different requirements. This PR tries to centralize the definition for the Attributes in a common place and share across (for the moment resources and traces).
=> Centralize attributes definition

specification/resource/semantic_conventions/README.md, specification/resource/semantic_conventions/cloud.md, specification/resource/semantic_conventions/container.md, specification/resource/semantic_conventions/faas.md, specification/resource/semantic_conventions/host.md, specification/resource/semantic_conventions/k8s.md, specification/resource/semantic_conventions/os.md, specification/resource/semantic_conventions/process.md
While trying to add more details for k8s I found that this file is very large and adding more to the same file makes it hard to read.
No text changes except updating the "TOC" and adding a list with links instead of full definitions for different resources.
=> Split resource semantic conventions in smaller files

specification/resource/semantic_conventions/k8s.md
=> Add semantic conventions for more Kubernetes objects

specification/trace/sdk.md
Discussed at the Spec SIG this morning 7/28. Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/728
=> Change the default sampler to ParentOrElse(AlwaysOn)

CHANGELOG.md, specification/trace/sdk.md
Resolves #663 "Allow for global processing of spans in SpanProcessor".
Required for #158 "Describe proto.Span class".
- OnStart must be read/write.
- OnEnd must be readable ~, may additionally be writable~.
Also clean up related wording for span exporters that couldn't decide whether they want to work for different kinds of telemetry data or only spans (they work only for spans).
=> Trace SDK: Provide definitions for readable and read/write span.

specification/trace/api.md
Fixes #468 
Remove warnings against using `Span.UpdateName`. Adds notes about Samplers being unable to recalculate their decision after `Span.UpdateName` or `Span.SetAttribute`.
This PR somewhat duplicates #506 submitted by @toumorokoshi . I made new PR because that one gone stale and author does not answer.
Citing myself from https://github.com/open-telemetry/opentelemetry-specification/pull/506#issuecomment-662279351
>Please, can we keep the scope of our discussion to the scope of this PR?
>
>I support the opinion that we cannot remove Span.updateName completely, because doing that will make many instrumentations much more complicated. As was demonstrated several times both in this PR and in the related task, there are valid use-case where "good" span name is unknown until after span is …
=> Remove warnings about Span.UpdateName

.github/workflows/state-pr.yaml
As discussed during today's maintainers meeting, this PR adds stale bot to the specification repo to close stale PRs.
For now I suggest running it in debug mode, without actually closing PRs. In a few days, when I verify it seems to be working (testing in production FTW), I will submit second PR removing debug mode.
=> Close stale PRs

specification/trace/api.md, specification/trace/sdk.md
Follow-up to https://github.com/open-telemetry/opentelemetry-specification/pull/669#issuecomment-667148933
* Adds a SHOULD requirement that for spans passed to OnStart, updates should be reflected.
* Makes the convoluted definitions of read/write and readable span easier to read.
=> Clean up R/W span spec.

specification/context/api-propagators.md, specification/correlationcontext/api.md, specification/trace/api.md, specification/trace/sdk.md
Fixes #637
Also specifies what's the expected location of TraceContext in the API.
=> Specify the initial propagators requirements.

specification/sdk-environment-variables.md
Fixes #572.
This is an initial draft of an environment variable specification. As stated in the spec, the goal is to unify the names of environment variables between SDK implementations. SDKs are not required to add configuration for the variables specified, but if they do, they should align with names in this spec. 
This list was compiled from comments on https://github.com/open-telemetry/opentelemetry-specification/issues/572 and surveying a number of SDK implementations. Defaults have been provided where applicable and likely to be uncontroversial. The door is open to add more detail if we would like to.
Lastly, this is meant to be a starting to point document and align environment variable names going forward. To that end, if a SIG adds a new environment variable that is applicable …
=> add initial env var draft specification

specification/trace/api.md
Stress that empty arrays must be forwarded to span processors/exporters.
=> Empty arrays are meaningful

specification/sdk-environment-variables.md
Follow up to #666 
The reason being that Resource Labels were (relatively recently) renamed to Resource Attributes.
=> Use OTEL_RESOURCE_ATTRIBUTES instead of OTEL_RESOURCE_LABELS.

specification/resource/semantic_conventions/k8s.md
Ability to differentiate between container name in a Pod template vs name of a running container created as a result of the template in semantic convention. 
Let's take for example the following spec for a Job that specifies container name to be `hello`. 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: hello
spec:
template:
spec:
containers:
- name: hello
image: busybox
command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
restartPolicy: OnFailure
```
Example obtained from [here](https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates).
On applying the above spec, the container that's created will not necessarily have `hello` as its name. The container name set by the container engine could be different from the one specified in the pod template.
Add a …
=> k8s: Differentiate container spec name and container name

CHANGELOG.md
This is a follow-up to #697 which was missing a CHANGELOG entry.
CC @mwear, @iNikem
=> Add CHANGELOG entry for exceptions.

specification/trace/api.md
Updates #753 
Clarifies that `IsValid` and `IsRemote` are APIs.
=> Clarify that IsValid and IsRemote are APIs on SpanContext

specification/trace/semantic_conventions/exceptions.md
All other stacktraces use the full message (including type, message, etc), for Ruby only the plain stacktrace.
I will use this opportunity to repeat that I think exception.stacktrace is a misleading attribute name as discussed in https://github.com/open-telemetry/opentelemetry-specification/pull/697#discussion_r453662519 where I pointed out exactly this ambiguity. 😉  
* Fix exception.stacktrace recommendation for Ruby.
=> Fix exception.stacktrace recommendation for Ruby.

specification/common/common.md, specification/trace/api.md
Fixes #763 
The requirements for Resource and Span attributes are now consistent w.r.t.:
- empty values are not discarded
- `null` values are dropped and can remove an existing attribute iff overwriting is possible
=> Consistency between Span and Resource attributes

specification/context/api-propagators.md
Fixes #489 
Even though the Jaeger propagator has a vendor name in the key, it is a CNCF project that we should support. The name is most likely a legacy in the project and it we should not consider it as a "vendor" specific propagation.
=> Add Jaeger propagation as one of the officially supported propagation

specification/glossary.md, specification/overview.md
Fixes #528.
* Add link from overview to glossary and vice versa
* Add TOC to overview and glossary (overview has it folded in `<details>`, glossary has it expanded as no one is gonna read it top to bottom).
=> Clean up glossary and overview (resolves #528).

specification/common/common.md
Resolves: https://github.com/open-telemetry/opentelemetry-specification/issues/726
=> Add conventions for attribute names

specification/resource/semantic_conventions/README.md
In addition to the version of the SDK, I propose to add a resource semantic convention for the optional version of the auto instrumentation agent if that is used.
=> Add semantic convention for telemetry.auto.version

specification/trace/sdk_exporters/zipkin.md
Add rules for translating `InstrumentationLibraryInfo` from OTLP to Zipkin
=> Add translation of InstrumentationLibraryInfo to Zipkin

specification/correlationcontext/api.md, specification/trace/sdk_exporters/otlp.md
This PR adds configuration and retry behaviour specification for the OTLP exporter. Most of the configuration options are based off of the opentelemetry-collector configuration and the environment variables proposed are based on #666 
Fixes #681
=> Adding OTLP Exporter

specification/trace/semantic_conventions/span-general.md
Fixes #788
Added two new span attributes responsible for storing current thread information: `thread.name` and `thread.id`
Related issues: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/942
=> Add semantic conventions for thread.name and thread.id span attributes

specification/trace/api.md
Fixes #796 
Clarifies that when timestamp of event is not provided, current time must be used.
=> Clarify that optional timestamp means current time should be used.

CHANGELOG.md, specification/trace/api.md
Clarifies the behavior of the Trace API, in the absence of an installed SDK, especially with respect to context propagation.
Fixes #689 
Adds requirements for Trace API behavior in the absence of an SDK.
=> Add requirements for how the Trace API should behave in the absence of an SDK

specification/metrics/api.md
Update the Metric API specification to explicitly describe the no-op nature of the API.
Related issues #719
=> Add clarification on the no-op nature of the metric API.

specification/common/common.md
We earlier defined naming rules for attributes, however we do not have
similar rules for metric labels. This commit extends the exact same
set of rules to metric labels.
This was brought up in this comment https://github.com/open-telemetry/opentelemetry-specification/pull/807#discussion_r471550053
=> Extend attribute naming rules to metric labels

specification/trace/sdk_exporters/jaeger.md
Add rules for translating InstrumentationLibraryInfo from OTLP to Jaeger.
=> Add translation of InstrumentationLibraryInfo to Jaeger

specification/trace/api.md
Resolves #557.
(quoted from https://github.com/open-telemetry/opentelemetry-specification/pull/810#issuecomment-674710718)
1. Why a guideline at all? It streamlines discussion and avoids inconsistencies. For example, it would decide #548. There does not need to be a trade-off with human-readability here, since we could have both if we really wanted (see next point).
2. Why not prefer human-readability? Because a good display name can be synthesized without much trouble on the backend. This argument was one of the main reasons for declining #730 (see https://github.com/open-telemetry/opentelemetry-specification/pull/730#discussion_r459694652 by @yurishkuro) and I think it is a sound argument. On the other hand, a grouping key can be utilized for agent-side sampling (e.g. have a sampler …
=> Clarify span name criteria (resolves #557).

specification/metrics/api.md
Fixes #618 
Adds that Unbind() is a requirement so that users can take advantage of short-lived bound instruments without a long-term memory requirement.
=> Metrics API: Specify that Unbind() is a MUST

specification/resource/semantic_conventions/host.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/787
Idea from the issue is that we should use `host.name` with either of the proposed values.
=> Remove duplicate hostname attribute

spec-compliance-matrix.md
This commit introduces the compliance matrix. It is not yet a complete
list of features that we want to track. I marked several sections as
TBD. We will need to add features/rows in those sections in separate PRs.
In the meantime we can ask SIGs to add +, - or N/A in the sections
that are more or less ready (currently Traces API and OTLP, Zipkin Exporters).
If you see anything incorrect/missing in Traces API and OTLP or Zipkin Exporter
please suggest in this PR. Please do not suggest rows for the rest of the sections
since it will likely result in this PR staying for a very long time and I would like
to get the ball rolling with the SIGs first.
Suggestions to use a different format or approach to record this information
are welcome.
Related issues …
=> Add specification/implementation compliance matrix

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md
Discussed during the 8/24/2020 SIG meeting, we want to get changelog better maintained.
* Updated the `CONTRIBUTING.md` doc by suggesting folks to update changelog for non-trivial changes.
* Updated the PR template to remind people.
* Reformatted the `CHANGELOG.md` file using standard GFM (GitHub Flavor Markdown) syntax - no real content change.
=> Update instructions for CHANGELOG

spec-compliance-matrix.md
Remove LazyEvent and LazyLink as they got removed from spec in https://github.com/open-telemetry/opentelemetry-specification/pull/840
`CHANGELOG.md` for non-trivial changes.
=> Remove LazyEvent and LazyLink as they got removed from spec.

spec-compliance-matrix.md
IsRecording was missing.
`CHANGELOG.md` for non-trivial changes.
=> Add IsRecording, remove Get for Status. and Set/Get for Kind in Spec Compliance Matrix

spec-compliance-matrix.md
This removes the duplicate entry from the spec compliance matrix.
=> Remove duplicate service name mapping from matrix

specification/trace/api.md
The current spec text says "During the Span creation user MUST have the ability to record links to other Spans.". It is not clear if span creation is the only time when one can add Links, or it can be added after creation as well (similar to SetAttribute).
This PR just make it explicit that Link can be added at Span creation time only. Hopefully this was the original intention, and this PR is just clarifying it, not introducing or proposing any behavior change.
`CHANGELOG.md` for non-trivial changes.
=> Clarify that Links can be added at Span creation time only

CHANGELOG.md, specification/logs/data-model.md, specification/metrics/api.md, specification/resource/semantic_conventions/README.md, specification/resource/semantic_conventions/faas.md, specification/resource/semantic_conventions/host.md, specification/trace/api.md
Fixes #802
Removes the convention of prefixing version numbers with things like `semver:`, `git:`. This comes from the idea that the version is the version, adding prefixes makes it something that isn't the version, nor a duck. If a user queries their data for a version number, it is very unintuitive to have to prefix queries with `semver:`, or otherwise every single data store that stores this data needs to natively understand our spec well enough to do this for them which doesn't seem like a worthwhile restriction.
I didn't add a separate attribute for the version type - in the issue, no one championed for it. I can add it if it seems very useful. Need to do it now instead of later since then it needs to be `foo.version.id` + `foo.version.type`, we can't have `foo.version` + …
=> Remove version convention / semver prefix from versions.

specification/trace/api.md
SpanBuilder was specified in Concurrency section, but "SpanBuilder" term is never defined elsewhere. Removing this to avoid confusion.
`CHANGELOG.md` for non-trivial changes.
=> Remove SpanBuilder from Concurrency as its not defined anywhere else.

specification/trace/sdk.md
Fixes #883.
Only non-normative changes, so no CHANGELOG entry.
=> Fix Sampler.ShouldSample parameter descriptions.

spec-compliance-matrix.md
A trailing `|` was causing incorrect column to header alignment
=> fixing env var section of the spec matrix

specification/baggage/api.md
Changes the Baggage header name in the example to match the spec, at least until the header name is changed again (#879).
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/baggage/api.md#header-name
> Baggage implementations MUST use the header name otcorrelations.
=> Use correct header name for Baggage in example

specification/trace/api.md
Change syntax to reflect the requirement that all `SpanContext` implementations need to allow retrieving the `TraceId` and `SpanId` in defined forms.
=> Explicitly use notation conventions in trace API for SpanContext implementations

spec-compliance-matrix.md
As discussed in the latest Spec SIG call, we need to add Context Propagation items.
=> Add Context items for the Compliance Matrix.

specification/trace/semantic_conventions/exceptions.md
=> Fix Ruby stacktrace link reference in exceptions.md

CHANGELOG.md, specification/trace/api.md
Fixes #908.
I explicitly specified both APIs as required, which I think was the initial intention.
~According to the [spec-compliance-matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/master/spec-compliance-matrix.md#traces), only JS is known to not have implemented `IsValid`.~
--> implemented in the meantime
Apart from that, I slightly reworded `IsRemote` to not have the API spec dictate how it should be implemented.
=> Specify IsValid and IsRemote as required

specification/trace/api.md, specification/trace/sdk.md
Fixes #759
Add description of TraceState operations.
=> Add description of TraceState operations

specification/trace/semantic_conventions/faas.md
As pointed out here https://github.com/open-telemetry/opentelemetry-specification/pull/888#discussion_r478866767
if faas.name is not set, the Instrumentation probably doesn't know the name
and thus the span name would most likely also not contain it.
=> Delete sentence about using span name when faas.name is absent

spec-compliance-matrix.md
Updated the spec compliance matrix to reflect the status of OpenTelemetry C++.
=> Update compliance matrix for C++

specification/library-guidelines.md
=> Explicitly allow SIGs to split artifacts

specification/trace/sdk.md
Fixes #781.
Note that how span and trace IDs are (not) to be generated is currently unspecified, see #864 
* Describes association of Sampler with TracerProvider. This is hopefully how everyone already implemented this.
=> Describe association between Sampler and TracerProvider.

semantic_conventions/trace/database.yaml, specification/trace/semantic_conventions/database.md
Updated Database semantic convention to the YAML format.
Related issues #547
=> Add yaml semantic conventions for Database

specification/trace/sdk.md
- `NOT_RECORD`
- `RECORD`
- `RECORD_AND_SAMPLED`
Seems like we should pick between present tense or past tense and make it consistent. I am proposing that we use past tense as in it's a decision that has already been made.
`NOT_RECORD` doesn't make sense. It is not correct English.
- `NOT_RECORDED`
- `RECORDED`
- `RECORDED_AND_SAMPLED`
Related: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1255
=> Inconsistent Sampling Result Names

spec-compliance-matrix.md, specification/sdk-environment-variables.md
Fixes #710
Adds `OTEL_EXPORTER` environment variable to select the exporter to be used.
Adds `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable to configure the ingest endpoint for both OTLP spans and metrics.
1. I added `OTEL_EXPORTER_OTLP_ENDPOINT` in this PR because I think it makes the default value `OTEL_EXPORTER=otlp` make more sense.
(It also happens to be the env var that the Java SDK uses currently, and seems simpler for most OTLP users, who will be sending spans and metrics to the same endpoint)
An alternative would be to specify the default value as `OTEL_EXPORTER=otlp_span,otlp_metric`.
2. I went with the singular `OTEL_EXPORTER` over the plural `OTEL_EXPORTERS`, since the common use case is to configure just one exporter and so this seems less confusing.
=> Add OTEL_EXPORTER environment variable

specification/trace/sdk.md
Addressing the following comment as many seem to have agreed to it.
https://github.com/open-telemetry/opentelemetry-specification/pull/938#discussion_r487130730
=> Rename Ignore to Drop for SamplingResult

spec-compliance-matrix.md, specification/trace/sdk_exporters/zipkin.md
Fixes #568
The Zipkin exporter specification suggests sending timestamps in fractions, while the Zipkin swagger documentation specifies integers https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml. This change removes the ambiguity and adheres to the Zipkin spec. 
The spec compliance matrix has been updated to reflect this change.
=> Address ambiguity in zipkin formatting

specification/sdk-environment-variables.md
Adds known propagator values to the environment variables specification.
=> Adding known values for OTEL_PROPAGATORS

specification/trace/sdk_exporters/zipkin.md
The official rename of the acronym happened after this spec was made, but looks like we haven't updated it yet.
=> Rename prefix for Zipkin attributes from OT to OTel

specification/context/api-propagators.md
Fixes #960
This PR clarifies expectations around B3 context propagation. Specifically, B3 propagators:
* MUST support extracting context from both single and multi-header encodings
* MUST default to injecting context using the multi-header encoding, but
MAY provide configuration to change the default
Additionally, it relaxes the requirement that b3 and jaeger propagators need to distributed as extension packages, making it possible to distribute them as part of the SDK if a language chooses.
=> B3 clarification

CHANGELOG.md, semantic_conventions/trace/http.yaml, specification/metrics/semantic_conventions/http-metrics.md, specification/trace/semantic_conventions/http.md
=> Remove obsolete `http.status_text` from semantic conventions

CHANGELOG.md, specification/baggage/api.md
Updates https://github.com/open-telemetry/opentelemetry-specification/issues/879
For the moment still use a different name to protect against may possible breaking changes to the [w3c baggage header](https://github.com/w3c/baggage).
=> Update the header name for otel baggage, and version date

CHANGELOG.md, specification/metrics/api.md
Fixes #834.
Apply the decision in #834.  The ValueObserver instrument should use LastValue aggregation by default, since those are the semantics of the instrument itself. Clarify that #625 has not been decided. See also #982.
=> Specify LastValue for ValueObserver, TBD for ValueRecorder

semantic_conventions/README.md
Fixes #979
This PR doesn't change any existing files, it only adds a new README to the semantic_conventions directory at the root of this repo.
I've verified that the addition of this readme does not affect the functioning of the semantic convention build tool.
=> Add README describing use of semantic convention YAML models

README.md
Adding a pointer to the website so that people who are being linked into the spec repo blindly will have a route to get a better explanation of the project.
- Updates README
=> Add a link to the OpenTelemetry website from README

CHANGELOG.md, specification/trace/api.md
Fixes #949 
Define the notion of a `PropagatedSpan`, which wraps a `SpanContext`, and can be leveraged to simplify the active `Span` logic when detecting the parent `Span` in a given `Context` (so we don't have to store a `Span` **and** a `SpanContext` in `Context`).
(Observe I tried to keep it as simple as possible in order to expedite this PR as much as possible ;) )
=> Define Propagation-only Span to simplify active Span logic in Context.

CHANGELOG.md, spec-compliance-matrix.md, specification/common/common.md
Resolves #797.
Closes #971.
This is an alternative proposal to #971 as requested in yesterday's SIG spec meeting.
This defines attempts to set `null` as undefined behavior and removes the current behavior that setting `null` removes any previously set attribute, which was opposed on #797.
Declaring it as undefined allows for non-breaking definitions of this behavior in future. Future options include ignoring such calls with or without deleting any previously set attribute for that key, or preserving `null` as a valid value, with or without preserving its type, if any.
=> Define `null` as an invalid value for attributes and declare attempts to set `null` as undefined behavior

CHANGELOG.md, specification/sdk-environment-variables.md
Fixes the remaining bits of #680 
After the updates done by #960 and #962 there were only minor refinements left.
Did leave out the part regarding spaces, as this is something that can be specified later on for the entire variables that take multiple values ;)
cc @trask @codeboten
=> OTEL_PROPAGATORS refinements

CHANGELOG.md, specification/metrics/api.md
Apply #625 decision to the API spec: The term "Additive" is replaced by "Adding", and "Non-Additive" is replaced by "Grouping". See the [comment here](https://github.com/open-telemetry/opentelemetry-specification/issues/625#issuecomment-676563191).
Fixes #625.
=> Metrics terminology (Adding/Grouping)

specification/baggage/api.md, specification/context/api-propagators.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/879
During the w3c meeting there was a consensus to use the current w3c baggage definition, and avoid using a custom header name.
=> Remove custom header name for Baggage, use official header

CHANGELOG.md, specification/trace/sdk.md
Fixes #856
Added `Tracestate` to `SamplingResult`
Related [oteps](https://github.com/open-telemetry/oteps) https://github.com/open-telemetry/oteps/pull/135
=> Allow samplers to modify tracestate

specification/trace/api.md
I know there's an OTEP that was rejected about this but I'm resurrecting this topic. The OTEP contends that it is important to allow extensibility to `SpanContext` to enable certain use cases such as lazy ID generation.
I'd like to propose that even outside of use-case concerns, this is too strict of a spec since it brings language concerns (class inheritance) into the cross-language spec. Languages may have a language-specific reason to allow a non-sealed `SpanContext`. For example, in Java, we have a need to hide the implementation of `SpanContext` from a user app to prevent compatibility issues between auto instrumentation and the app which without special care, can share classpath and have collisions. This can be done efficiently if `SpanContext` is an interface - two interfaces, one …
=> Remove restriction that SpanContext must be a final class, specify creation.

specification/trace/sdk_exporters/jaeger.md, specification/trace/sdk_exporters/zipkin.md
otel.instrumentation_library.name and otel.instrumentation_library.version
are quite long. The keys increase the size of the wire data (and they are present
for every span emitted by OpenTelemetry).
Long keys may also cause trouble when formatting in the UI.
This change uses a shorter "otel.library" prefix. I think this does not create
any ambiguity, it appears that this is the only "library" OpenTelemetry-emitted
span should refer to.
I am not attached to any particular name, open to any other naming suggestions
as long as they are reasonably short.
=> Shorten otel.instrumentation_library.* attribute names

spec-compliance-matrix.md
Updating the spec compliance matrix, as part of this change, added links to track all the issues for items not currently supported. The idea here is to:
- help maintainers understand where the work is tracked
- give SIGs an easy way to find issues they can use as a template
- give users a way to find ways they can help the project for features they want/need
The downside of this change is the formatting on the table is uglier.
=> Updating spec compliance for Python

specification/resource/semantic_conventions/cloud.md
Before some cloud provider values were given as an examples but it was still
left open to interpretation about what that meant. This makes it more explicit
that these are known values for those particular cloud providers.
=> Explicitly specify cloud.provider values for common cloud providers

semantic_conventions/trace/messaging.yaml, specification/trace/semantic_conventions/messaging.md
Updated Messaging semantic convention to the YAML format.
Related issues #547
=> Add yaml semantic conventions for Messaging

CHANGELOG.md, spec-compliance-matrix.md, specification/trace/sdk.md
- Fix CHANGELOG entry.
- Use SHOULD for the tracestate change.
- Add it to the compliance matrix.
Related to #988 
Note: Realized we need to add the list of the built-in samplers to the compliance matrix, but will do that in another PR.
=> Follow up for #988.

specification/protocol/otlp.md
MUST is the correct requirement here. There is no situation when a different content type is a better choice.
=> Fix the unclear SHOULD requirement for "gzip" OTLP content type

semantic_conventions/resource/service.yaml, semantic_conventions/resource/telemetry.yaml, specification/resource/semantic_conventions/README.md
Fixes #547
**Editorial change**.
This PR introduces the YAML definitions of service and telemetry resource attributes.
=> Add telemetry and service yaml

specification/trace/api.md
* Updates left over mention of `SpanContext` as parent for the situation after only allowing `Context` as parent (#875) and not allowing to store `SpanContext` directly in `Context` / introducing Propagated Span (#994).
This should be only an editorial change, there is no intent to change meaning, thus no CHANGELOG update.
=> Trace API: Update mentions of SpanContext as parent.

CHANGELOG.md, specification/sdk-environment-variables.md
Signed-off-by: Pavol Loffay <ploffay@redhat.com>
Add prometheus exporter env vars.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/385
=> Add prometheus exporter env vars

CHANGELOG.md, specification/trace/api.md, specification/trace/semantic_conventions/http.md
=> Change Status to be consistent with Link and Event

semantic_conventions/resource/cloud.yaml, semantic_conventions/resource/container.yaml, semantic_conventions/resource/deployment_environment.yaml, specification/resource/semantic_conventions/cloud.md, specification/resource/semantic_conventions/container.md, specification/resource/semantic_conventions/deployment_environment.md
Fixes #547
**Editorial change**.
This PR introduces the YAML definitions of Cloud, Container, and Deployment environment resource attributes.
=> Add yaml for Cloud, Container, and Deployment resource attributes

CHANGELOG.md, specification/baggage/api.md
Also update the description of the propagator to clarify metadata propagation.
Fixes #1050 
Adds the concept of baggage entry metadata, and explains how to propagate the W3C baggage.
=> Update the baggage spec to include opaque metadata.

specification/trace/api.md
=> Clarify that link and event don't need to be objects in the API

semantic_conventions/resource/faas.yaml, semantic_conventions/resource/host.yaml, specification/resource/semantic_conventions/faas.md, specification/resource/semantic_conventions/host.md
Fixes #547
**Editorial change**.
This PR introduces the YAML definitions of FaaS and Host resource attributes.
=> Add yaml for FaaS and Host resource attributes

spec-compliance-matrix.md
Follow-up for issue #510 (PR #875).
* Update compliance matrix for removal of support for Span and SpanContext as explicit parents.
I think this should be merged before renaming SpanContext to SpanReference to avoid confusion: #1075.
=> Update compliance matrix for removal of SpanContext or Span as parent (#510)

CHANGELOG.md, specification/trace/api.md
Resolves: https://github.com/open-telemetry/opentelemetry-specification/issues/1069
=> Remove "canonical" adjective from Status Code

specification/baggage/api.md
Fixes #1051
Updates the Baggage API to clarify that the Baggage may be implemented with an immutable struct/object.
=> Add a note to the Baggage API to clarify that languages are free to use language-friendly idiom to implement the API.

CHANGELOG.md, spec-compliance-matrix.md, specification/metrics/api.md, specification/metrics/sdk.md, specification/trace/api.md, specification/trace/sdk.md
=> Add a Shutdown() method to `*Provider` SDK

CHANGELOG.md, spec-compliance-matrix.md, specification/context/api-propagators.md, specification/metrics/api.md, specification/overview.md, specification/trace/api.md, specification/trace/sdk.md, specification/trace/semantic_conventions/messaging.md
Renamed `SpanContext` to `SpanReference`. This is done in order to prevent the overuse of the `Context` term.
Inspired by the discussion happening in #1033 - see https://github.com/open-telemetry/opentelemetry-specification/pull/1033#issuecomment-703760402
=> Rename SpanContext to SpanReference.

CHANGELOG.md, specification/trace/api.md
=> Clarify context interaction for trace module

specification/trace/sdk_exporters/jaeger.md
Currently the spec does not clarify this as far as I can tell. Today, multiple implementations map Otel Event's `name` field to a Jaeger Log attribute with `message` as the key while `dropped_attributes_count` is completely dropped. I propose we use different names for attributes keys for Event fields that don't have a direct Jaeger Log counter-part as,
1. It's more in-line with the rest of the spec where we use `otel.*` attribute keys to map similar fields to attributes.
2. `message` is a very generic event/log attribute that users or instrumentation might actually try to set and this translation would overwrite it.
=> Clarify how Otel Events should map to Jaeger Logs

semantic_conventions/trace/faas.yaml, specification/trace/semantic_conventions/faas.md
Fixes #547
**Editorial change**.
This PR introduces the YAML definitions of FaaS span attributes.
=> Add yaml for FaaS trace attributes

spec-compliance-matrix.md
As discussed in the maintainers meeting. These spec entries are already tracked under the tracing section.
=> Remove error handling section from compliance matrix

specification/metrics/api.md
I found a small typo while reading through the metrics api specification 😄  
* `Languages` was misspelt as `Languges`.
=> small typo in the metrics API spec

CHANGELOG.md, specification/baggage/api.md
Fixes #1070
Clarifies that the Baggage API MUST be functional with only the OpenTelemetry API, without an installed SDK.
=> Add a directive that the Baggage API must function, even without an SDK.

spec-compliance-matrix.md
The current `+` refer to the old Status API taking `StatusCanonicalCode`. This entry is for tracking the new API as per #966 and #1081.
Follow-up of #1107.
=> Add spec compliance matrix entry for StatusCode

semantic_conventions/trace/messaging.yaml, specification/trace/semantic_conventions/messaging.md
Fixes #977
Update tracing semantic conventions for messaging systems to better reflect "non-traditional" approaches such as Apache Kafka.
Include recommended semantic attributes for Apache Kafka
=> Resolve semantic inconsistencies for non traditional messaging

CHANGELOG.md, spec-compliance-matrix.md, specification/context/api-propagators.md, specification/overview.md, specification/trace/api.md, specification/trace/sdk.md, specification/trace/semantic_conventions/messaging.md
Fixes #1126 
I'd like to get the eyes of as many people as possible. We will also reserve a few days before (hopefully) merging this.
=> Revert "Rename SpanContext to SpanReference. (#1075)"

specification/trace/api.md
Fixes #1087, closes #1124, closes #1125
Makes clear that the non-recording span / propagated Span has no semantic meaning and should not be a new public type.
=> Make clear the propagated/non-recording span concept needs no type.

specification/context/api-propagators.md
Fixes #1004 
This PR clarifies how OpenTelemetry should handle the B3 debug trace flag and parent span id propagation. 
As discussed in issue #1004, OpenTelemetry does not support client and server spans sharing an id when they are part of the same request. To enable this, B3 support propagating a parent span id, in addition to the current span id. As a result, OpenTelemetry safely ignore the parent span id when propagating B3.
When receiving a B3 debug trace flag, an OpenTelemetry implementation should preserve and propagate the debug trace flag, but internally treat it as a sampled trace flag.
See https://github.com/openzipkin/b3-propagation for more details.
=> Clarify b3 debug flag and parent span id handling

experimental/trace/zpages.md, specification/context/api-propagators.md, specification/resource/semantic_conventions/process.md
"CAN" is not a standard normative word used in specs. Replace with MAY.
"CAN" indicates the ability. "MAY" indicates permissibility, which is the concern of the spec.
=> Replace CAN with MAY

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md
Adds `OTEL_TRACE_SAMPLER`, required for properly resolving #1105 .
This is a super minimalistic, but hopefully correct approach. Following @jmacd's comment about the possibility of adding sampling for metrics in the future, I added `TRACE` in it.
=> Add OTEL_TRACE_SAMPLER.

CHANGELOG.md, specification/resource/semantic_conventions/process.md
Fixes #831, fixes #997
* Splits process.runtime as a separate semantic convention from process (fixes #997)
* No longer require PID in any case (would also fix #997, but this is mainly for languages where the pid is not available)
* Split process.command_args from process.command_line (fixes #831).
=> Overhaul process command-line resource conventions.

specification/resource/semantic_conventions/process.md
Editorial change, no related issue.
Main benefit: The individual runtimes are now linkable (e.g. `#java-runtimes`).
Related: #1137
=> Rework headings of process semantic convention, add TOC.

specification/trace/api.md
Clarifies the location of the tracing interaction with `Context`, i.e. we want to say that this logic can exist **anywhere** in the API, as long as it exists in a single place.
The mention of a `TracingContextUtils` class seemed like a *too-specific* suggestion, hence the removal (in Java we had this class, but ended up putting the `Context` interaction as static/instance `Span` directly).
=> Clarify the location of tracing's Context interaction.

specification/baggage/api.md, specification/trace/semantic_conventions/messaging.md
Randomly noticed this - removes usage of SHALL for MUST which is much more common in our spec, and means the same. Consistency can reduce some cognitive load.
=> Use MUST consistently instead of shall.

specification/resource/semantic_conventions/process.md
Fixes open-telemetry/opentelemetry-python#1127
Specifies `process.runtime.*` attributes for Python.
CC @open-telemetry/python-approvers
=> Specify process.runtime for Python.

specification/trace/sdk_exporters/zipkin.md
`Span.Status` is not related to gRPC codes anymore.
=> Update status serialization for Zipkin (was: Remove mention of gRPC status codes)

CHANGELOG.md, semantic_conventions/trace/database.yaml, specification/trace/semantic_conventions/database.md
Fixes #1104
This PR adds a new attribute to the trace semantic conventions for database operations: `db.table`, and adds guidance that this attribute should be set only if the value is readily available from the library being instrumented. 
It also changes the guidance around `db.operation` to indicate that it should be set to the SQL keyword, but also only if the value is readily available from the library being instrumented.
=> Database semantic conventions: Add db.table, allow SQL keyword as db.operation

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md
Fixes #1105 
Closes #1190 (alternative solution)
It was discussed in the latest TC meeting trying out the approach taken by [Jaeger](https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L122), which uses two environment variables to configure samplers:
1) JAEGER_SAMPLER_TYPE
2) JAEGER_SAMPLER_PARAM: the Sampler-specific parameters (as defined by each specific type).
This way, each `Sampler` will use the same environment variable, and we could even extend the future expected input, i.e. accept json.
=> Add OTEL_TRACE_SAMPLER_ARG env variable definition.

CHANGELOG.md, specification/common/common.md
Fixes #1203
Removes ordering requirement for attributes for now.
If we decide this is helpful, we can add it back after GA. But if we have it in GA and decide it is not worth it (e.g. for performance reasons), removing this would be a potentially breaking change for users.
CC @jkwatson
=> Remove ordering reqirement for attributes.

specification/trace/semantic_conventions/http.md
Fixes #1204
This is an editorial change. These span status codes were made obsolete in #966, and should have been removed then.
=> Remove deprecated span status codes from http semantic conventions

specification/metrics/semantic_conventions/README.md
This PR is part of the solution to issue #600.
This PR is a clarification in the general metrics semantic conventions guidelines. It adds some guidelines about when to use a pluralized metric name (like `system.paging.faults`) and when to use a singular name (like `http.server.duration`).
Related issues #600 and #705
Related oteps: [#108](https://github.com/open-telemetry/oteps/pull/108)
=> Add metric name pluralization guidelines

specification/common/common.md
Fixes #1115 
Provides proposal for attribute name pluralization guidelines
Depends on https://github.com/open-telemetry/opentelemetry-specification/pull/1109/files
* [Trace payload/message size in semantic convention is inconsistent #1053
](https://github.com/open-telemetry/opentelemetry-specification/issues/1053)
* [Add metric name pluralization guidelines #1109](https://github.com/open-telemetry/opentelemetry-specification/pull/1109)
* [process.command_line accepts multiple value types #831](https://github.com/open-telemetry/opentelemetry-specification/issues/831)
=> Include attribute name pluralization guidelines (#1115)

specification/common/common.md
This topic has come up at least 3 times now. I believe a clarification is
warranted. The clarification is aligned with previous recommendations:
https://github.com/open-telemetry/opentelemetry-specification/pull/789#issuecomment-675506855
https://github.com/open-telemetry/opentelemetry-specification/pull/882#issuecomment-690945900
https://github.com/open-telemetry/opentelemetry-specification/pull/1194#issuecomment-722431982
=> Add guidance on when to use and not use nested namespaces

CHANGELOG.md, specification/common/common.md
Fixes #1213, closes #1155.
Clarify null SHOULD NOT be allowed even in arrays.
CC @anuraaga
=> Nulls SHOULD NOT be allowed in arrays.

specification/context/api-propagators.md
Initial addressing of #1047 
OTel repos won't initially contain any third party propagator (such as OT or AWS). @alolita will do the related follow-up, but this is a first step to put us back in the [original agreement](https://github.com/open-telemetry/opentelemetry-specification/issues/1047#issuecomment-703748553).
=> Remove the need to maintain third party propagators.

CHANGELOG.md, specification/trace/sdk_exporters/jaeger.md
Documents how service name must be mapped to Jaeger spans.
=> [jaeger exporter] Document mapping of service name

CHANGELOG.md, specification/protocol/exporter.md, specification/protocol/otlp.md
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/1148
Note that a separate port is used for OTLP/HTTP for now. There is currently work
in progress to confirm that we can use the same port. Once we have the confirmation
I will update the spec again to use one port.
=> Change default OTLP port number

specification/sdk-environment-variables.md
from: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md#b3-requirements:
> MUST provide configuration to change the default injection format to B3 multi-header
Because `b3` is a single header propagator, it's useful to  have `b3multi` value for OTEL_PROPAGATORS to inject multi-header.
=> add b3multi to OTEL_PROPAGATORS

spec-compliance-matrix.md
Related to #1254
Missed one of the Zipkin items the .NET library supports.
/cc @cijothomas @reyang
=> Updated exporter matrix for .NET library (part 2)

CHANGELOG.md, specification/resource/semantic_conventions/process.md
Add java.vm.name to process.runtime.description. I think (except for Eclipse J9), the result reads cleaner and is more informative.
Related: https://github.com/open-telemetry/opentelemetry-java/issues/1908#issuecomment-728909456
=> Add java.vm.name to process.runtime.description & more examples.

specification/protocol/otlp.md
It seems wired that the closing tag of `<details>` is missing. As a result, most of the content has been folded. 
Added a closing `</details>` tags to only fold the table of contents.
Before the change:
After the change:
=> Add missing details closing tag

specification/resource/sdk.md
1. changed a stale link
2. changed the link name: The W3C Correlation-Context is now called "Baggage"
both issues are caused by https://github.com/w3c/baggage/commit/307affc8323e05425dfa9898544f03906ee8355c
=> fixed stale link and updated link name

spec-compliance-matrix.md
Wanted to ensure we have visibility across all languages in otel on the compliance matrix, I added a column for swift.
@open-telemetry/swift-approvers please fill in the matrix when possible.
=> adding column for swift to compliance matrix

specification/logs/overview.md
OTLP/JSON is currently using trace_id, span_id field naming. The snake case
with underscores comes from Protobuf/JSON mapping rules.
Elsewhere we were previously using traceid, spanid, traceflags without underscores.
This changes standardizes field names to use underscores for all text log mediums
where these fields may be recorded.
Note: the alternate approach, i.e. keeping traceid, spanid, traceflags and renaming
them in OTLP/JSON would result in OTLP/JSON format having an inconsistent naming,
since all other fields use snake casing.
=> Standardize TraceId/SpandId/TraceFlags field casing in log formats

spec-compliance-matrix.md
=> Add default service.name to the compliance matrix.

CHANGELOG.md, spec-compliance-matrix.md, specification/trace/sdk.md
Fixes #896
Make the SDKs commit to providing a way for IDs to be customizable by including it in the specifications.
How they do so is up to the SDKs individually.
Providing this will solve the problem of **having traces incompatible with some backends** as discussed in the linked issue.
=> Require the SDK to provide custom ID generation

spec-compliance-matrix.md
Added customizable SDK Trace and Span ID generation: https://github.com/open-telemetry/opentelemetry-ruby/pull/529
=> Update spec compliance matrix for Ruby

specification/trace/api.md
=> fix small typo error in tracing spec api.md

semantic_conventions/resource/faas.yaml, specification/resource/semantic_conventions/faas.md
Fixes #
This PR introduces the new attribute `max_memory` to the `faas` resource attributes. Maximum memory allocated to a serverless function is a useful metric since e.g. too little memory can easily stop a Java AWS Lambda function from working correctly.
=> Introduce resource attribute `faas.max_memory`

spec-compliance-matrix.md
SDK Trace & Span ID generation is customizable - this row was marked as done for .NET. This is not fully true.
1. For spanid, there is no customization allowed now.
2. For traceid, there is no proper support for this now. The id generation is part of the .NET runtime itself. Currently a workaround (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/master/src/OpenTelemetry.Contrib.Extensions.AWSXRay/AWSXRayIdGenerator.cs#L60) is used by AWSXRay generator, to somewhat achieve custom traceid generation.
Related [oteps](https://github.com/open-telemetry/oteps) …
=> Fix .NET spec matrix

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md
Fixes #1309
Fixes #1313
Splits `OTEL_EXPORTER` into two variables that only accept a single value. This makes the syntax of the variable consistent with others (singular name, singular value) and removes some corner cases in configuration caused by the previous list (multiple jaeger exporters accept different format for endpoint, push / pull metrics exporters can't be enabled at the same time, inconsistency in not having a way of enabling multiple exporters of a same type).
=> Split OTEL_EXPORTER to OTEL_TRACE_EXPORTER and OTEL_METRICS_EXPORTER

CHANGELOG.md, spec-compliance-matrix.md, specification/resource/sdk.md
Required for #1346.
Resolves parts of #1184.
As agreed (except for the empty-string change) in the spec meeting, this is a pre-requesite for the updated default resource wording of #1294.
- Remove special case for empty string when merging resources.
- Let the second argument take precedence, i.e. x.Merge(y) will have values from y on conflict.
=> Make Resource.Merge consistent with Span.SetAttribute.

specification/trace/sdk_exporters/jaeger.md
Jaeger exporters usually include Thrift-over-UDP exporter that is the default in Jaeger native SDKs, but the spec was only mentioning the Protobuf model. Added link to Thrift model.
=> [jaeger] Point to Jaeger Thrift format

CHANGELOG.md, specification/trace/sdk_exporters/jaeger.md
Provide additional details for mappings needed to be supported in Jaeger exporters.
Related issues #1237
=> Fix TODOs in Jaeger exporter spec

.github/workflows/checks.yaml
Use a fixed version for the semantic convention tool. 
This way, we will not block other spec PRs if we update the tool. 
Examples of this problem: 
- https://github.com/open-telemetry/opentelemetry-specification/pull/1342#event-4204907874
- https://github.com/open-telemetry/opentelemetry-specification/pull/1339#issuecomment-768226487
=> Pin Semantic Convention tool to v0.2.1

CHANGELOG.md, specification/trace/sdk_exporters/jaeger.md, specification/trace/sdk_exporters/zipkin.md
Fixes #1237 
Fixes #1380 
Small clarification on using the default `Resource` is no `service.name` was used.
PS - Don't think we need a CHANGELOG entry for this, but happy to add one if needed.
=> Small clarification for default's service.name for exporters.

spec-compliance-matrix.md
Samplers doesn't allow modifying tracestate: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1708
New Span ID created also for non-recording Spans: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1709
No explicit parent Span https://github.com/open-telemetry/opentelemetry-dotnet/issues/1676
=> Update Dotnet compliance matrix

specification/resource/sdk.md
Fixes some portion of #1184 
Spec says Resource attribute can be any type (string, int, bool etc.) allowed in common attribute (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes). Yet the Retrieve Attribute section hints that name/value should be strings. Its best to remove this sentence to avoid any confusion. 
This is just editorial change, not changing actual spec.
=> Remove contradictory and confusing statement from Resource Attributes

spec-compliance-matrix.md
Updated .NET spec compliance. Added Resource compliance.
IsRecording becoming false OnEnd not supported. (https://github.com/open-telemetry/opentelemetry-dotnet/pull/1758)
=> Update dotnet spec compliance matrix

specification/protocol/exporter.md, specification/sdk-environment-variables.md
Adapts #1340
- Reserve ZIPKIN format environment variable for post 1.0 implementation.
- Update specification to keep OTLP protocol + ZIPKIN protocol story consistent for 1.0 (request from @bogdandrutu, note: seeing this, I'm not sure I agree, looking for feedback)
Related issues #1336
=> Modify Exporter format variables for 1.0 (allowing further specification post 1.0)

CHANGELOG.md, specification/protocol/exporter.md
Follow up to #1358 
- Adds a CHANGELOG entry
- Updates the OTLP environment variables with the actual latest names.
Removed an example that is not valid anymore as well.
=> Update CHANGELOG and OTLP env vars with the latest names.

CHANGELOG.md, specification/protocol/otlp.md
Fixes #1397 
Adds minimal clarifications.
Specifically, for OTLP/HTTP it simply mentions that we are stable for the Binary part, while being experimental for the JSON one. I'm also open to rewrite these sections to have them clearly separated, although that would probably be an overkill, given that they both share **a lot**.
=> OTLP stability clarifications

semantic_conventions/syntax.md, specification/trace/api.md, specification/trace/sdk.md, specification/trace/sdk_exporters/zipkin.md, specification/trace/semantic_conventions/rpc.md
Per https://tools.ietf.org/html/rfc2119, the work "NOT" must also be capitalized.
Skipping changelog since this is a stylistic change.
=> Fix capitalization of MUST NOT/SHOULD NOT

specification/context/api-propagators.md
Fixes #1391 
Adds  `OT Trace` propagator as a (very) optional extension component.
cc @yurishkuro
=> Add OT Trace Propagator.

CHANGELOG.md, specification/sdk-environment-variables.md
Presuming this was just missing from #1402. Hope it can be added without much ceremony, otherwise recommend renaming OT Trace to OT Tracer for the spec entry (matches the header name)
=> Update ottrace environment variable to match spec.

specification/trace/sdk.md
In the context propagators we explicitly forbid vendor specific propagators in the core distributions, apply the same logic for IdsGenerator.
=> Clarify IdsGenerator, same requirement for vendor specific code like Propagators

specification/sdk-environment-variables.md, specification/versioning-and-stability.md
Fixes #
Resolves v1.0 blocker identified here: [](https://github.com/open-telemetry/opentelemetry-specification/pull/1372#issuecomment-775278062)
* Marks "OpenTelemetry Environment Variable Specification" document as stable
* Marks "Versioning and stability for OpenTelemetry clients" document as stable
=> Mark Versioning documents as stable

specification/trace/sdk.md
Not urgent, but with this proposal we kind of have a top down structure, start from top level object (TraceProvider) and go into details later.
=> Reorder entries in the trace/sdk.md. No other changes

CHANGELOG.md, specification/sdk-environment-variables.md, specification/trace/sdk.md
128 is based on the value used in OpenCensus and it was not a problem there. See https://github.com/census-instrumentation/opencensus-java/blob/3d7f0b511dea392bbf68ee5268dd95857552dd87/api/src/main/java/io/opencensus/trace/config/TraceParams.java#L36
The limits for attributes and links were smaller, but I applied a max(of_all) function.
=> Update default for span limits to 128, 1000 seems off

spec-compliance-matrix.md
See https://github.com/open-telemetry/opentelemetry-go/issues/1515
=> Go implementation of SpanContext does not confirm with w3c

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md, specification/trace/sdk.md
Followup from https://github.com/open-telemetry/opentelemetry-specification/pull/1407 when we were asked to exclude the environment variables for the span limits.
**Update:**
Discussed with the @open-telemetry/technical-committee if we want to have this or not, and decision was to include this PR in the version 1.0 that will be released today:
* This PR does not add a new functionality, the limits were defined before and defined only as configurable via ENV variables. Having the limits was and will remain optional. 
* This PR indeed does make required to add the code configuration as well and standardize it, for languages that implement this feature, but all languages which support the ENV variables have a way to configure this via code anyway, so this PR tries only to standardize on that …
=> Finalize SpanLimits definition, add option to configure it

specification/trace/sdk.md
Original PR https://github.com/open-telemetry/opentelemetry-specification/pull/1419 updated SDK values, but during rebase of https://github.com/open-telemetry/opentelemetry-specification/pull/1416 they were reverted by mistake.
=> correct the default span limit values to 128

CHANGELOG.md, specification/sdk-environment-variables.md
Adds `none` as an option for exporter selection. Because the default is `otlp`, there is no way to disable signal export via env vars.
=> Add none for exporter selection enums.

spec-compliance-matrix.md, specification/resource/semantic_conventions/process.md
No real change here, simply removes the TODO since it is done and updates the attributes into a table.
Related issue: https://github.com/open-telemetry/opentelemetry-erlang/issues/96
=> erlang process.runtime attributes: remove TODO note and update descriptions

CHANGELOG.md, spec-compliance-matrix.md, specification/trace/sdk.md
Fixes #1451
Added `ForceFlush` to [Tracing SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown) like it was done for the `Shutdown` method.
=> Add ForceFlush to Tracing SDK

CHANGELOG.md, semantic_conventions/trace/database.yaml, specification/trace/semantic_conventions/database.md
Added elasticsearch to db.system semantic conventions
=> Add elasticsearch to db.system semantic conventions

spec-compliance-matrix.md
Go uses explicit context propagation, implicit context propagation support functionality is not applicable.
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1588
=> Update Go trace/context spec-compliance entry

specification/metrics/api.md
Per discussion during the [03/02/2021 Spec SIG Mtg](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit#heading=h.qjk2i7r08k0r), I'm sending this PR in hope that all the spec docs would have owners/experts clarified. This could become very useful for semantic convention spec.
@rakyll please review.
@bogdandrutu @jmacd @jsuereth I put your names as the "domain experts" for metrics API spec, please approve if you'd like to be listed in the doc. If I haven't got your approval, I'll assume that you don't want to be listed here so I'll remove your name.
=> Kick off the ownership clarification

CHANGELOG.md, semantic_conventions/trace/http.yaml, specification/trace/semantic_conventions/http.md
Example request's URL: `https://username:password@example.com:8080/path/to/file.aspx?query=1#fragment`
What is the expected attribute's value in such a case? For sure we should not pass the password. The username should not there as well per https://github.com/open-telemetry/opentelemetry-specification/pull/1502#discussion_r587860542.
Why do I think it is important? Because I saw this in OTel .NET SDK: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs#L115
Reference:
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#common-attributes
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specificati …
=> http.url MUST NOT contain credentials

CHANGELOG.md, semantic_conventions/resource/cloud.yaml, specification/resource/semantic_conventions/cloud.md
Only Google Cloud calls availability zones a zone. Renaming zone
to make the least common case an exception.
This change is a follow-up of https://github.com/open-telemetry/opentelemetry-specification/pull/1481.
=> Rename cloud.zone to cloud.availability_zone

specification/baggage/api.md
[The Baggage API states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/baggage/api.md#overview) that it can be implemented by providing functionality interacting solely with the `Context`. If an implementation chooses this option it follows that it should not be required to provide access to a Baggage object. This updates the Context Interaction section of the Baggage API to clarify this caveat and makes the caveat meaning clearer in the Overview section.
=> Scope baggage/context interaction functionality

spec-compliance-matrix.md
The [Golang context.Context](https://golang.org/pkg/context/) is used as the OTel-Go context implementation.
| Feature                | Go  |
|------------------------|-----|
| Create Context Key     | + keys are Go interfaces; e.g. `interface{}(name)` satisfies the API |
| Get value from Context | + [Context.Value](https://pkg.go.dev/context#Context)  |
| Set value for Context  | + [context.WithValue](https://pkg.go.dev/context#WithValue) |
| Attach Context         | N/A (no implicit context) |
| Detach Context         | N/A (no implicit context) |
| Get current Context    | N/A (no implicit context) |
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1600
=> Update spec-compliance-matrix context section for Go

spec-compliance-matrix.md
Fixes #1493, Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1589
Since Go use explicit `Context`, it is not suitable for Go to expose functions to implement `Get active Span` and `Mark Span active`
=> Update the spec-compliance-matrix Tracer section for Go

CHANGELOG.md, specification/trace/sdk.md
Samplers need to return a static string as a description. The string the TraceIdRatioBased sampler returns needs to be based on the sampling ratio that it is configured for. The current specification could be misinterpreted as requiring a static string that was not based on the samplers sampling ratio be used. This corrects that discrepancy.
Resolves #1524
=> Clarify the TraceIdRatioBased description format

spec-compliance-matrix.md
Additionally, mark the optional [getter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#textmap-extract)/[setter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#textmap-inject) arguments as such.
For more information see the linked issue this resolves, but for a quick overview:
| Feature                                                                          | Go |
|----------------------------------------------------------------------------------|----|
| Composite Propagator                                                             | [+](https://pkg.go.dev/go.opentelemetry.io/otel@v0.18.0/propagation#NewCompositeTextMapPropagator) |
| Global Propagator …
=> Update spec-compliance-matrix context propagators for Go

spec-compliance-matrix.md
| Feature                                                                                          | Go |
|--------------------------------------------------------------------------------------------------|----|
| [New Span ID created also for non-recording Spans](specification/trace/sdk.md#sdk-span-creation) | [+](https://github.com/open-telemetry/opentelemetry-go/blob/8b1be11a549eefb6efeda2f940cbda70b3c3d08d/sdk/trace/span.go#L526-L543)   |
New Span IDs are created for all spans. See the linked issue for more details.
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1648
=> Update spec-compliance-matrix span ID creation for Go

specification/trace/api.md
The requirement that `Span` creation can't set the newly created `Span` in `Context` is not suitable for languages that use explicit `Context`, such as Go.
This corrects that ambiguity.
Resolves #1508
=> Clarify the requirement about newly created Span

CHANGELOG.md, specification/context/api-propagators.md
If the underlying `TextMapPropagator` does not accept the optional getter and setter arguments it is unreasonable that the composite needs to require these arguments. This updates the API definition to communicate this.
=> Clarify composite inject/extract optional arguments

spec-compliance-matrix.md
Fixes https://github.com/open-telemetry/opentelemetry-go/issues/1649
Updates the spec compliance matrix to indicate that Go has conformant ID generators.
=> Update spec compliance matrix for Go IDGenerators

CHANGELOG.md, specification/trace/api.md
Fixes #1472 
Keeps the original invalid value (to be handled by the backends instead), while asking implementations to log this as an error.
=> Define the fallback tracer name for invalid values.

.github/workflows/checks.yaml, CHANGELOG.md, semantic_conventions/resource/faas.yaml, semantic_conventions/resource/process.yaml, semantic_conventions/syntax.md, semantic_conventions/trace/database.yaml, semantic_conventions/trace/general.yaml, semantic_conventions/trace/http.yaml, semantic_conventions/trace/messaging.yaml, specification/metrics/semantic_conventions/rpc.md, specification/resource/semantic_conventions/faas.md, specification/resource/semantic_conventions/process.md, specification/trace/semantic_conventions/database.md, specification/trace/semantic_conventions/http.md, specification/trace/semantic_conventions/messaging.md, specification/trace/semantic_conventions/rpc.md, specification/trace/semantic_conventions/span-general.md
This distinction was recently introduced in https://github.com/open-telemetry/build-tools/releases/tag/v0.3.0.
Note that the generic `number` type was dropped.
Fixes #1096.
=> Update semantic conventions to distinguish between int and double

.github/workflows/checks.yaml, semantic_conventions/syntax.md, specification/trace/semantic_conventions/rpc.md
Also, `double`s are not supported as enum values.
See https://github.com/open-telemetry/build-tools/releases/tag/v0.3.1.
=> Update to latest semconv table generator to fix int enum issue

CHANGELOG.md, spec-compliance-matrix.md, specification/overview.md
Adding a section to semantic conventions to capture the implementation
requirements from the languages.
This is a follow up from the spec SIG model where we
discussed we should ask each language to autogenerate
the semantic conventions keys from the YAML files.
=> Mention that semantic conventions should be autogenerated

specification/metrics/new_api.md
Fixes #1046.
Fixes #1433.
Follow up on #1533 and the Metrics API/SDK SIG.
* Reduced the scope of the metrics API spec by focusing on [OTEP146](https://github.com/open-telemetry/oteps/blob/main/text/metrics/0146-metrics-prototype-scenarios.md) scenario.
* Borrowed the idea from the stable version of Tracing API, organized the Metrics API spec in the similar flow.
* Documented the MeterProvider and Meter API.
* Added the initial skeleton of the Instrument API.
Related issues #1113 #1366
Related [oteps](https://github.com/open-telemetry/oteps)
* https://github.com/open-telemetry/oteps/blob/main/text/metrics/0146-metrics-prototype-scenarios.md
=> MeterProvider and Meter API spec

CHANGELOG.md, specification/context/api-propagators.md, specification/sdk-environment-variables.md
Fixes #1562
This PR updates the spec as discussed in #1562. It clarifies that b3 propagators for single and multi-header formats should extract both formats. The B3 single propagator should give precedence to b3 single when extracting, and inject using the single format only. Similarly, the B3 multi propagator should give precedence to b3 multi extracting and inject using only the multi format.
=> Clarify B3 requirements and configuration

CHANGELOG.md, specification/baggage/api.md
The current notes in the Baggage API contradict how the API Propagators Operation section specifies how failure to extract/inject should not clear any pre-existing Baggage. This removes the notes and instead links to the relevant section of the API Propagators.
Resolves #1526 
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1685
=> Update Baggage propagator to reference API Propagators

specification/trace/api.md
BTW, there are some inconsistent words
-  **`sampled` flag** and **`SampledFlag`** may be the same thing in `TraceFlags`?
=> fix spelling mistake

specification/trace/sdk_exporters/jaeger.md
Small fix of the thrift name in jaeger exporter doc.
=> Fix typo in thrift name

specification/compatibility/openmetrics.md
As of today, the compatibility work between OTel and OpenMetrics/Prometheus is represented as an experimental spec on the working group. This is change is adding a link to provide more visibility. We will graduate the compatibility spec to this repo once it's more mature.
=> Add a link to the Prometheus/OpenMetrics compatibility

CHANGELOG.md, spec-compliance-matrix.md, specification/protocol/exporter.md, specification/sdk-environment-variables.md
Adds `OTEL_EXPORTER_JAEGER_TIMEOUT` environment variable, similar to `OTEL_EXPORTER_OTLP_TIMEOUT`.
The Java SDK already has this as a programmatic option:
https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporterBuilder.java#L76-L83
and we would like to surface this as an environment variable.
=> Add OTEL_EXPORTER_JAEGER_TIMEOUT environment variable

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md
OTLP and Jaeger exporters have timeout environment variable. It would be nice and consistent to have same for Zipkin.
=> Add OTEL_EXPORTER_ZIPKIN_TIMEOUT environment variable

CHANGELOG.md, semantic_conventions/trace/messaging.yaml, specification/trace/semantic_conventions/messaging.md
In trace semantic conventions markdown there is a [section about rabbitmq](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#rabbitmq) with attribute `messaging.rabbitmq.routing_key`.
This attribute is not reflected in the `messaging.yaml` file [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/trace/messaging.yaml).
opentelemetry-js auto-generate the attributes from this yaml, thus it is [currently missing](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-semantic-conventions/src/trace/SemanticAttributes.ts)
=> add rabbitmq to semantic conventions yaml

specification/protocol/otlp.md
Resolves https://github.com/open-telemetry/opentelemetry-proto/issues/268
This behavior is already the documented behavior for JSON Protobuf,
see https://developers.google.com/protocol-buffers/docs/proto3#json:
>JSON value will be a decimal string. Either numbers or strings are accepted.
=> Clarify that 64 bit integer numbers are decimal strings in OTLP/JSON

specification/logs/data-model.md
Parts of the data model documents were using the term "map", the others
were using the term "key/value pair list" without clearly telling why
and how they are the same.
This change clarifies and ensures that we refer to a map of key/value pairs
that can be represented in different way in different languages.
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/1592
=> Clarify "key/value pair list" vs "map" in Log Data Model

specification/metrics/new_api.md
Follow up https://github.com/open-telemetry/opentelemetry-specification/pull/1617#issuecomment-821454608.
This has been discussed and concluded during the [metrics API/SDK spec SIG meeting](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit#).
* Used "Asynchronous Counter" as the name of the entry.
* Added description to encourage implementations to use "ObservableCounter".
* Clarified that these concepts have nothing to do with asynchronous pattern or observer pattern.
* Changed other async instruments so we have consistency.
=> Remove the "Func" name, use "Asynchronous" and "Observable"

CHANGELOG.md, specification/trace/api.md
Fixes #1619 - as discussed previously in a previous SIG call.
The `Get Tracer` operation, upon receiving an invalid value, should set the `name` to an empty string, instead of allowing null values to pass through.
=> Get Tracer operation should use an empty string if the specified `name` is null

CHANGELOG.md, specification/common/attribute-and-label-naming.md
I noticed developers adding their own attributes to this namespace
without going through the specification. We need to regulate this
namespace through the specification, just like we do it for other
semantic conventions.
=> Clarify usage of "otel." attribute namespace

specification/logs/data-model.md
Fixes #1621
[Log Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body): Fix case typo in the mapping between Elastic Common Schema and OpenTelemetry's Unified Model.
The correct case is "Attributes", "Resources", "Body", and "Timestamp" instead of "attributes", "resources", "body", and "timestamp".
Related issues: #1621
=> Log Data Model: Fix case typo reported in #1621

CHANGELOG.md, specification/trace/sdk_exporters/jaeger.md, specification/trace/sdk_exporters/non-otlp.md, specification/trace/sdk_exporters/zipkin.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/1656
The documents that describe transformations to Jaeger and Zipkin contained
duplicate information about how to record InstrumentationLibrary.
They also contained incomplete and incorrect information about how to record
dropped attribute count.
This change extracts common transformation rules into a separate document (non-otlp.md)
and references this document where appropriate.
We also define otel.event.dropped_attributes_count as the only way to record
dropped attribute count, regardless of the entity for which it is recorded.
Previously in Jaeger format we specified that for Events we must use
otel.event.dropped_attributes_count and did not specify at all what to use for Spans.
I believe using the same uniform …
=> Refactor non-OTLP Format Mapping and Fix Dropped Attribute Count bug

specification/metrics/new_api.md
Follow up #1617.
Added details to the Histogram instrument. In #1617 these were left as TODO.
=> Add details to UpDownCounter API

README.md, specification/metrics/README.md
- Where metrics data model was called out, but not linked, add links.
- Add a link to logs/metrics data model specification under protocol, as it's non-obvious how to find these.
=> Add data model links to various places where it was marked WIP

specification/metrics/api.md
Fixing spelling mistakes and typo in the metrics API spec.
=> Fix typo in the metrics API spec

CHANGELOG.md
This entry slipped into the wrong section. The PR was merged after 1.3.0 was released.
=> Fix changelog for #1643

CHANGELOG.md, specification/trace/sdk_exporters/jaeger.md, specification/trace/sdk_exporters/non-otlp.md, specification/trace/sdk_exporters/zipkin.md
Fixes #1696 
Adding a similar section to events and attributes limit to the exporter specification.
Related issues https://github.com/open-telemetry/opentelemetry-specification/issues/1656
=> adding DroppedLinksCount to non-otlp exporters section

CHANGELOG.md, spec-compliance-matrix.md, specification/metrics/api.md, specification/trace/api.md, specification/versioning-and-stability.md
This adds to the API the changes proposed in OTEP 0152:
https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md
I will submit corresponding changes to the proto repository separately.
=> Introduce Schema URL in Tracer and Meter API

CHANGELOG.md, specification/resource/sdk.md
This adds to the Resource SDK the concept of Schema URL proposed in OTEP 0152:
https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md
Related earlier PR that adds the Schema URL to the API:
https://github.com/open-telemetry/opentelemetry-specification/pull/1666
=> Define how Schema URL works for Resources

CHANGELOG.md, specification/trace/sdk.md
Fixes #1698 
Clarify that dropped counts should be reported from the SDK. Would love feedback from reviewers on whether or not this change should include a change to the matrix.
Related issues #1656
=> add note about reporting dropped attributes/events/links

specification/metrics/api.md
Follow up #1617.
Added details to the Asynchronous Gauge instrument. In #1617 these were left as TODO.
=> Add details to Asynchronous Gauge API

CHANGELOG.md, semantic_conventions/resource/device.yaml, semantic_conventions/resource/os.yaml, specification/resource/semantic_conventions/README.md, specification/resource/semantic_conventions/device.md, specification/resource/semantic_conventions/os.md
Fixes #1499
Hey folks 👋 
Apologies, I'm not fully clued up on the running process of adding new semantic attributes, only just starting to contribute to OpenTelemetry. I've created this pull request based on the suggestions of the issue above as well as my own beliefs - but I'm more hoping this will prompt a conversation. Please let me know if there's a better way to go about this.
All changes are purely additive, no breaking changes.
I've added an operating system name attribute, I believe this to be different enough to the existing `os.type` to justify its own attribute. While `os.type` will specify a more generalised "Linux" value (in this example), `os.name` can be the specific distro such as Ubuntu or Fedora. In a mobile world, from which I'm from, the `os.name` allows us to …
=> Add Device (Mobile) and OS Version Resource Semantic Attributes

.github/workflows/checks.yaml, Makefile, schemas/1.4.0, tools/schema_check.sh
This adds some minimal sanity checks to make sure we don't forget
to add the schema file when we make a release. The checks are tied
to the CHANGELOG.md.
In the future we can do more thorough verifications, e.g. parse the content
of the schema YAML file and ensure it includes the changes that we can
detect by looking at the changes at the semantic convention files.
=> Add schema file and a script with minimal checks that verifies them

specification/metrics/README.md, specification/metrics/sdk.md
Added the metrics SDK specification skeleton
Related issues #1116
Related [oteps](https://github.com/open-telemetry/oteps) [OTEP146](https://github.com/open-telemetry/oteps/blob/main/text/metrics/0146-metrics-prototype-scenarios.md)
=> Metrics SDK spec skeleton

specification/metrics/api.md
Follow up #1617.
Added details to the Asynchronous Gauge instrument. In #1617 these were left as TODO.
=> Add details to Asynchronous UpDownCounter API

specification/metrics/datamodel.md
- Fix a few typos
- Update the references pointing to metric point types in the proto and fix the proto version in the reference. I am not sure if there is a more elegant way of referencing the proto at a specific line while still pointing at the latest proto version. Doing it this way, the reference will always point at the right line. On the flip side, the references have to be updated every time a new version of the proto is released. Is there a preferred way to do this?
=> Fix a few typos in the datamodel specification

README.md
Fix project status link in the README.
Now links to https://opentelemetry.io/status/
=> Fix project status link in README

CHANGELOG.md, semantic_conventions/trace/database.yaml, specification/trace/semantic_conventions/database.md
Adds the [CockroachDB](https://www.cockroachlabs.com/) DBMS to the list of well-known identifiers for `db.system`
=> Add cockroachdb to db.system semantic conventions

CONTRIBUTING.md, specification/library-guidelines.md
While going through the docs here I noticed that in some places there was a link to Gitter, but when visiting, the chat seems stale ( last message on 1st April). 
Since there's a Slack channel I thought of sending this PR to consolidate the links, so new people don't get confused.
=> Change links from Gitter to Slack

CHANGELOG.md, specification/metrics/api.md
Prepare for the initial metrics API spec release (status = Experimental).
=> Clean up the Metrics API spec

CHANGELOG.md, specification/resource/sdk.md
The specification currently states that merging Resources and aggregating
ResourceDetectors results in an error, but does not say anything about the
resource with which the program continues to operate. This change specifies
that the resultant resource of these methods is undefined and the decision is
left to each implementation.
=> Specify result of Resource.merge error

specification/metrics/datamodel.md, specification/protocol/otlp.md
- All components outlining what data is provided and its meaning is marked as stable.
- Sections providing guidance and support for handling of data marked as experimental.
=> Mark relevant portions of Metrics DataModel stable

specification/metrics/api.md
* Editorial change - added clarification and examples about sync vs. async instruments.
Related [oteps](https://github.com/open-telemetry/oteps) [OTEP146](https://github.com/open-telemetry/oteps/blob/main/text/metrics/0146-metrics-prototype-scenarios.md)
=> Add clarification about async vs. sync instruments

specification/trace/api.md
Fixes #1360
Provides some additional clarity around Span.Kind and the meanings of the various values.
=> Clarify some details about span kind and the meanings of the values.

specification/protocol/otlp.md
The Log SIG discussed and made a decision to declare Log data model and Log part of OTLP Beta.
(See SIG meeting notes here https://docs.google.com/document/d/1cX5fWXyWqVVzYHSFUymYUfWxUK5hT97gc23w595LmdM/edit#heading=h.28y76as82bvu)
=> Declare OTLP Logs Beta

.github/auto_assign_issue.yml, .github/workflows/auto-assign-issue.yml
This is now done similarly to what we do for PRs. One thing that we had considered was to include the @open-telemetry/specs-trace-approvers team as part of this 'rotation'. Any opinions?
=> Auto assign issues.

specification/metrics/api.md
Duration Python prototype I noticed that folks were struggling if the parameter name should be called `unit` or `unit_of_measure`. Trying to make this editorial change so it helps to encourage `unit`.
=> Editorial change regarding metrics unit

CHANGELOG.md, semantic_conventions/trace/rpc.yaml, specification/metrics/semantic_conventions/rpc.md, specification/trace/semantic_conventions/instrumentation/aws-sdk.md, specification/trace/semantic_conventions/rpc.md
(no corresponding issue)
Remove `rpc.jsonrpc.method`, clarify that `rpc.method` should be used instead.
* PR that introduced JSON RPC conventions: #1643 (@Rast1234)
This change was just released in 1.4, but semantic conventions are still experimental thus a breaking change like this may be acceptable.
=> Remove rpc.jsonrpc.method, clarify rpc.method instead.

Makefile, specification/trace/semantic_conventions/span-general.md
Pulls in the fix introduced in https://github.com/open-telemetry/build-tools/pull/48 and unblocks #1759.
See https://github.com/open-telemetry/build-tools/releases for the changelog.
=> Bump semconvgen to 0.4.1

CHANGELOG.md, specification/sdk-environment-variables.md
Fixes #1755
- Allow selecting multiple exporters via `OTEL_TRACES_EXPORTER` and `OTEL_METRICS_EXPORTER`  by using a comma-separated list.
The [exporter selection environmental variables](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection) allow only to select a SINGLE one. It would be handy to allow selecting more than one e.g. `otlp,console`.
=> Allow selecting multiple exporters

CHANGELOG.md, spec-compliance-matrix.md, specification/sdk-environment-variables.md, specification/trace/sdk.md
Fixes #1750 
Adding environment variable definitions for span event and link attributes.
=> Adding environment variables for event and link attribute limits

semantic_conventions/resource/cloud.yaml, semantic_conventions/resource/cloud_provider/aws/ecs.yaml, semantic_conventions/trace/faas.yaml, semantic_conventions/trace/general.yaml, semantic_conventions/trace/http.yaml, semantic_conventions/trace/rpc.yaml, specification/resource/semantic_conventions/cloud.md, specification/resource/semantic_conventions/cloud_provider/aws/ecs.md, specification/trace/semantic_conventions/rpc.md
Remove examples for enum from YAML, as the enum members are already perfectly fine examples.
The semantic convention generator apparently uses the first enum member as example automatically.
=> Remove examples from enums.

CHANGELOG.md, semantic_conventions/resource/faas.yaml, semantic_conventions/trace/aws/lambda.yaml, specification/resource/semantic_conventions/faas.md, specification/trace/semantic_conventions/faas.md, specification/trace/semantic_conventions/instrumentation/aws-lambda.md
Fixes #1280 (through introduction of aws.lambda.invoked_arn span attribute, @mateuszrzeszutek please check if that is OK).
Addresses #1778.
- More clearly describe some FaaS attributes, in particular ID-related ones.
- Add `aws.lambda.invoked_arn` and clarify that alias must be stripped from `faas.id` resource attribute for AWS Lambda.
- Describe what IDs to use for Azure and GCP (Note: It might be impractical to collect these IDs client-side).
CC @skonto
=> Rework FaaS semantic conventions.

schemas/1.5.0
No schema changes since 1.4.0, so 1.5.0 section is empty in the file.
=> Add 1.5.0 Schema File

specification/overview.md
The word cross-cutting is explained in short in the Readme, but it would be better to link to some other article that could explain with examples to give a better understanding. I have linked to the Wikipedia article but this [Stack Overflow](https://stackoverflow.com/questions/23700540/cross-cutting-concern-example) is also good
=> Add wikipedia link for word cross-cutting concern

specification/metrics/api.md
This PR fills in some missing links to the respective instrument creation sections.
=> Add links to all specified creation operations

spec-compliance-matrix.md
The support was added in this PR https://github.com/open-telemetry/opentelemetry-go/pull/1889
=> Indicate Go supports Get Tracer with schema_url

.github/workflows/auto-assign-pr.yml
Config is separate from workflow, but uses different - vs _ conventions and I'm not very observant.
=> Fix typo in autoassign action

CHANGELOG.md, specification/metrics/api.md
Discussed during the [07/27/2021 Metrics SIG Meeting](https://docs.google.com/document/d/1-bCYkN-DWJq4jw1ybaDZYYmx-WAe6HnwfWbkm8d57v8/edit#), we are moving Metrics API to Feature-freeze.
There are several things which we will not cover in the initial metrics specification, we will revisit them after the metrics specification went Stable:
* [Hint](https://github.com/open-telemetry/opentelemetry-specification/pull/1753)
* [Dedicated Instrument for timing/duration](https://github.com/open-telemetry/opentelemetry-specification/issues/464)
* https://github.com/open-telemetry/opentelemetry-specification/issues/1732
=> Move metrics API to Feature-freeze

semantic_conventions/README.md
Improve the README file in the semantic convention directory to include a link to the attribute naming rules.
=> Improve semconv README, link to naming rules.

specification/sdk-environment-variables.md
Adds an environment variable value for the AWS X-Ray Sampler. Being a vendor sampler, it doesn't make much sense to define the Sampler itself in the spec, this is only to make sure language-specific SDK extensions offer a consistent experience for environment variables, similar to the AWS propagator.
=> Add environment variable for third party AWS X-Ray Sampler

schemas/1.6.0
No schema changes since 1.5.0, so 1.6.0 section is empty in the file.
=> Add 1.6.0 Schema File

specification/glossary.md
Fixes typo `RFC 5425` to `RFC 5424` in the glossary.
Not sure if I need to update the CHANGELOG for this since there is no section for glossary/others.
=> docs: fix RFC 5425 to RFC 5424

specification/trace/semantic_conventions/messaging.md
Minor update to the Kafka messaging example for tracing, as after seeing a real-life example of this situation it didn't look right. I now realize it makes more sense for the second producer to be a child of the receiver, as opposed to no parent and a link to the first producer.
=> Update trace example for Kafka messaging

CHANGELOG.md, specification/trace/semantic_conventions/instrumentation/aws-lambda.md
The behavior of Lambda requires that we check that the context `IsValid` in addition to checking if it sampled. We update the specs to reflect that.
Also changed the wording in the API Gateway section so that we know that the attributes are set in _both_ the "as a pure proxy" and "as a configuration for a REST API" setups of API Gateway.
=> Lambda instrumentations should check if X-Ray parent context is valid

specification/metrics/sdk.md
Add more details for an Aggregator in the Metrics Spec.
This PR is a rework of #1804 after discussions and feedback from metric SIG meetings.
=> Add details for Aggregator in Metrics Spec.

CHANGELOG.md, semantic_conventions/resource/cloud.yaml, semantic_conventions/trace/faas.yaml, semantic_conventions/trace/general.yaml, semantic_conventions/trace/http.yaml, semantic_conventions/trace/rpc.yaml, specification/trace/semantic_conventions/span-general.md
Fixes #1519 (again) and also fixes some `id`s containing spaces (`Alibaba Cloud` -> `alibaba_cloud`) or starting with numbers (`1xRTT` -> `csma2000_1xrtt`) which tripped up code generators (open-telemetry/build-tools#59).
Changes enum IDs to be lowercase.
Also changes values and briefs of `net.host.connection.subtype` and `rpc.grpc.status_code` to match the IDs. http.flavor is left unchanged since it is already quite old (but http.flavor should probably be refactored anyway separately).
=> Consistently format enums, fix non-identifier IDs.

spec-compliance-matrix.md, specification/trace/semantic_conventions/span-general.md
Adjusts the `.NET` casing to follow their brand as described in the guidelines: https://github.com/dotnet/brand/blob/main/dotnet-brand-guidelines.pdf
=> Adjust .NET casing

CHANGELOG.md, specification/sdk-environment-variables.md
jaeger-agent accepts traces on two different ports:
- `6831` for the "normal" format used by most Jaeger clients
- `6832` for a Node.js-only format
(see [docs](https://www.jaegertracing.io/docs/1.24/deployment/#agent))
I believe the default value for `OTEL_EXPORTER_JAEGER_AGENT_PORT` should therefore be `6831` and not `6832`.
=> Change default value for OTEL_EXPORTER_JAEGER_AGENT_PORT

.github/workflows/publish-schemas.yml
The action should be triggered manually after every spec release
and will copy/update schema files from this repository to the
website repository so that they become available publicly.
The publish-schemas action after manual triggering will create a PR
in https://github.com/open-telemetry/opentelemetry.io repo, and the
PR needs to be approved and merged manually.
This is similar to how we publish doc updates from language repos
to the website repo.
Resolves https://github.com/open-telemetry/opentelemetry.io/issues/577
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/1693
=> Add automated Schema File publish action

schemas/1.6.0, schemas/1.6.1
Related to the recently 1.6.1 Release.
Note: cannot retire the broken 1.6.0 Schema file too, as per the current build.
=> Add 1.6.1 Schema File

specification/context/api-propagators.md
Fixes propagator's Extract required argument.
1. Capitalize `HTTP`
2. It should be a "request", not a "response"
=> Fix propagator's Extract required argument

CHANGELOG.md, semantic_conventions/trace/http.yaml, specification/trace/semantic_conventions/http.md
Fixes #1845.
* Clarify when & why to set http.client_ip (#1845).
* Clarify that an empty string for http.host is valid and in fact recommended if there actually is an empty host header.
=> Clarify some cases for http.host and http.client_ip.

specification/metrics/sdk.md
Follow up #1864.
* Added the MetricReader interface (refer to https://github.com/open-telemetry/opentelemetry-specification/pull/1730#discussion_r669024476 for the initial discussion)
=> Add MetricReader interface

specification/metrics/sdk.md
This was previously left as TODO since it has dependency on the exporter (#1864) and reader (#1888) interface.
=> Spec out the MeterProvider ForceFlush and Shutdown requirement

CHANGELOG.md, specification/common/common.md
Fixes #1878 
Prefer global limit over model-specific limit default when model-specific limit is not set.
=> Prefer global limit over model-specific default

CHANGELOG.md, specification/metrics/sdk.md
This PR is pending on #1888 and #1913 to be merged.
Changes:
* Removed the warning & banner.
* Updated changelog.
=> Prepare for the metrics SDK experimental release

.vscode/settings.json, Makefile, semantic_conventions/README.md
Changelog: https://github.com/open-telemetry/build-tools/releases/tag/v0.6.0
Related to #1519.
This should prevent us from having invalid enum IDs like the ones we had to fix in #1863.
=> Upgrade semconv generator to v0.6.0

specification/metrics/sdk.md
Addressing the non-blocking comments / minor issues (these are nice to have, and won't block the SDK spec Experimental release):
* Addressed https://github.com/open-telemetry/opentelemetry-specification/pull/1888#discussion_r704923731 from @cijothomas
* Updated the ToC to reflect changes from #1828.
=> Metrics SDK fixes

specification/metrics/README.md
Changes:
* removed the warning message given both the Metrics API and SDK spec are ready for API/SDK authors to implement.
* editorial changes (fixing the links, update the outdated diagrams, rewrap lines)
=> Clean up the Metrics top level README

specification/metrics/api.md, specification/metrics/sdk.md
Fixes #1918.
Fixed the wording (e.g. `s/must/MUST`, `s/can/CAN/`).
Used `OpenTelemetry API authors` and `OpenTelemetry SDK authors` wording to clarify the ownership and responsibility.
=> Improve the Metrics API/SDK spec wording

spec-compliance-matrix.md
The matrix is out of date: "OTLP/HTTP binary Protobuf Exporter" for Python exists: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
Fixes #
=> Update compliance matrix

CHANGELOG.md, specification/trace/semantic_conventions/http.md
Fixes #1061
- Add semantic conventions for capturing HTTP request and response headers.
=> Capture HTTP request/response headers as span attributes

CHANGELOG.md, spec-compliance-matrix.md, specification/trace/sdk.md
This reverts commit f936f2e941ad10bf9b16b5ab15067f775f479cdb.
During today Maintainers meeting @jmacd expressed his concern about https://github.com/open-telemetry/opentelemetry-specification/pull/1658 and the direction that it moves SDK: runtime decisions in `Samplers` as opposed to configuration-time decisions of configuring SDK and/or `Tracers` with the correct `Samplers`. His opinion was that we should use the latter: all decisions based on `Resources` and `InstrumentationLibraries` can be done before providing `Tracers` to the users. Thus those `Tracers` can already use `Samplers` chosen/narrowed down based on that information. Thus they don't need to accept it in `ShouldSample` method.
Several attendees, myself including, agreed that this is a reasonable idea. It was thus decided to …
=> Revert "Add InstrumentationLibrary to Sampler.ShouldSample (#1850)"

CHANGELOG.md, specification/metrics/sdk.md
This was discussed during the [08/12/2021 #186 Metrics SIG at 11am PT](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.rf686wxmv2ru) and we concluded that `MeasurementProcessor` should be removed.
I didn't make the change at that time because we were focusing on getting the initial Experimental version done (which is achieved now).
**Note:** this CAN be part of the [spec v1.7.0 release](https://github.com/open-telemetry/opentelemetry-specification/pull/1926#issuecomment-921932216), although it does NOT HAVE TO be.
=> Remove MeasurementProcessor from the Metrics SDK spec

CHANGELOG.md, specification/common/common.md
Resources are not susceptible to scenarios where excessive attributes
can be recorded unlike Spans. Resources are also immutable and it can be
hard for some SDKs to apply the limits at source at the time the
attributes are added to a resource. Also Limits and Resources
both are generally defined and passed on to a TracerProvider which
forces a TracerProvider to either mutate the resource or generate a new
one with duplicate attributes in order to apply the limits to it.
I propose we explicitly exempt Resources from attribute limits.
Exempt Resources from attribute limits.
=> Exempt resources from attribute limits

.vscode/settings.json, Makefile, semantic_conventions/README.md
Changelog: https://github.com/open-telemetry/build-tools/releases/tag/v0.7.0
This PR itself does not introduce any changes to the semconv output but is a prerequisite for the ones in #1916.
=> Upgrade semconv generator to v0.7.0

specification/logs/data-model.md
Since we already have logs mapping from the unified model to Splunk HEC, we should define it for all fields in the unified model. This PR adds missing request context fields to the mapping.
=> Add missing fields to logs mapping from universal model to Splunk HEC
