- CODEOWNERS
according to https://github.com/open-telemetry/community/blob/master/community-members.md#specifications-and-proto
> Adding Reiley 

- specification/README.md
- specification/sampling-api.md
> sampling document

- specification/tracing-api.md
> added note that Span is an interface

- specification/tracing-api.md
> SpanData was errorneously defined as abstract

- specification/tracing-api.md
Inspired by https://github.com/open-telemetry/opentelemetry-specification/pull/105/files#r292621692
> Span.End MUST be non-blocking

- specification/tracing-api.md
fixes [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/117#discussion_r293870695) provided in #117
> change first letter to uppercase.

- README.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add OpenTelemetry Logo to README

- CHANGELOG.md
- specification/distributedcontext-api.md
See https://github.com/open-telemetry/opentelemetry-java/issues/401 and https://github.com/open-telemetry/opentelemetry-java/pull/429.
> Replace DistributedContext.getIterator with getEntries.

- work_in_progress/opencensus/StandardResources.md
- work_in_progress/opentracing/semantic_conventions.md
- work_in_progress/specification/trace/Span.md
- work_in_progress/typedspans/README.md
some links were broken, so i checked the original OpenCensus and OpenTracing specs and fixed
> fix some links

- specification/api-resources.md
> Fix broken link.

- README.md
- specification/api-metrics.md
- specification/api-resources.md
- specification/api-tracing.md
- specification/library-layout.md
Fix a few links orphaned by #188.
> Fix broken links

- specification/data-semantic-conventions.md
> Fixes ambiguity in http.url attribute description.

- specification/api-tracing.md
Seems a false negative of the misspell tool.
> Fix a typo

- specification/api-tracing.md
~~Of course the "fix" may contradict the intended meaning, I just choose the one I personally like more. 😉 Please tell me / make a new PR if a different meaning was intended.~~
Current PR version should reflect the intended meaning after feedback by @songy23  and @bogdandrutu.
> "Fix" contradictory wording in SpanContext spec.

- CONTRIBUTING.md
> Added a note about signing CLA explicitly

- specification/api-tracing.md
First part of "specing" the https://github.com/open-telemetry/oteps/blob/master/text/0007-no-out-of-band-reporting.md
> Remove start span properties that are no longer needed

- specification/api-tracing.md
> update name has a special semantics comment

- specification/api-tracing.md
- specification/sdk-tracing.md
> fix #44 IsRecordingEvents -> IsRecording

- specification/api-tracing.md
> Clarify that no Span activation happens by default.

- specification/api-tracing.md
- specification/sdk-tracing.md
> recording vs sampled explained

- specification/overview.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
> Rename OpenTelemetry service to collector

- Makefile
Revert unintended indentation changes from https://github.com/open-telemetry/opentelemetry-specification/pull/233.
> Fix indentation in makefile

- specification/concurrency.md
Replacing https://github.com/open-telemetry/opentelemetry-specification/pull/348 as it had no traction
> links are thread safe

- specification/api-metrics-user.md
This OTEP was approved: https://github.com/open-telemetry/oteps/pull/70
> Metric 'Handle' to 'Bound Instrument' (OTEP 70)

- README.md
> Add a reference to OTEPs process

- specification/api-metrics.md
Signed-off-by: Daniel González Lopes <danielgonzalezlopes@gmail.com>
> Add table of contents in api-metrics.md

- specification/overview.md
Swapped some **Span**s to **Spans**
> Fix bold characters

- specification/context.md
I was slightly confused by the semantics of the Context CreateKey method and others might be also. Added some clarification.
> clarify context key use

- CHANGELOG.md
- README.md
- specification/sdk-configuration.md
> Default SDK configuration

- specification/api-propagators.md
> Rename Setter.put to Setter.set

- specification/sdk-tracing.md
Simple replace. Seems to be an artifact from the past
> Minor clean up: Decision -> SamplingResult

- specification/trace/semantic_conventions/messaging.md
I forgot about that one on my previous PR, could be useful as well.
> Add payload size to messaging semantic conventions

- CHANGELOG.md
> Update CHANGELOG with 0.4.0/0.5.0 notes.

- specification/metrics/api.md
docs: change SumObserver to UpDownSumObserver because before we were mention UpDownSumObserver
> change SumObserver to UpDownSumObserve

- specification/trace/api.md
I think "map" is a more commonly used term for what Attributes are.
> Change "ordered mapping" to "ordered map"

- CHANGELOG.md
(Wondering whether it feels like an overkill to list the related PRs)
> Update CHANGELOG with 0.6.0 changes.

- CHANGELOG.md
- specification/trace/semantic_conventions/http.md
> Add mapping for nginx 499 http status

- specification/trace/sdk.md
Adds a small clarification to the exporter return code specification.
> Add an addendum for allowing async/callback export return results.

- specification/concurrency.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/662
Add concurrency requirements for metrics API and polish a bit trace API requirements.
> Clarify concurrency requirements for trace and metrics

- specification/overview.md
Fixes #
not work link on Log Data Model
> fix link 'Log Data Model'

- specification/trace/sdk.md
> Fix small markdownlint error, check for TC assignment

- specification/trace/semantic_conventions/README.md
Adds a link to exceptions spec from its folder's README
> Add link to exceptions from folder README

- .github/auto_assign.yml
- .github/workflows/auto-assign-tc-members.yml
> Use Auto Assign Action to assign one TC member

- spec-compliance-matrix.md
> Fix lint errors from #828

- specification/trace/api.md
> Define how trace/span ids are retrieved

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-java/issues/1570
Updates the spec compliance matrix for java.
> Update the spec compliance matrix for java.

- spec-compliance-matrix.md
I have added + and - where I am sure, but left blank where I am not.
/cc @mayurkale22 @obecny
> Update spec compliance for JS

- .github/PULL_REQUEST_TEMPLATE.md
To help track implementation of significant changes to the spec.
> Mention spec compliance matrix in the PR template

- spec-compliance-matrix.md
First pass through the compliance matrix for Python
> Compliance matrix for Python

- spec-compliance-matrix.md
> Update compliance matrix for .NET

- spec-compliance-matrix.md
First draft at filling this in. Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1073
> Update spec-compliance-matrix for Go SIG

- specification/trace/semantic_conventions/span-general.md
> Fix the rendering of the table

- spec-compliance-matrix.md
/cc @open-telemetry/javascript-approvers
> Update JS spec compliance matrix

- spec-compliance-matrix.md
This change covers the resource and context propagation sections. It also updates the value for zipkin environment variables support.
> Python compliance matrix update

- CONTRIBUTING.md
- README.md
This is the publicizing of tc notes document.
> publicize TC notes document

- .github/auto_assign.yml
> Add new TC members to auto assign script

- spec-compliance-matrix.md
Updates the compliance matrix for Java.
> update the java compliance matrix

- spec-compliance-matrix.md
Updates the compliance matrix for PHP.
> Updating PHP Compliance Matrix

- CHANGELOG.md
> Add changelog entry for the renaming of `SamplingResult` `Decision`s

- spec-compliance-matrix.md
Updates spec compliance matrix for Ruby.
> Update spec compliance matrix for Ruby

- CHANGELOG.md
- spec-compliance-matrix.md
Follow-up for #993 (CHANGELOG + addition to the Spec Matrix).
cc @arminru
> Add the official Baggage change to CHANGELOG and Spec Matrix.

- specification/protocol/exporter.md
Fixes: https://github.com/open-telemetry/opentelemetry-specification/issues/1001#issuecomment-699020209
> Clarify supported compression methods for OTLP

- specification/metrics/semantic_conventions/http-metrics.md
> Fix HTTP Metric Semantics Typos

- specification/context/api-propagators.md
Documenting this decision: https://github.com/open-telemetry/opentelemetry-specification/issues/637#issuecomment-644846847
No changes worth mentioning in changelog
> note on vendor specific propagators

- specification/trace/api.md
> Clarify where links can be added, format add-link as add-event

- CHANGELOG.md
> Fix PR number in changelog for #1021

- spec-compliance-matrix.md
Resolved in https://github.com/open-telemetry/opentelemetry-java/pull/1706
> Update spec compliance matrix for null attributes in Java

- spec-compliance-matrix.md
Minor update to compliance matrix for Python.
> Updating python compliance matrix

- semantic_conventions/resource/cloud.yaml
- specification/resource/semantic_conventions/cloud.md
Update description of Azure in cloud convention spec.
> Fix typo in cloud resource convention.

- .github/ISSUE_TEMPLATE/baggage.md
Following on PR #857 
Just an update to github issue template. 🛄
> update issue tmpl for baggage

- spec-compliance-matrix.md
Updates the spec compliance matrix for JS tracing
> Update spec compliance matrix to reflect current JS tracing

- CHANGELOG.md
Follow-up for #1027 + syntax cleanup.
> Mention new Kafka span attributes in changelog

- specification/baggage/api.md
- specification/context/api-propagators.md
- specification/trace/api.md
> Clarify that TraceContext/Baggage propagators are required.

- .github/workflows/auto-assign-tc-members.yml
see https://github.com/open-telemetry/opentelemetry-specification/pull/1137#issuecomment-715378919
Event documentation:
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
> Run "Auto Assign" workflow once draft PRs are ready for review

- spec-compliance-matrix.md
Updates the java column in the compliance matrix
> update the java compliance column

- spec-compliance-matrix.md
Update feature matrix with latest rust support
> Update rust compliance in matrix

- spec-compliance-matrix.md
Updates `spec-compliance-matrix.md` for Ruby.
> Ruby updates to spec compliance matrix

- spec-compliance-matrix.md
Changes just the Erlang column of the spec matrix to be up to date with the latest Erlang repo code.
> update Erlang column of spec compliance matrix

- README.md
Cosmtic: added error handling link to the toc
> Added link to error handling

- CHANGELOG.md
The attribute was renamed in the course of the review of PR #1141.
> Fix changelog entry for #1141

- spec-compliance-matrix.md
> Add more .NET spec matrix

- CHANGELOG.md
> Update changelog after the v0.7.0 release

- .circleci/config.yml
- .github/workflows/markdown.yaml
- Makefile
> Move markdownlint and markdown-link-check to github actions

- Makefile
> Fix markdownlint check, wrong makefile label

- spec-compliance-matrix.md
Updated exporter compliance matrix for .NET library.
/cc @cijothomas @reyang
> Updated exporter matrix for .NET library.

- spec-compliance-matrix.md
Updated compliance matrix for Swift
> Updated compliance data for Swift

- semantic_conventions/trace/database.yaml
- specification/trace/semantic_conventions/database.md
Instrumentation currently defines geode but it's not in spec yet
> Fix typo in hsqlsb convention and add geode

- CHANGELOG.md
- specification/sdk-environment-variables.md
> Define default value for traceid ratio.

- specification/metrics/semantic_conventions/system-metrics.md
Fixes #1299
Update system metrics semantic conventions to match collector https://github.com/open-telemetry/opentelemetry-collector/pull/2311
> Update system metrics with changes from collector

- specification/sdk-environment-variables.md
Fixes #1315.
Adds verbiage specifying integer limit handling for SDK configuration environment variables.
> Specify required integer limits

- specification/glossary.md
PR intends to increase clarity and build consensus by adding the following terms to glossary:
- Manual Instrumentation
- Automatic Instrumentation
> Add Instrumentation to Glossary

- spec-compliance-matrix.md
Update spec compliance for Swift
> Update spec compliance for Swift

- spec-compliance-matrix.md
Updates the compliance matrix for the latest java API/SDK.
> update the spec compliance matrix for java

- specification/baggage/api.md
- specification/context/api-propagators.md
There is no functionality change in this PR, or no new concepts added to the API.
This is a simple rewrite to ensure consistency in our specs.
> Rewrite baggage API description to be consistent with trace API

- spec-compliance-matrix.md
Update the spec compliance matrix for C++
> Update the spec compliance matrix for C++

- spec-compliance-matrix.md
Related issue in .NET repo: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1783
> More updates to DotNet compliance matrix

- specification/sdk-environment-variables.md
> [Blocking 1.0] Add status to environment variables document

- spec-compliance-matrix.md
> Reset spec compliance matrix for latest changes

- CHANGELOG.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/1431
Update dates in changelog to YYYY-MM-DD.
> Update dates in changelog YYYY-MM-DD

- spec-compliance-matrix.md
Added ForceFlush, IdGenerators and SpanLimits
> Update Swift compliance matrix

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1587
> Update spec-compliance matrix for Go TracerProvider

- spec-compliance-matrix.md
Implemented ForceFlush in the SDK TracerProvider
> Update spec compliance for Ruby

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1591
> Update spec-compliance-matrix Span section for Go

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1592
> Update Go compliance of Span -- SetAttribute

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1598
> Update Baggage section of spec-compliance-matrix for Go

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1599
> Update the spec-compliance-matrix Resource section for Go

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1596
> Update Sampling section of spec compliance matrix for Go

- .markdownlint.yaml
- CHANGELOG.md
Per the decision we should do a new release of the specs every month to ensure we include all the new changes.
> Release v1.1.0

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1602
> Update spec-compliance-matrix env vars for Go

- spec-compliance-matrix.md
Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1650
> Update the spec-compliance-matrix SpanLimits section for Go

- specification/trace/sdk.md
> Fix spelling error

- specification/overview.md
`OpenTelementry` -> `OpenTelemetry`
> fix spelling mistake

- spec-compliance-matrix.md
Features added to the C++ library:
- Composite propagator
- B3 propagator
- Jaeger propagator
- TextMap propagator
- Zipkin V2 JSON exporter
> update c++ compliance matrix

- CHANGELOG.md
#1612 had its Changelog entry in the previous release section ;)
> Fix CHANGELOG entry for #1612

- spec-compliance-matrix.md
Updated the matrix w/ the latest for Python. As I found the tables difficult to read w/ the full links, I also updated the links to use link references.
> update matrix for python

- specification/metrics/semantic_conventions/openmetrics-guidelines.md
Copy of PR #1684 by @alberto to spare them from signing the CLA for fixing a typo.
> Fix typo in openmetrics-guidelines.md

- spec-compliance-matrix.md
Update spec-compliance-matrix for C++
cc @open-telemetry/cpp-approvers
> Update spec-compliance-matrix for C++

- CHANGELOG.md
- specification/metrics/api.md
> Clarify the limit on the instrument unit

- specification/logs/data-model.md
Use `com.splunk.source` for source field for Splunk instead of `service.name`.
Related issues 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4596
> update splunk hec data model

- CHANGELOG.md
This slipped into the wrong section when it was merged yesterday.
> Move changelog entry for #1810

- schemas/1.6.0
- tools/schema_check.sh
Closes #1909
/cc @austinlparker @tigrannajaryan @carlosalberto
> Delete schema 1.6.0

- specification/metrics/api.md
> Minor improvements to the Metrics API spec wording

- spec-compliance-matrix.md
Updates the spec compliance matrix for the Erlang API/SDK.
> erlang: update spec compliance matrix

- specification/trace/api.md
Partly related: https://github.com/open-telemetry/opentelemetry.io/pull/923
/cc @austinlparker
> Copyedits of Trace API > Specifying links

- specification/metrics/datamodel.md
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Fix typo in metrics datamodel

- specification/metrics/sdk.md
> Add notes to MetricReader.Collect about overriding

- specification/metrics/sdk.md
> Clarify that reader has one exporter, but more readers can exists

- spec-compliance-matrix.md
Set status and id generators are implemented
> Erlang compliance updates

- CHANGELOG.md
Fixes missing CHANGELOG entry for #2121
> add CHANGELOG entry for #2121 no-op startspan clarification

- specification/metrics/datamodel.md
Fixes incorrect markdown formatting of Exemplars in the **Sums** section.
> Fix Exemplars as sub-list item

- specification/metrics/datamodel.md
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2231
Small typo in counting the number of point kinds.
> Fix the number of points kind in the metrics datamodel

- specification/metrics/datamodel.md
> Fix references to temporality data points, add exponential histogram

- specification/metrics/datamodel.md
> Fix time intervals to match with proto and time window definition in sum/histogram

- specification/trace/semantic_conventions/faas.md
> Add link from FaaS trace to resource attributes

- CHANGELOG.md
- specification/sdk-environment-variables.md
> Change Prometheus Exporter default host to localhost

- spec-compliance-matrix.md
Updating spec compliance matrix for PHP as of release 0.0.5
> Updating spec compliance matrix for PHP

- Makefile
- specification/logs/data-model.md
- specification/logs/overview.md
- specification/logs/semantic_conventions/media.md
/cc @austinlparker @tedsuo @carlosalberto
> [editorial]Add toc/tocstop to Logs pages

- README.md
- spec-compliance-matrix.md
* copy language headers to sub-sections of the table to make it more readable
* link to Jaeger documentation for specific protocols
* add link to compliance matrix from README
> [editorial] Improve display of compatibility matrix

- specification/trace/semantic_conventions/rpc.md
Context: #2236, at https://github.com/open-telemetry/opentelemetry-specification/pull/2236/files#r807345305
/cc @lmolkova @carlosalberto
> [editorial] Remove repeated sentence in trace semconv

- CHANGELOG.md
See #2317. No CHANGELOG was provided.
Related issues #2226.
> Add a CHANGELOG description for 2317 (Duplicate instrument registration)

- specification/metrics/api.md
- specification/trace/api.md
Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/2371
> Fix wording for instrumentation scope version

- specification/schemas/overview.md
Please consider these minor improvements - just a few things I noticed while reading this doc.
Minor spelling/grammar improvements.
> Small minor spelling/grammar improvements

- specification/error-handling.md
Align with https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#notation-conventions-and-compliance.
> Use MAY instead of may

- CHANGELOG.md
> Fix release year in changelog

- spec-compliance-matrix.md
The matrix had incorrect values for PHP, those were inspected and appropriately fixed.
> Add changes to PHP implementation

- spec-compliance-matrix.md
Fixes https://github.com/open-telemetry/opentelemetry-dotnet/issues/3146
@alanwest @cijothomas @CodeBlanch to keep my honest here.
> Update logs compliance matrix for .NET

- spec-compliance-matrix.md
`Resource detector` has been implemented
> Update values for php

- spec-compliance-matrix.md
Fixes https://github.com/open-telemetry/opentelemetry-python/issues/2590
// @open-telemetry/python-approvers
> Update python logging SDK spec compliance matrix

- spec-compliance-matrix.md
- Associate Tracer with InstrumentationScope
- Default values for `service.name`
> Changes to PHP values

- specification/metrics/datamodel.md
Fixes #2551
Fixed broken links in **datamodel.md**
> Fixed broken links in **datamodel.md**

- specification/logs/data-model.md
> [editorial] Logs data model: update heading to match section name

- spec-compliance-matrix.md
> Update java compliance matrices

- CONTRIBUTING.md
> Allow draft PRs to be created before issue is accepted

- CHANGELOG.md
see https://github.com/open-telemetry/opentelemetry-specification/pull/2292
> Add changelog entry about semantic conventions for jvm cpu metrics

- specification/README.md
- specification/overview.md
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1467
/cc @austinlparker
> [editorial] Add Hugo front matter to selected pages

- specification/compatibility/opentracing.md
> Fix trivial typo

- specification/metrics/data-model.md
Fixes broken link in metrics data model documentation.
> Fix broken link in metrics data model doc.

- specification/logs/README.md
> Fix typo in logs overview

- CHANGELOG.md
Small followup to #2755 (merely adjusting its Changelog entry).
> Put the 2755 Changelog entry under SDK Configuration.

- CHANGELOG.md
> Minor fix: move #2785 from released to unreleased

- README.md
The TC cleaned up the doc and had to create a new one.
> Update the TC Notes document link.

- .github/PULL_REQUEST_TEMPLATE.md
This pr replaces the relative markdown links with external ones. This pr replaces the relative markdown links with external ones. Also line breaks have been removed. 
You can see the result here:
---
For non-trivial changes, follow the [change proposal
process](../CONTRIBUTING.md#proposing-a-change) and link to the related issue(s)
and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the
[`CHANGELOG.md`](../CHANGELOG.md), and also be sure to update
[`spec-compliance-matrix.md`](../spec-compliance-matrix.md) if necessary.
---
For non-trivial changes, follow the [change proposal …
> [pull request template] fix internal links

- schemas/1.16.0
Required prior to do our December release (see #3012)
> Add 1.16.0 Schema.

- specification/trace/semantic_conventions/http.md
> Clarify common HTTP attributes apply to both clients and servers

- specification/trace/sdk.md
Fixes #
For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.
> trace: It is the SDK that should enforce the rule

- specification/sdk-environment-variables.md
Just a leftover from https://github.com/open-telemetry/opentelemetry-specification/pull/2919/files
> Fix typo in ExemplarFilter default

- .github/auto_assign_issue.yml
- .github/auto_assign_pr.yml
See https://github.com/open-telemetry/community/pull/1368
> Remove SergeyKanzhelev from auto-assignment

- .github/auto_assign_issue.yml
- .github/auto_assign_pr.yml
See https://github.com/open-telemetry/community/pull/1371.
> Add jack-berg to auto assignment for issues and PRs

- specification/logs/bridge-api.md
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/3268
> Proofread Logs Bridge API

- specification/metrics/api.md
> Use UCUM unit in example

- specification/common/attribute-requirement-level.md
Follow-up edits to #3270 based on @tigrannajaryan's https://github.com/open-telemetry/opentelemetry-specification/pull/3270#issuecomment-1456726906.
> Attribute requirement level follow-up edits

- specification/metrics/semantic_conventions/http-metrics.md
Add `toc` for metric http semconv markdown file
> Add `toc` for metric http semconv

- CHANGELOG.md
Relocate the changelog for #3127.
> [Editorial] Fix changelog

- CHANGELOG.md
- specification/common/attribute-requirement-level.md
Fixes #3235
Marks attribute requirement levels as stable.
> Mark attribute requirement levels as stable

- semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
- specification/metrics/semantic_conventions/runtime-environment-metrics.md
> Fix JVM buffer pool attribute description

- CHANGELOG.md
Forgot changelog entry in #3376.
> Add stable logs changelog entry

- README.md
- specification/README.md
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2704
- Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/2698
> [editorial] Use new path to spec on website

- spec-compliance-matrix.md
Update spec compliance matrix for PHP
> update spec compliance for php

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This was discussed during the 6/28/2023 TC meeting.
> Clarify the prototyping expectation

- CHANGELOG.md
- specification/logs/noop.md
- specification/metrics/noop.md
> Mark noop log bridge API and metric API documents as stable

- CHANGELOG.md
> Release 1.26.0

- specification/protocol/exporter.md
> [chore] protocol/exporter: Remove old reference

- CHANGELOG.md
Editorial
Sorry for my copy-paste error.
> Fix changelog entry for #3730

- CHANGELOG.md
> Release 1.27.0

- CHANGELOG.md
> Release 1.29.0

- specification/common/README.md
- specification/common/attribute-type-mapping.md
- specification/common/mapping-to-non-otlp.md
- I happened to notice these while working on  #3859
/cc @theletterf @svrnm
> [editorial] Add Hugo-front-matter linkTitles for common pages

- .github/ISSUE_TEMPLATE/profiling.md
TODO create the label before merging
> Add profiling issue template

- spec-compliance-matrix.md
Included in https://github.com/open-telemetry/opentelemetry-php/issues/1187
> Mark jaeger propagator as implemented for PHP

- specification/logs/README.md
- specification/logs/bridge-api.md
- specification/logs/data-model-appendix.md
- specification/logs/event-api.md
- specification/logs/sdk.md
- specification/logs/supplementary-guidelines.md
Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/3792
> Add references to logs and events OTEPs

- specification/metrics/api.md
- specification/metrics/data-model.md
- specification/metrics/noop.md
- specification/metrics/sdk.md
- specification/metrics/sdk_exporters/otlp.md
> Add references to metrics OTEPs

- CHANGELOG.md
The CHANGELOG.md has non-ASCII characters, this PR is changing them to ASCII.
> [Editorial] Use standard SPC characters

- specification/README.md
- specification/versioning-and-stability.md
Per https://github.com/open-telemetry/opentelemetry-specification/pull/4020#discussion_r1608559729
Some people confuse SHALL with SHOULD.
> Do not use SHALL and SHALL NOT

- specification/trace/tracestate-handling.md
Just fixed small typos in the TraceState handling documentation 🙏
> Fix typos in TraceState handling documentation

- specification/context/api-propagators.md
> Fix typo in `api-propagators.md`

- CHANGELOG.md
> Release 1.39.0 

- specification/logs/README.md
Fixes #4358
cc @open-telemetry/docs-approvers
> Add aliasas for recently deleted pages

- .lychee.toml
(now that semconv release is out)
> Remove link exclusion

- .github/workflows/fossa.yml
- .github/workflows/stale-pr.yaml
- .yamllint
For your consideration.
Related to the confusion here: https://github.com/open-telemetry/opentelemetry-specification/pull/4420#issuecomment-2665263112
> Update yamllint config

- CHANGELOG.md
#4321 needs a CHANGELOG entry.
> Add OTEP 4321 to the CHANGELOG.

- .github/renovate.json5
This groups dependency updates for github actions into a single pull request.
> chore: group github action dep updates

- .markdownlint.yaml
> Disable markdownlint descriptive-link-text rule

- specification/metrics/data-model.md
> Use the final collect's binary url to prevent timeouts.

- .markdownlint.yaml
> Disable markdownlint rule no-duplicate-heading

- README.md
Related to https://github.com/open-telemetry/community/issues/2830
> Standardize maintainer/approver/triager listings

- CONTRIBUTING.md
Update the (currently manual) release process and add minor details (helpful for anybody helping in the future).
> Update the release process steps.

- README.md
Related to https://github.com/open-telemetry/community/issues/2919 and https://github.com/open-telemetry/opentelemetry-specification/issues/4625.
> Add OpenSSF badges to the README file

- specification/resource/README.md
> Fix typo in Resource README.md
